#pragma once
#include <Aero/Gui/Control.hpp>
#include <Aero/Gui/ContentControl.hpp>
#include <Aero/Controls/UserControl.hpp>
#include <Aero/Gui/Panel.hpp>
#include <Aero/Controls/Decorator.hpp>
#include <Aero/Gui/StackPanel.hpp>
#include <Aero/Gui/Grid.hpp>
#include <Aero/Gui/Border.hpp>
#include <Aero/Gui/TextBlock.hpp>
#include <Aero/Controls/ContentPresenter.hpp>
#include <Aero/Gui/ButtonBase.hpp>
#include <Aero/Gui/Button.hpp>
#include <Aero/Controls/CheckBox.hpp>
#include <Aero/Controls/RadioButton.hpp>
#include <Aero/Controls/ScrollViewer.hpp>
#include <Aero/Controls/RangeBase.hpp>
#include <Aero/Gui/ItemsControl.hpp>
#include <Aero/Controls/Popup.hpp>
#include <Aero/Controls/HeaderedContentControl.hpp>
#include <Aero/Gui/ListBox.hpp>
#include <Aero/Controls/ComboBox.hpp>
#include <Aero/Controls/ListView.hpp>
#include <Aero/Gui/TreeView.hpp>
#include <Aero/Controls/VirtualizingStackPanel.hpp>
#include <Aero/Controls/Menu.hpp>
#include <Aero/Controls/ToolBar.hpp>
#include <Aero/Controls/StatusBar.hpp>
#include <Aero/Controls/ToolTip.hpp>
#include <Aero/Controls/Image.hpp>
#include <Aero/Gui/TextBoxBase.hpp>
#include <Aero/Gui/TextBox.hpp>
#include <Aero/Controls/PasswordBox.hpp>
