// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiResources(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    auto resourceDictionary =
        Meta::Register<ResourceDictionary>(context);
    resourceDictionary
        .Property<
            Base::ResourceUri,
            &ResourceDictionary::GetSource,
            &ResourceDictionary::SetSource>(
            "Source",
            PropertyFlags::None)
        .Collection<ResourceDictionary>(
            "MergedDictionaries",
            &AddMergedDictionary,
            &ClearMergedDictionaries)
        .Content<Base::Object>(
            "Entries",
            ContentKind::Collection)
        .Factory();
    status = resourceDictionary.Result();
    if (!status) return status.GetStatus();

    auto geometry = Meta::Register<Media::Geometry>(context);
    geometry
        .Property(
            "Transform", &Media::Geometry::GetTransform, &Media::Geometry::SetTransform,
            PropertyFlags::Structural)
        .Content(MakeMemberId(
            Media::Geometry::StaticTypeId(), MemberKind::Property, "Transform"))
        .TextConverter(&ConvertGeometryText)
        .Factory();
    status = geometry.Result();
    if (!status) return status.GetStatus();

    auto streamGeometry = Meta::Register<Media::StreamGeometry>(context);
    streamGeometry
        .Property(
            "Data", &Media::StreamGeometry::GetData, &Media::StreamGeometry::SetData,
            PropertyFlags::Structural)
        .Content(MakeMemberId(
            Media::StreamGeometry::StaticTypeId(), MemberKind::Property, "Data"))
        .TextConverter(&ConvertGeometryText)
        .Factory();
    status = streamGeometry.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::PathSegment>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto lineSegment = Meta::Register<Media::LineSegment>(context);
    lineSegment
        .Property(
            Media::LineSegment::PointProperty,
            FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Factory();
    status = lineSegment.Result();
    if (!status) return status.GetStatus();

    auto pathFigure = Meta::Register<Media::PathFigure>(context);
    pathFigure
        .Property(
            Media::PathFigure::StartPointProperty,
            FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(
            Media::PathFigure::IsClosedProperty,
            FrameworkPropertyMetadata(false).AffectsRender())
        .Content<Media::PathSegment>(
            "Segments", ContentKind::Collection,
            &AddPathFigureSegment, &ClearPathFigureSegments)
        .Factory();
    status = pathFigure.Result();
    if (!status) return status.GetStatus();

    auto pathGeometry = Meta::Register<Media::PathGeometry>(context);
    pathGeometry
        .Content<Media::PathFigure>(
            "Figures", ContentKind::Collection,
            &AddPathGeometryFigure, &ClearPathGeometryFigures)
        .Factory();
    status = pathGeometry.Result();
    if (!status) return status.GetStatus();

    auto fontFamily = Meta::Register<Media::FontFamily>(context);
    fontFamily
        .Property(
            "Source", &Media::FontFamily::GetSource, &Media::FontFamily::SetSource,
            PropertyFlags::Structural)
        .Content(MakeMemberId(
            Media::FontFamily::StaticTypeId(), MemberKind::Property, "Source"))
        .TextConverter(&ConvertFontFamilyText)
        .Factory();
    status = fontFamily.Result();
    if (!status) return status.GetStatus();
    return {};
}
