// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiAnimation(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    auto timeline = Meta::Register<Media::Animation::Timeline>(
        context, TypeFlags::Abstract);
    timeline
        .Property(
            "BeginTime",
            &Media::Animation::Timeline::GetBeginTime,
            &Media::Animation::Timeline::SetBeginTime)
        .Property(
            "Duration",
            &Media::Animation::Timeline::GetDuration,
            &Media::Animation::Timeline::SetDuration)
        .Property(
            "RepeatBehavior",
            &Media::Animation::Timeline::GetRepeatBehavior,
            &Media::Animation::Timeline::SetRepeatBehavior)
        .Property<
            double,
            &Media::Animation::Timeline::GetSpeedRatio,
            &Media::Animation::Timeline::SetSpeedRatio>(
            "SpeedRatio")
        .Property<
            bool,
            &Media::Animation::Timeline::GetAutoReverse,
            &Media::Animation::Timeline::SetAutoReverse>(
            "AutoReverse")
        .Property<
            FillBehavior,
            &Media::Animation::Timeline::GetFillBehavior,
            &Media::Animation::Timeline::SetFillBehavior>(
            "FillBehavior");
    status = timeline.Result();
    if (!status) return status.GetStatus();

    auto easingBase = Meta::Register<Media::Animation::EasingFunctionBase>(
        context, TypeFlags::Abstract);
    easingBase.Property(
        Media::Animation::EasingFunctionBase::EasingModeProperty,
        PropertyOptions(EasingMode::EaseOut));
    status = easingBase.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::Animation::SineEase>(context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::QuadraticEase>(context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::CubicEase>(context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::QuarticEase>(context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::QuinticEase>(context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::CircleEase>(context).Factory().Result();
    if (!status) return status.GetStatus();
    auto exponentialEase =
        Meta::Register<Media::Animation::ExponentialEase>(context);
    exponentialEase
        .Property(
            Media::Animation::ExponentialEase::ExponentProperty,
            PropertyOptions(2.0))
        .Factory();
    status = exponentialEase.Result();
    if (!status) return status.GetStatus();

    auto powerEase = Meta::Register<Media::Animation::PowerEase>(context);
    powerEase
        .Property(
            Media::Animation::PowerEase::PowerProperty,
            PropertyOptions(2.0))
        .Factory();
    status = powerEase.Result();
    if (!status) return status.GetStatus();

    auto backEase = Meta::Register<Media::Animation::BackEase>(context);
    backEase
        .Property(
            Media::Animation::BackEase::AmplitudeProperty,
            PropertyOptions(1.0))
        .Factory();
    status = backEase.Result();
    if (!status) return status.GetStatus();

    auto bounceEase = Meta::Register<Media::Animation::BounceEase>(context);
    bounceEase
        .Property(
            Media::Animation::BounceEase::BouncesProperty,
            PropertyOptions(3.0))
        .Property(
            Media::Animation::BounceEase::BouncinessProperty,
            PropertyOptions(3.0))
        .Factory();
    status = bounceEase.Result();
    if (!status) return status.GetStatus();

    auto elasticEase = Meta::Register<Media::Animation::ElasticEase>(context);
    elasticEase
        .Property(
            Media::Animation::ElasticEase::OscillationsProperty,
            PropertyOptions(3.0))
        .Property(
            Media::Animation::ElasticEase::SpringinessProperty,
            PropertyOptions(3.0))
        .Factory();
    status = elasticEase.Result();
    if (!status) return status.GetStatus();

    auto doubleAnimationBase =
        Meta::Register<Media::Animation::DoubleAnimationBase>(
            context, TypeFlags::Abstract);
    doubleAnimationBase
        .Property<
            double,
            &Media::Animation::DoubleAnimationBase::GetFrom,
            &Media::Animation::DoubleAnimationBase::SetFrom>("From")
        .Property<
            double,
            &Media::Animation::DoubleAnimationBase::GetTo,
            &Media::Animation::DoubleAnimationBase::SetTo>("To");
    status = doubleAnimationBase.Result();
    if (!status) return status.GetStatus();

    auto doubleAnimation = Meta::Register<Media::Animation::DoubleAnimation>(context);
    doubleAnimation
        .Property<
            double,
            &Media::Animation::DoubleAnimation::GetAccelerationRatio,
            &Media::Animation::DoubleAnimation::SetAccelerationRatio>(
                "AccelerationRatio")
        .Property<
            double,
            &Media::Animation::DoubleAnimation::GetDecelerationRatio,
            &Media::Animation::DoubleAnimation::SetDecelerationRatio>(
                "DecelerationRatio")
        .Property<
            Base::Ref<Media::Animation::EasingFunctionBase>,
            &Media::Animation::DoubleAnimation::GetEasingFunction,
            &Media::Animation::DoubleAnimation::SetEasingFunction>(
            "EasingFunction",
            PropertyFlags::Structural)
        .Factory();
    status = doubleAnimation.Result();
    if (!status) return status.GetStatus();

    auto colorAnimation = Meta::Register<Media::Animation::ColorAnimation>(context);
    colorAnimation
        .Property<
            Color,
            &Media::Animation::ColorAnimation::GetFrom,
            &Media::Animation::ColorAnimation::SetFrom>("From")
        .Property<
            Color,
            &Media::Animation::ColorAnimation::GetTo,
            &Media::Animation::ColorAnimation::SetTo>("To")
        .Property<
            Base::Ref<Media::Animation::EasingFunctionBase>,
            &Media::Animation::ColorAnimation::GetEasingFunction,
            &Media::Animation::ColorAnimation::SetEasingFunction>(
            "EasingFunction",
            PropertyFlags::Structural)
        .Factory();
    status = colorAnimation.Result();
    if (!status) return status.GetStatus();

    auto pointAnimation =
        Meta::Register<Media::Animation::PointAnimation>(
            context);
    pointAnimation
        .Property<
            Point,
            &Media::Animation::PointAnimation::GetFrom,
            &Media::Animation::PointAnimation::SetFrom>(
            "From")
        .Property<
            Point,
            &Media::Animation::PointAnimation::GetTo,
            &Media::Animation::PointAnimation::SetTo>(
            "To")
        .Property<
            Base::Ref<
                Media::Animation::EasingFunctionBase>,
            &Media::Animation::PointAnimation::
                GetEasingFunction,
            &Media::Animation::PointAnimation::
                SetEasingFunction>(
            "EasingFunction",
            PropertyFlags::Structural)
        .Factory();
    status = pointAnimation.Result();
    if (!status) return status.GetStatus();

    auto rectAnimation =
        Meta::Register<Media::Animation::RectAnimation>(
            context);
    rectAnimation
        .Property<
            Rect,
            &Media::Animation::RectAnimation::GetFrom,
            &Media::Animation::RectAnimation::SetFrom>(
            "From")
        .Property<
            Rect,
            &Media::Animation::RectAnimation::GetTo,
            &Media::Animation::RectAnimation::SetTo>(
            "To")
        .Property<
            Base::Ref<
                Media::Animation::EasingFunctionBase>,
            &Media::Animation::RectAnimation::
                GetEasingFunction,
            &Media::Animation::RectAnimation::
                SetEasingFunction>(
            "EasingFunction",
            PropertyFlags::Structural)
        .Factory();
    status = rectAnimation.Result();
    if (!status) return status.GetStatus();

    auto thicknessAnimation =
        Meta::Register<
            Media::Animation::ThicknessAnimation>(
            context);
    thicknessAnimation
        .Property<
            Base::Thickness,
            &Media::Animation::ThicknessAnimation::GetFrom,
            &Media::Animation::ThicknessAnimation::SetFrom>(
            "From")
        .Property<
            Base::Thickness,
            &Media::Animation::ThicknessAnimation::GetTo,
            &Media::Animation::ThicknessAnimation::SetTo>(
            "To")
        .Property<
            Base::Ref<
                Media::Animation::EasingFunctionBase>,
            &Media::Animation::ThicknessAnimation::
                GetEasingFunction,
            &Media::Animation::ThicknessAnimation::
                SetEasingFunction>(
            "EasingFunction",
            PropertyFlags::Structural)
        .Factory();
    status = thicknessAnimation.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::Animation::DoubleKeyFrame>(
        context, TypeFlags::Abstract)
        .Property<
            double,
            &Media::Animation::DoubleKeyFrame::GetValue,
            &Media::Animation::DoubleKeyFrame::SetValue>("Value")
        .Property(
            "KeyTime",
            &Media::Animation::DoubleKeyFrame::GetKeyTime,
            &Media::Animation::DoubleKeyFrame::SetKeyTime)
        .Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::LinearDoubleKeyFrame>(
        context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::DiscreteDoubleKeyFrame>(
        context).Factory().Result();
    if (!status) return status.GetStatus();

    auto easingFrame =
        Meta::Register<Media::Animation::EasingDoubleKeyFrame>(context);
    easingFrame
        .Property(
            Media::Animation::EasingDoubleKeyFrame::EasingFunctionProperty,
            PropertyOptions(
                Base::Ref<Media::Animation::EasingFunctionBase>{})
                .AffectsRender())
        .Factory();
    status = easingFrame.Result();
    if (!status) return status.GetStatus();

    auto splineFrame =
        Meta::Register<Media::Animation::SplineDoubleKeyFrame>(context);
    splineFrame
        .Property(
            "KeySpline",
            &Media::Animation::SplineDoubleKeyFrame::GetKeySpline,
            &Media::Animation::SplineDoubleKeyFrame::SetKeySpline)
        .Factory();
    status = splineFrame.Result();
    if (!status) return status.GetStatus();

    auto doubleFrames =
        Meta::Register<Media::Animation::DoubleAnimationUsingKeyFrames>(context);
    doubleFrames
        .Content<Media::Animation::DoubleKeyFrame>(
            "KeyFrames",
            ContentKind::Collection,
            &AddDoubleKeyFrame,
            &ClearDoubleKeyFrames)
        .Factory();
    status = doubleFrames.Result();
    if (!status) return status.GetStatus();

    auto pointFrame = Meta::Register<Media::Animation::PointKeyFrame>(
        context, TypeFlags::Abstract);
    pointFrame
        .Property(
            "Value",
            &Media::Animation::PointKeyFrame::GetValue,
            &Media::Animation::PointKeyFrame::SetValue)
        .Property(
            "KeyTime",
            &Media::Animation::PointKeyFrame::GetKeyTime,
            &Media::Animation::PointKeyFrame::SetKeyTime);
    status = pointFrame.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::Animation::DiscretePointKeyFrame>(context)
        .Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::EasingPointKeyFrame>(context)
        .Factory().Result();
    if (!status) return status.GetStatus();

    auto pointFrames =
        Meta::Register<Media::Animation::PointAnimationUsingKeyFrames>(context);
    pointFrames
        .Content<Media::Animation::PointKeyFrame>(
            "KeyFrames", ContentKind::Collection,
            &AddPointKeyFrame, &ClearPointKeyFrames)
        .Factory();
    status = pointFrames.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::Animation::ThicknessKeyFrame>(
        context, TypeFlags::Abstract)
        .Property<
            Thickness,
            &Media::Animation::ThicknessKeyFrame::GetValue,
            &Media::Animation::ThicknessKeyFrame::SetValue>(
                "Value")
        .Property(
            "KeyTime",
            &Media::Animation::ThicknessKeyFrame::GetKeyTime,
            &Media::Animation::ThicknessKeyFrame::SetKeyTime)
        .Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<
        Media::Animation::LinearThicknessKeyFrame>(
            context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<
        Media::Animation::DiscreteThicknessKeyFrame>(
            context).Factory().Result();
    if (!status) return status.GetStatus();
    auto easingThicknessFrame =
        Meta::Register<
            Media::Animation::EasingThicknessKeyFrame>(
                context);
    easingThicknessFrame
        .Property<
            Base::Ref<Media::Animation::EasingFunctionBase>,
            &Media::Animation::EasingThicknessKeyFrame::
                GetEasingFunction,
            &Media::Animation::EasingThicknessKeyFrame::
                SetEasingFunction>(
                    "EasingFunction",
                    PropertyFlags::Structural)
        .Factory();
    status = easingThicknessFrame.Result();
    if (!status) return status.GetStatus();
    auto splineThicknessFrame =
        Meta::Register<
            Media::Animation::SplineThicknessKeyFrame>(
                context);
    splineThicknessFrame
        .Property(
            "KeySpline",
            &Media::Animation::SplineThicknessKeyFrame::
                GetKeySpline,
            &Media::Animation::SplineThicknessKeyFrame::
                SetKeySpline)
        .Factory();
    status = splineThicknessFrame.Result();
    if (!status) return status.GetStatus();
    auto thicknessFrames =
        Meta::Register<
            Media::Animation::ThicknessAnimationUsingKeyFrames>(
                context);
    thicknessFrames
        .Content<Media::Animation::ThicknessKeyFrame>(
            "KeyFrames",
            ContentKind::Collection,
            &AddThicknessKeyFrame,
            &ClearThicknessKeyFrames)
        .Factory();
    status = thicknessFrames.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::Animation::ColorKeyFrame>(
        context, TypeFlags::Abstract)
        .Property<
            Base::Color,
            &Media::Animation::ColorKeyFrame::GetValue,
            &Media::Animation::ColorKeyFrame::SetValue>(
            "Value")
        .Property(
            "KeyTime",
            &Media::Animation::ColorKeyFrame::GetKeyTime,
            &Media::Animation::ColorKeyFrame::SetKeyTime)
        .Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::LinearColorKeyFrame>(
        context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::DiscreteColorKeyFrame>(
        context).Factory().Result();
    if (!status) return status.GetStatus();

    auto easingColorFrame =
        Meta::Register<Media::Animation::EasingColorKeyFrame>(
            context);
    easingColorFrame
        .Property<
            Base::Ref<Media::Animation::EasingFunctionBase>,
            &Media::Animation::EasingColorKeyFrame::GetEasingFunction,
            &Media::Animation::EasingColorKeyFrame::SetEasingFunction>(
            "EasingFunction",
            PropertyFlags::Structural)
        .Factory();
    status = easingColorFrame.Result();
    if (!status) return status.GetStatus();

    auto splineColorFrame =
        Meta::Register<Media::Animation::SplineColorKeyFrame>(
            context);
    splineColorFrame
        .Property(
            "KeySpline",
            &Media::Animation::SplineColorKeyFrame::GetKeySpline,
            &Media::Animation::SplineColorKeyFrame::SetKeySpline)
        .Factory();
    status = splineColorFrame.Result();
    if (!status) return status.GetStatus();

    auto colorFrames =
        Meta::Register<
            Media::Animation::ColorAnimationUsingKeyFrames>(
            context);
    colorFrames
        .Content<Media::Animation::ColorKeyFrame>(
            "KeyFrames",
            ContentKind::Collection,
            &AddColorKeyFrame,
            &ClearColorKeyFrames)
        .Factory();
    status = colorFrames.Result();
    if (!status) return status.GetStatus();

    auto objectFrame =
        Meta::Register<Media::Animation::DiscreteObjectKeyFrame>(context);
    objectFrame
        .Property<
            Value,
            &Media::Animation::DiscreteObjectKeyFrame::GetValue,
            &Media::Animation::DiscreteObjectKeyFrame::SetValue>(
            "Value",
            PropertyFlags::AnyValue)
        .Property(
            "KeyTime",
            &Media::Animation::DiscreteObjectKeyFrame::GetKeyTime,
            &Media::Animation::DiscreteObjectKeyFrame::SetKeyTime)
        .Factory();
    status = objectFrame.Result();
    if (!status) return status.GetStatus();

    auto objectFrames =
        Meta::Register<Media::Animation::ObjectAnimationUsingKeyFrames>(context);
    objectFrames
        .Content<Media::Animation::DiscreteObjectKeyFrame>(
            "KeyFrames",
            ContentKind::Collection,
            &AddObjectKeyFrame,
            &ClearObjectKeyFrames)
        .Factory();
    status = objectFrames.Result();
    if (!status) return status.GetStatus();

    auto booleanFrame =
        Meta::Register<Media::Animation::DiscreteBooleanKeyFrame>(context);
    booleanFrame
        .Property<
            bool,
            &Media::Animation::DiscreteBooleanKeyFrame::GetValue,
            &Media::Animation::DiscreteBooleanKeyFrame::SetValue>("Value")
        .Property(
            "KeyTime",
            &Media::Animation::DiscreteBooleanKeyFrame::GetKeyTime,
            &Media::Animation::DiscreteBooleanKeyFrame::SetKeyTime)
        .Factory();
    status = booleanFrame.Result();
    if (!status) return status.GetStatus();

    auto booleanFrames =
        Meta::Register<Media::Animation::BooleanAnimationUsingKeyFrames>(context);
    booleanFrames
        .Content<Media::Animation::DiscreteBooleanKeyFrame>(
            "KeyFrames",
            ContentKind::Collection,
            &AddBooleanKeyFrame,
            &ClearBooleanKeyFrames)
        .Factory();
    status = booleanFrames.Result();
    if (!status) return status.GetStatus();

    auto storyboard = Meta::Register<Media::Animation::Storyboard>(context);
    storyboard
        .Property(
            Media::Animation::Storyboard::TargetNameProperty,
            PropertyOptions(Base::String{}))
        .Property(
            Media::Animation::Storyboard::TargetPropertyProperty,
            PropertyOptions(Base::String{}))
        .Content<Media::Animation::Timeline>(
            "Children",
            ContentKind::Collection,
            &AddStoryboardTimeline,
            &ClearStoryboardTimelines)
        .Factory();
    status = storyboard.Result();
    if (!status) return status.GetStatus();

    auto parallelTimeline =
        Meta::Register<Media::Animation::ParallelTimeline>(context);
    parallelTimeline
        .Content<Media::Animation::Timeline>(
            "Children",
            ContentKind::Collection,
            &AddStoryboardTimeline,
            &ClearStoryboardTimelines)
        .Factory();
    status = parallelTimeline.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::Animation::TriggerAction>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto keyBinding = Meta::Register<KeyBinding>(context);
    keyBinding
        .Property("Command", &KeyBinding::GetCommandName,
            &KeyBinding::SetCommandName)
        .Property("Key", &KeyBinding::GetKeyName,
            &KeyBinding::SetKeyName)
        .Property("Modifiers", &KeyBinding::GetModifiersName,
            &KeyBinding::SetModifiersName)
        .Factory();
    status = keyBinding.Result();
    if (!status) return status.GetStatus();

    auto changeProperty =
        Meta::Register<Media::Animation::ChangePropertyAction>(
            context);
    changeProperty
        .Property(
            "TargetName",
            &Media::Animation::ChangePropertyAction::GetTargetName,
            &Media::Animation::ChangePropertyAction::SetTargetName)
        .Property(
            "PropertyName",
            &Media::Animation::ChangePropertyAction::GetPropertyName,
            &Media::Animation::ChangePropertyAction::SetPropertyName)
        .Property<
            Meta::PropertyValue,
            &Media::Animation::ChangePropertyAction::GetValue,
            &Media::Animation::ChangePropertyAction::SetValue>(
                "Value",
                PropertyFlags::AnyValue)
        .Factory();
    status = changeProperty.Result();
    if (!status) return status.GetStatus();

    auto setFocus = Meta::Register<Media::Animation::SetFocusAction>(context);
    setFocus
        .Property(
            "Engage",
            &Media::Animation::SetFocusAction::GetEngage,
            &Media::Animation::SetFocusAction::SetEngage)
        .Factory();
    status = setFocus.Result();
    if (!status) return status.GetStatus();

    auto launchUriOrFile =
        Meta::Register<Media::Animation::LaunchUriOrFileAction>(context);
    launchUriOrFile
        .Property(
            "Path",
            &Media::Animation::LaunchUriOrFileAction::GetPath,
            &Media::Animation::LaunchUriOrFileAction::SetPath)
        .Factory();
    status = launchUriOrFile.Result();
    if (!status) return status.GetStatus();

    auto removeElement = Meta::Register<Media::Animation::RemoveElementAction>(context);
    removeElement
        .Property<
            Base::Ref<Data::Binding>,
            &Media::Animation::RemoveElementAction::GetTargetObject,
            &Media::Animation::RemoveElementAction::SetTargetObject>(
                "TargetObject",
                PropertyFlags::Structural)
        .Factory();
    status = removeElement.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<
        Media::Animation::ControllableStoryboardAction>(
        context, TypeFlags::Abstract)
        .Property(
            "BeginStoryboardName",
            &Media::Animation::ControllableStoryboardAction::
                GetBeginStoryboardName,
            &Media::Animation::ControllableStoryboardAction::
                SetBeginStoryboardName)
        .Result();
    if (!status) return status.GetStatus();

    auto beginStoryboard =
        Meta::Register<Media::Animation::BeginStoryboard>(context);
    beginStoryboard
        .Property(
            "Name",
            &Media::Animation::BeginStoryboard::GetName,
            &Media::Animation::BeginStoryboard::SetName)
        .Content<Media::Animation::Storyboard>(
            "Storyboard",
            ContentKind::Single,
            &SetBeginStoryboardContent,
            &ClearBeginStoryboardContent)
        .Factory();
    status = beginStoryboard.Result();
    if (!status) return status.GetStatus();

    auto controlStoryboard = Meta::Register<Media::Animation::ControlStoryboardAction>(context);
    controlStoryboard
        .Property("Storyboard", &Media::Animation::ControlStoryboardAction::GetStoryboard,
            &Media::Animation::ControlStoryboardAction::SetStoryboard)
        .Property("ControlStoryboardOption", &Media::Animation::ControlStoryboardAction::GetControlOption,
            &Media::Animation::ControlStoryboardAction::SetControlOption)
        .Factory();
    status = controlStoryboard.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Media::Animation::PauseStoryboard>(
        context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::ResumeStoryboard>(
        context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::StopStoryboard>(
        context).Factory().Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<Media::Animation::RemoveStoryboard>(
        context).Factory().Result();
    if (!status) return status.GetStatus();
    auto seekStoryboard =
        Meta::Register<Media::Animation::SeekStoryboard>(
            context);
    seekStoryboard
        .Property(
            "Offset",
            &Media::Animation::SeekStoryboard::GetOffset,
            &Media::Animation::SeekStoryboard::SetOffset)
        .Factory();
    status = seekStoryboard.Result();
    if (!status) return status.GetStatus();

    auto eventTrigger = Meta::Register<Media::Animation::EventTrigger>(context);
    eventTrigger
        .Property(
            "RoutedEvent",
            &Media::Animation::EventTrigger::GetRoutedEvent,
            &Media::Animation::EventTrigger::SetRoutedEvent)
        .Property(
            "EventName",
            &Media::Animation::EventTrigger::GetEventName,
            &Media::Animation::EventTrigger::SetEventName)
        .Property(
            "SourceName",
            &Media::Animation::EventTrigger::GetSourceName,
            &Media::Animation::EventTrigger::SetSourceName)
        .Content<Media::Animation::TriggerAction>(
            "Actions",
            ContentKind::Collection,
            &AddEventTriggerAction,
            &ClearEventTriggerActions)
        .Factory();
    status = eventTrigger.Result();
    if (!status) return status.GetStatus();

    auto timerTrigger = Meta::Register<Media::Animation::TimerTrigger>(context);
    timerTrigger
        .Property(
            "TotalTicks",
            &Media::Animation::TimerTrigger::GetTotalTicks,
            &Media::Animation::TimerTrigger::SetTotalTicks)
        .Property<
            Meta::PropertyValue,
            &Media::Animation::TimerTrigger::GetMillisecondsPerTick,
            &Media::Animation::TimerTrigger::SetMillisecondsPerTick>(
                "MillisecondsPerTick",
                PropertyFlags::AnyValue)
        .Factory();
    status = timerTrigger.Result();
    if (!status) return status.GetStatus();

    auto propertyChangedTrigger =
        Meta::Register<Media::Animation::PropertyChangedTrigger>(context);
    propertyChangedTrigger
        .Property<
            Base::Ref<Data::Binding>,
            &Media::Animation::PropertyChangedTrigger::GetBinding,
            &Media::Animation::PropertyChangedTrigger::SetBinding>(
                "Binding")
        .Content<Media::Animation::TriggerAction>(
            "Actions",
            ContentKind::Collection,
            &AddPropertyChangedTriggerAction,
            &ClearPropertyChangedTriggerActions)
        .Factory();
    status = propertyChangedTrigger.Result();
    if (!status) return status.GetStatus();

    auto keyTrigger =
        Meta::Register<Media::Animation::KeyTrigger>(context);
    keyTrigger
        .Property(
            "Key",
            &Media::Animation::KeyTrigger::GetKey,
            &Media::Animation::KeyTrigger::SetKey)
        .Property(
            "ActiveOnFocus",
            &Media::Animation::KeyTrigger::GetActiveOnFocus,
            &Media::Animation::KeyTrigger::SetActiveOnFocus)
        .Content<Media::Animation::TriggerAction>(
            "Actions",
            ContentKind::Collection,
            &AddKeyTriggerAction,
            &ClearKeyTriggerActions)
        .Factory();
    status = keyTrigger.Result();
    if (!status) return status.GetStatus();

    auto invokeCommand =
        Meta::Register<Media::Animation::InvokeCommandAction>(context);
    invokeCommand
        .Property(
            "Command",
            &Media::Animation::InvokeCommandAction::GetCommand,
            &Media::Animation::InvokeCommandAction::SetCommand)
        .Property<
            Meta::PropertyValue,
            &Media::Animation::InvokeCommandAction::GetCommandParameter,
            &Media::Animation::InvokeCommandAction::SetCommandParameter>(
                "CommandParameter",
                PropertyFlags::AnyValue)
        .Factory();
    status = invokeCommand.Result();
    if (!status) return status.GetStatus();

    status =
        Meta::Register<Media::Animation::SelectAction>(context)
            .Factory()
            .Result();
    if (!status) return status.GetStatus();
    status =
        Meta::Register<Media::Animation::SelectAllAction>(context)
            .Factory()
            .Result();
    if (!status) return status.GetStatus();

    auto playSound =
        Meta::Register<Media::Animation::PlaySoundAction>(context);
    playSound
        .Property(
            "Source",
            &Media::Animation::PlaySoundAction::GetSource,
            &Media::Animation::PlaySoundAction::SetSource)
        .Property(
            "Volume",
            &Media::Animation::PlaySoundAction::GetVolume,
            &Media::Animation::PlaySoundAction::SetVolume)
        .Property(
            Media::Animation::PlaySoundAction::IsEnabledProperty,
            PropertyOptions(true))
        .Factory();
    status = playSound.Result();
    if (!status) return status.GetStatus();

    auto comparisonCondition = Meta::Register<Media::Animation::ComparisonCondition>(context);
    comparisonCondition
        .Property<
            Base::Ref<Data::Binding>,
            &Media::Animation::ComparisonCondition::GetLeftOperand,
            &Media::Animation::ComparisonCondition::SetLeftOperand>("LeftOperand")
        .Property<
            Meta::PropertyValue,
            &Media::Animation::ComparisonCondition::GetRightOperand,
            &Media::Animation::ComparisonCondition::SetRightOperand>(
                "RightOperand", PropertyFlags::AnyValue)
        .Property(
            "Operator",
            &Media::Animation::ComparisonCondition::GetComparisonOperator,
            &Media::Animation::ComparisonCondition::SetComparisonOperator)
        .Factory();
    status = comparisonCondition.Result();
    if (!status) return status.GetStatus();

    auto conditionalExpression = Meta::Register<Media::Animation::ConditionalExpression>(context);
    conditionalExpression
        .Property(
            "ForwardChaining",
            &Media::Animation::ConditionalExpression::GetChaining,
            &Media::Animation::ConditionalExpression::SetChaining)
        .Content<Media::Animation::ComparisonCondition>(
            "Conditions", ContentKind::Collection,
            &AddConditionalComparison, &ClearConditionalComparisons)
        .Factory();
    status = conditionalExpression.Result();
    if (!status) return status.GetStatus();

    auto conditionBehavior = Meta::Register<Media::Animation::ConditionBehavior>(context);
    conditionBehavior
        .Content<Media::Animation::ConditionalExpression>(
            "Expression", ContentKind::Single,
            &SetConditionBehaviorExpression,
            &ClearConditionBehaviorExpression)
        .Factory();
    status = conditionBehavior.Result();
    if (!status) return status.GetStatus();

    auto storyboardCompleted =
        Meta::Register<Media::Animation::StoryboardCompletedTrigger>(
            context);
    storyboardCompleted
        .Property(
            "Storyboard",
             &Media::Animation::StoryboardCompletedTrigger::
                GetStoryboard,
            &Media::Animation::StoryboardCompletedTrigger::
                SetStoryboard)
        .Content<Media::Animation::TriggerAction>(
            "Actions",
            ContentKind::Collection,
            &AddStoryboardCompletedTriggerAction,
            &ClearStoryboardCompletedTriggerActions)
        .Factory();
    status = storyboardCompleted.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Interactivity::Behavior>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto mouseDragBehavior =
        Meta::Register<Interactivity::MouseDragElementBehavior>(context);
    mouseDragBehavior
        .Property(
            Interactivity::MouseDragElementBehavior::XProperty,
            PropertyOptions(0.0)
                .Changed(&Interactivity::MouseDragElementBehavior::OnPositionChanged))
        .Property(
            Interactivity::MouseDragElementBehavior::YProperty,
            PropertyOptions(0.0)
                .Changed(&Interactivity::MouseDragElementBehavior::OnPositionChanged))
        .Property(
            Interactivity::MouseDragElementBehavior::ConstrainToParentBoundsProperty,
            PropertyOptions(false))
        .Factory();
    status = mouseDragBehavior.Result();
    if (!status) return status.GetStatus();

    auto backgroundEffectBehavior =
        Meta::Register<Interactivity::BackgroundEffectBehavior>(context);
    backgroundEffectBehavior
        .Property(
            Interactivity::BackgroundEffectBehavior::SourceProperty,
            PropertyOptions(Base::Ref<Base::Object>{})
                .Changed(&Interactivity::BackgroundEffectBehavior::OnBehaviorPropertyChanged))
        .Property(
            Interactivity::BackgroundEffectBehavior::EffectProperty,
            PropertyOptions(Base::Ref<Media::Effect>{})
                .Changed(&Interactivity::BackgroundEffectBehavior::OnBehaviorPropertyChanged))
        .Content<Media::Effect>(
            "Content", ContentKind::Single,
            &SetBackgroundEffectBehaviorEffect,
            &ClearBackgroundEffectBehaviorEffect)
        .Factory();
    status = backgroundEffectBehavior.Result();
    if (!status) return status.GetStatus();

    auto styleBehaviors =
        Meta::Register<Interactivity::StyleBehaviorCollection>(context);
    styleBehaviors
        .Content<Base::Object>(
            "Items", ContentKind::Collection,
            &AddStyleBehaviorItem,
            &ClearStyleBehaviorItems)
        .Factory();
    status = styleBehaviors.Result();
    if (!status) return status.GetStatus();

    auto styleTriggers =
        Meta::Register<Interactivity::StyleTriggerCollection>(context);
    styleTriggers
        .Content<Base::Object>(
            "Items", ContentKind::Collection,
            &AddStyleTriggerItem,
            &ClearStyleTriggerItems)
        .Factory();
    status = styleTriggers.Result();
    if (!status) return status.GetStatus();

    auto styleInteraction = Meta::Register<Interactivity::StyleInteraction>(
        context, TypeFlags::Abstract);
    styleInteraction
        .Property(
            Interactivity::StyleInteraction::BehaviorsProperty,
            PropertyOptions(Base::Ref<Interactivity::StyleBehaviorCollection>{})
                .Changed(&Interactivity::StyleInteraction::OnBehaviorsChanged))
        .Property(
            Interactivity::StyleInteraction::TriggersProperty,
            PropertyOptions(Base::Ref<Interactivity::StyleTriggerCollection>{})
                .Changed(&Interactivity::StyleInteraction::OnTriggersChanged));
    status = styleInteraction.Result();
    if (!status) return status.GetStatus();

    auto interaction = Meta::Register<Media::Animation::Interaction>(
        context, TypeFlags::Abstract);
    interaction.Collection<Base::Object>(
        "Triggers",
        &AddInteractionTrigger,
        &ClearInteractionTriggers,
        PropertyFlags::Attached |
            PropertyFlags::Structural)
        .Collection<Base::Object>(
            "Behaviors",
            &AddInteractionBehavior,
            &ClearInteractionBehaviors,
            PropertyFlags::Attached |
                PropertyFlags::Structural);
    status = interaction.Result();
    if (!status) return status.GetStatus();
    return {};
}
