// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiElements(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    status = Meta::Register<Visual>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<ContentElement>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto frameworkContentElement = Meta::Register<FrameworkContentElement>(
        context, TypeFlags::Abstract);
    frameworkContentElement
        .Property<
            Base::Ref<ResourceDictionary>,
            &FrameworkContentElement::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Property(
            FrameworkContentElement::DataContextProperty,
            PropertyOptions(Value::NullObject(
                TypeOf<Base::Object>())).Inherits())
        .Property(
            FrameworkContentElement::StyleProperty,
            PropertyOptions(Base::Ref<Style>{}))
        .Property(
            FrameworkContentElement::TagProperty,
            PropertyOptions(Meta::Value::NullObject(
                Meta::TypeOf<Base::Object>())));
    status = frameworkContentElement.Result();
    if (!status) return status.GetStatus();

    auto uiElement = Meta::Register<UIElement>(
        context, TypeFlags::Abstract);
    uiElement
        .Event(UIElement::PreviewMouseMoveEvent, RoutingStrategy::Tunnel)
        .Event(UIElement::MouseMoveEvent)
        .Event(UIElement::PreviewMouseDownEvent, RoutingStrategy::Tunnel)
        .Event(UIElement::MouseDownEvent)
        .Event(UIElement::PreviewMouseUpEvent, RoutingStrategy::Tunnel)
        .Event(UIElement::MouseUpEvent)
        .Event(UIElement::PreviewMouseWheelEvent, RoutingStrategy::Tunnel)
        .Event(UIElement::MouseWheelEvent)
        .Event(UIElement::GotKeyboardFocusEvent)
        .Event(UIElement::LostKeyboardFocusEvent)
        .Event(UIElement::PreviewKeyDownEvent, RoutingStrategy::Tunnel)
        .Event(UIElement::KeyDownEvent)
        .Event(UIElement::PreviewKeyUpEvent, RoutingStrategy::Tunnel)
        .Event(UIElement::KeyUpEvent)
        .Event(UIElement::PreviewTextInputEvent, RoutingStrategy::Tunnel)
        .Event(UIElement::TextInputEvent)
        .Property(
            UIElement::ClipToBoundsProperty,
            PropertyOptions(false)
                .AffectsArrange()
                .Changed(&OnRenderStateChanged))
        .Property(
            UIElement::BlendModeProperty,
            PropertyOptions(BlendMode::Normal)
                .Changed(&OnRenderStateChanged))
        .Property(
            UIElement::EffectProperty,
            PropertyOptions(Base::Ref<Effect>{})
                .AffectsRender()
                .Changed(&OnEffectChanged))
        .Property(
            UIElement::OpacityMaskProperty,
            PropertyOptions(Base::Ref<Brush>{})
                .AffectsRender()
                .Changed(&OnOpacityMaskChanged))
        .Property(
            UIElement::IsHitTestVisibleProperty,
            PropertyOptions(true))
        .Property(
            UIElement::VisibilityProperty,
            PropertyOptions(Visibility::Visible)
                .AffectsMeasure()
                .Changed(&OnRenderStateChanged))
        .Property(
            UIElement::IsEnabledProperty,
            PropertyOptions(true)
                .Inherits()
                .AffectsRender())
        .Property(
            UIElement::AllowDropProperty,
            PropertyOptions(false))
        .Property(
            UIElement::IsMouseOverProperty,
            PropertyOptions(false).AffectsRender())
        .Property(
            UIElement::IsPressedProperty,
            PropertyOptions(false).AffectsRender())
        .Property(
            UIElement::IsKeyboardFocusedProperty,
            PropertyOptions(false).AffectsRender())
        .Property(
            UIElement::IsKeyboardFocusWithinProperty,
            PropertyOptions(false).AffectsRender())
        .Property(
            UIElement::FocusableProperty,
            PropertyOptions(false))
        .Property(
            UIElement::IsTabStopProperty,
            PropertyOptions(false))
        .Property(
            UIElement::TabIndexProperty,
            PropertyOptions(std::uint32_t{0}))
        .Property(
            UIElement::IsFocusScopeProperty,
            PropertyOptions(false))
        .Property(
            UIElement::OpacityProperty,
            PropertyOptions(1.0)
                .Changed(&OnRenderStateChanged)
                .Validate(&ValidateUnitDouble))
        .Property(
            UIElement::RenderTransformProperty,
            PropertyOptions(Base::Ref<Transform>{})
                .AffectsRender()
                .Changed(&OnRenderTransformChanged))
        .Property(
            UIElement::RenderTransformOriginProperty,
            PropertyOptions(Point{})
                .Changed(&OnRenderStateChanged));
    status = uiElement.Result();
    if (!status) return status.GetStatus();

    auto frameworkElement = Meta::Register<FrameworkElement>(context);
    frameworkElement
        .Property<
            Base::Ref<ResourceDictionary>,
            &FrameworkElement::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Property(
            FrameworkElement::DataContextProperty,
            PropertyOptions(Value::NullObject(
                TypeOf<Base::Object>()))
                .Inherits())
        .Property(
            FrameworkElement::FontFamilyProperty,
            PropertyOptions(Base::Ref<Media::FontFamily>{})
                .Inherits()
                .AffectsMeasure())
        .Property(
            FrameworkElement::FlowDirectionProperty,
            PropertyOptions(FlowDirection::LeftToRight)
                .Inherits()
                .AffectsMeasure())
        .Property(
            FrameworkElement::CursorProperty,
            PropertyOptions(Base::String{}).Inherits())
        .Property(
            FrameworkElement::ForceCursorProperty,
            PropertyOptions(false))
        .Property(
            FrameworkElement::InputScopeProperty,
            PropertyOptions(InputScope::Default))
        .Property(
            FrameworkElementForegroundProperty,
            PropertyOptions(Base::Ref<Brush>{})
                .Inherits()
                .AffectsRender())
        .Property(
            FrameworkElement::StyleProperty,
            PropertyOptions(Base::Ref<Style>{}))
        .Property(
            FrameworkElement::TagProperty,
            PropertyOptions(Meta::Value::NullObject(
                Meta::TypeOf<Base::Object>())) )
        .Property(
            FrameworkElement::ToolTipProperty,
            PropertyOptions(Meta::Value::NullObject(
                Meta::TypeOf<Base::Object>())))
        .Property(
            FrameworkElement::WidthProperty,
            PropertyOptions(Length::Auto())
                .AffectsMeasure()
                .Validate(&ValidateLength))
        .Property(
            FrameworkElement::HeightProperty,
            PropertyOptions(Length::Auto())
                .AffectsMeasure()
                .Validate(&ValidateLength))
        .Property(
            FrameworkElement::ActualWidthProperty,
            PropertyOptions(0.0))
        .Property(
            FrameworkElement::ActualHeightProperty,
            PropertyOptions(0.0))
        .Property(
            FrameworkElement::MinWidthProperty,
            PropertyOptions(0.0)
                .AffectsMeasure()
                .Validate(&::Aero::Base::Detail::Validate::NonNegative<double>)
                .Coerce(&CoerceMinWidth))
        .Property(
            FrameworkElement::MaxWidthProperty,
            PropertyOptions(DefaultMaximum)
                .AffectsMeasure()
                .Validate(&::Aero::Base::Detail::Validate::NonNegative<double>)
                .Coerce(&CoerceMaxWidth))
        .Property(
            FrameworkElement::MinHeightProperty,
            PropertyOptions(0.0)
                .AffectsMeasure()
                .Validate(&::Aero::Base::Detail::Validate::NonNegative<double>)
                .Coerce(&CoerceMinHeight))
        .Property(
            FrameworkElement::MaxHeightProperty,
            PropertyOptions(DefaultMaximum)
                .AffectsMeasure()
                .Validate(&::Aero::Base::Detail::Validate::NonNegative<double>)
                .Coerce(&CoerceMaxHeight))
        .Property(
            FrameworkElement::MarginProperty,
            PropertyOptions(Thickness{})
                .AffectsMeasure()
                .Validate(&ValidateMarginValue))
        .Property(
            FrameworkElement::HorizontalAlignmentProperty,
            PropertyOptions(HorizontalAlignment::Stretch)
                .AffectsArrange())
        .Property(
            FrameworkElement::VerticalAlignmentProperty,
            PropertyOptions(VerticalAlignment::Stretch)
                .AffectsArrange())
        .Property(
            FrameworkElement::UseLayoutRoundingProperty,
            PropertyOptions(false).AffectsMeasure())
        .Property(
            FrameworkElement::LayoutTransformProperty,
            PropertyOptions(Base::Ref<Transform>{})
                .AffectsMeasure()
                .Changed(&OnLayoutTransformChanged))
        .Collection<Media::Animation::EventTrigger>(
            "Triggers",
            &AddFrameworkEventTrigger,
            &ClearFrameworkEventTriggers)
        .Factory(&CreateFrameworkElementPlaceholder);
    status = frameworkElement.Result();
    if (!status) return status.GetStatus();
    return {};
}
