// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiInput(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    status = Meta::Register<EventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<RoutedEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<InputEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<MouseEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<MouseButtonEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<MouseWheelEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<KeyEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<TextCompositionEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<KeyboardFocusChangedEventArgs>(
        context).Result();
    if (!status) return status.GetStatus();
    auto keyboardNavigation =
        Meta::Register<KeyboardNavigation>(
            context, TypeFlags::Abstract);
    keyboardNavigation.Property(
        KeyboardNavigation::
            DirectionalNavigationProperty,
        PropertyOptions(
            KeyboardNavigationMode::Continue));
    keyboardNavigation.Property(
        KeyboardNavigation::TabNavigationProperty,
        PropertyOptions(
            KeyboardNavigationMode::Continue));
    keyboardNavigation.Property(
        KeyboardNavigation::TabIndexProperty,
        PropertyOptions(std::uint32_t{0}));
    status = keyboardNavigation.Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<CanExecuteRoutedEventArgs>(
        context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<ExecutedRoutedEventArgs>(
        context).Result();
    if (!status) return status.GetStatus();
    return {};
}
