// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiInput(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    status = Meta::Describe<EventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<RoutedEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<InputEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<MouseEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<MouseButtonEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<MouseWheelEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<KeyEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<TextCompositionEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<KeyboardFocusChangedEventArgs>(
        context).Result();
    if (!status) return status.GetStatus();
    auto keyboardNavigationMode =
        Meta::Describe<KeyboardNavigationMode>(context);
    keyboardNavigationMode
        .Value(
            "Continue",
            KeyboardNavigationMode::Continue)
        .Value(
            "Once",
            KeyboardNavigationMode::Once)
        .Value(
            "Cycle",
            KeyboardNavigationMode::Cycle)
        .Value(
            "None",
            KeyboardNavigationMode::None)
        .Value(
            "Contained",
            KeyboardNavigationMode::Contained)
        .Value(
            "Local",
            KeyboardNavigationMode::Local);
    status = keyboardNavigationMode.Result();
    if (!status) return status.GetStatus();
    auto keyboardNavigation =
        Meta::Describe<KeyboardNavigation>(
            context, TypeFlags::Abstract);
    keyboardNavigation.Property(
        KeyboardNavigation::
            DirectionalNavigationProperty,
        PropertyOptions(
            KeyboardNavigationMode::Continue));
    keyboardNavigation.Property(
        KeyboardNavigation::TabNavigationProperty,
        PropertyOptions(
            KeyboardNavigationMode::Continue));
    keyboardNavigation.Property(
        KeyboardNavigation::TabIndexProperty,
        PropertyOptions(std::uint32_t{0}));
    status = keyboardNavigation.Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<CanExecuteRoutedEventArgs>(
        context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<ExecutedRoutedEventArgs>(
        context).Result();
    if (!status) return status.GetStatus();
    return {};
}
