// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiMedia(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    auto length = Meta::Register<Length>(context);
    length
        .ValueSemantics({sizeof(Length), alignof(Length), nullptr, nullptr,
            &EqualLength, nullptr, true})
        .TextConverter<&ConvertLength>();
    status = length.Result();
    if (!status) return status.GetStatus();

    auto thickness = Meta::Register<Thickness>(context);
    thickness
        .Field<&Thickness::left>("Left")
        .Field<&Thickness::top>("Top")
        .Field<&Thickness::right>("Right")
        .Field<&Thickness::bottom>("Bottom")
        .ValueSemantics({sizeof(Thickness), alignof(Thickness), nullptr,
            nullptr, &EqualThickness, nullptr, true})
        .TextConverter<&ConvertThickness>();
    status = thickness.Result();
    if (!status) return status.GetStatus();

    auto cornerRadius = Meta::Register<CornerRadius>(context);
    cornerRadius
        .Field<&CornerRadius::topLeft>("TopLeft")
        .Field<&CornerRadius::topRight>("TopRight")
        .Field<&CornerRadius::bottomRight>("BottomRight")
        .Field<&CornerRadius::bottomLeft>("BottomLeft")
        .ValueSemantics({
            sizeof(CornerRadius),
            alignof(CornerRadius),
            nullptr,
            nullptr,
            &EqualCornerRadius,
            nullptr,
            true})
        .TextConverter<&ConvertCornerRadius>();
    status = cornerRadius.Result();
    if (!status) return status.GetStatus();

    auto color = Meta::Register<Color>(context);
    color
        .Field<&Color::red>("Red")
        .Field<&Color::green>("Green")
        .Field<&Color::blue>("Blue")
        .Field<&Color::alpha>("Alpha")
        .ValueSemantics({sizeof(Color), alignof(Color), nullptr, nullptr,
            &EqualColor, nullptr, true})
        .TextConverter<&ConvertColor>();
    status = color.Result();
    if (!status) return status.GetStatus();

    auto point = Meta::Register<Point>(context);
    point
        .Field<&Point::x>("X")
        .Field<&Point::y>("Y")
        .ValueSemantics()
        .TextConverter<&ConvertPoint>();
    status = point.Result();
    if (!status) return status.GetStatus();

    auto rect = Meta::Register<Rect>(context);
    rect
        .Field<&Rect::x>("X")
        .Field<&Rect::y>("Y")
        .Field<&Rect::width>("Width")
        .Field<&Rect::height>("Height")
        .ValueSemantics()
        .TextConverter<&ConvertRect>();
    status = rect.Result();
    if (!status) return status.GetStatus();

    // Brush.RelativeTransform is a Transform-valued dependency property, so
    // the abstract value type must exist before Brush metadata is authored.
    status = Meta::Register<Transform>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto brush = Meta::Register<Brush>(
        context, TypeFlags::Abstract);
    brush
        .Property(
            Brush::OpacityProperty,
            PropertyOptions(1.0)
                .Validate(&ValidateUnitDouble))
        .Property(
            Brush::ShaderProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            Brush::RelativeTransformProperty,
            PropertyOptions(Base::Ref<Transform>{}))
        .TextConverter(&ConvertBrushText);
    status = brush.Result();
    if (!status) return status.GetStatus();

    auto solidBrush =
        Meta::Register<SolidColorBrush>(context);
    solidBrush
        .Property(
            SolidColorBrush::ColorProperty,
            PropertyOptions(Color{}))
        .Factory();
    status = solidBrush.Result();
    if (!status) return status.GetStatus();

    auto gradientStop =
        Meta::Register<GradientStop>(context);
    gradientStop
        .Property(
            GradientStop::OffsetProperty,
            PropertyOptions(0.0)
                .Validate(&ValidateUnitDouble))
        .Property(
            GradientStop::ColorProperty,
            PropertyOptions(Color{}))
        .Factory();
    status = gradientStop.Result();
    if (!status) return status.GetStatus();

    auto gradientStopCollection =
        Meta::Register<GradientStopCollection>(context);
    gradientStopCollection
        .Content<GradientStop>(
            "Items", ContentKind::Collection,
            &AddGradientStopCollectionItem,
            &ClearGradientStopCollectionItems)
        .Factory();
    status = gradientStopCollection.Result();
    if (!status) return status.GetStatus();

    auto brushShader = Meta::Register<BrushShader>(
        context, TypeFlags::Abstract);
    brushShader.Factory();
    status = brushShader.Result();
    if (!status) return status.GetStatus();

    auto monochromeBrush = Meta::Register<MonochromeShader>(context);
    monochromeBrush
        .Property(
            MonochromeShader::ColorProperty,
            PropertyOptions(Color{}).AffectsRender())
        .Factory();
    status = monochromeBrush.Result();
    if (!status) return status.GetStatus();

    auto conicGradientBrush = Meta::Register<ConicGradientShader>(context);
    conicGradientBrush
        .Content<GradientStop>(
            "GradientStops", ContentKind::Collection,
            [](Base::Object& owner, const Base::Ref<Base::Object>& value, void*) noexcept {
                static_cast<ConicGradientShader&>(owner).AddGradientStop(
                    Base::Ref<GradientStop>::FromBorrowed(
                        static_cast<GradientStop&>(*value)));
            },
            [](Base::Object& owner, void*) noexcept {
                static_cast<ConicGradientShader&>(owner).ClearGradientStops();
            })
        .Factory();
    status = conicGradientBrush.Result();
    if (!status) return status.GetStatus();

    auto wavesBrush = Meta::Register<WavesShader>(context);
    wavesBrush
        .Property(
            WavesShader::TimeProperty,
            PropertyOptions(0.0).AffectsRender())
        .Factory();
    status = wavesBrush.Result();
    if (!status) return status.GetStatus();

    auto gradientBrush = Meta::Register<GradientBrush>(
        context, TypeFlags::Abstract);
    gradientBrush
        .Property(
            GradientBrush::MappingModeProperty,
            PropertyOptions(
                BrushMappingMode::RelativeToBoundingBox))
        .Content<GradientStop>(
            "GradientStops",
            ContentKind::Collection,
            &AddGradientStop,
            &ClearGradientStops);
    status = gradientBrush.Result();
    if (!status) return status.GetStatus();

    auto linearBrush =
        Meta::Register<LinearGradientBrush>(context);
    linearBrush
        .Property(
            LinearGradientBrush::StartPointProperty,
            PropertyOptions(Point{0.0, 0.0}))
        .Property(
            LinearGradientBrush::EndPointProperty,
            PropertyOptions(Point{1.0, 1.0}))
        .Factory();
    status = linearBrush.Result();
    if (!status) return status.GetStatus();

    auto radialBrush =
        Meta::Register<RadialGradientBrush>(context);
    radialBrush
        .Property(
            RadialGradientBrush::CenterProperty,
            PropertyOptions(Point{0.5, 0.5}))
        .Property(
            RadialGradientBrush::GradientOriginProperty,
            PropertyOptions(Point{0.5, 0.5}))
        .Property(
            RadialGradientBrush::RadiusXProperty,
            PropertyOptions(0.5)
                .Validate(&::Aero::Base::Detail::Validate::Positive<double>))
        .Property(
            RadialGradientBrush::RadiusYProperty,
            PropertyOptions(0.5)
                .Validate(&::Aero::Base::Detail::Validate::Positive<double>))
        .Factory();
    status = radialBrush.Result();
    if (!status) return status.GetStatus();

    auto imageSource = Meta::Register<ImageSource>(
        context, TypeFlags::Abstract);
    imageSource.TextConverter(
        &ConvertImageSourceText);
    status = imageSource.Result();
    if (!status) return status.GetStatus();

    auto bitmapImage =
        Meta::Register<BitmapImage>(context);
    bitmapImage
        .Property(
            BitmapImage::UriSourceProperty,
            PropertyOptions(
                Base::ResourceUri{}))
        .Factory();
    status = bitmapImage.Result();
    if (!status) return status.GetStatus();

    auto imageBrush =
        Meta::Register<ImageBrush>(context);
    imageBrush
        .Property(
            ImageBrush::ImageSourceProperty,
            PropertyOptions(
                Base::Ref<ImageSource>{}))
        .Property(
            ImageBrush::StretchProperty,
            PropertyOptions(Stretch::Fill))
        .Property(
            ImageBrush::ViewboxProperty,
            PropertyOptions(
                Rect{0.0, 0.0, 1.0, 1.0}))
        .Property(
            ImageBrush::ViewportProperty,
            PropertyOptions(
                Rect{0.0, 0.0, 1.0, 1.0}))
        .Property(
            ImageBrush::ViewboxUnitsProperty,
            PropertyOptions(
                BrushMappingMode::RelativeToBoundingBox))
        .Property(
            ImageBrush::ViewportUnitsProperty,
            PropertyOptions(
                BrushMappingMode::RelativeToBoundingBox))
        .Property(
            ImageBrush::TileModeProperty,
            PropertyOptions(TileMode::None))
        .Property(
            ImageBrush::AlignmentXProperty,
            PropertyOptions(HorizontalAlignment::Center))
        .Property(
            ImageBrush::AlignmentYProperty,
            PropertyOptions(VerticalAlignment::Center))
        .Factory();
    status = imageBrush.Result();
    if (!status) return status.GetStatus();

    auto matrix = Meta::Register<Base::Transform2D>(context);
    matrix
        .Field<&Base::Transform2D::m11>("M11")
        .Field<&Base::Transform2D::m12>("M12")
        .Field<&Base::Transform2D::m21>("M21")
        .Field<&Base::Transform2D::m22>("M22")
        .Field<&Base::Transform2D::dx>("OffsetX")
        .Field<&Base::Transform2D::dy>("OffsetY")
        .ValueSemantics()
        .TextConverter<&ConvertMatrix>();
    status = matrix.Result();
    if (!status) return status.GetStatus();

    auto translate = Meta::Register<TranslateTransform>(context);
    translate
        .Property(
            TranslateTransform::XProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            TranslateTransform::YProperty,
            PropertyOptions(0.0).AffectsRender())
        .Factory();
    status = translate.Result();
    if (!status) return status.GetStatus();

    auto scale = Meta::Register<ScaleTransform>(context);
    scale
        .Property(
            ScaleTransform::ScaleXProperty,
            PropertyOptions(1.0).AffectsRender())
        .Property(
            ScaleTransform::ScaleYProperty,
            PropertyOptions(1.0).AffectsRender())
        .Property(
            ScaleTransform::CenterXProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            ScaleTransform::CenterYProperty,
            PropertyOptions(0.0).AffectsRender())
        .Factory();
    status = scale.Result();
    if (!status) return status.GetStatus();

    auto rotate = Meta::Register<RotateTransform>(context);
    rotate
        .Property(
            RotateTransform::AngleProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            RotateTransform::CenterXProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            RotateTransform::CenterYProperty,
            PropertyOptions(0.0).AffectsRender())
        .Factory();
    status = rotate.Result();
    if (!status) return status.GetStatus();

    auto skew = Meta::Register<SkewTransform>(context);
    skew
        .Property(
            SkewTransform::AngleXProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            SkewTransform::AngleYProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            SkewTransform::CenterXProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            SkewTransform::CenterYProperty,
            PropertyOptions(0.0).AffectsRender())
        .Factory();
    status = skew.Result();
    if (!status) return status.GetStatus();

    auto matrixTransform = Meta::Register<MatrixTransform>(context);
    matrixTransform
        .Property(
            MatrixTransform::MatrixProperty,
            PropertyOptions(Base::Transform2D{}).AffectsRender())
        .Factory();
    status = matrixTransform.Result();
    if (!status) return status.GetStatus();

    auto transformGroup = Meta::Register<TransformGroup>(context);
    transformGroup
        .Content<Transform>(
            "Children",
            ContentKind::Collection,
            &AddTransformGroupChild,
            &ClearTransformGroupChildren)
        .Factory();
    status = transformGroup.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Effect>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto blurEffect = Meta::Register<BlurEffect>(context);
    blurEffect
        .Property(
            BlurEffect::RadiusProperty,
            PropertyOptions(5.0)
                .AffectsRender()
                .Validate(&::Aero::Base::Detail::Validate::NonNegative<double>))
        .Factory();
    status = blurEffect.Result();
    if (!status) return status.GetStatus();

    auto dropShadowEffect =
        Meta::Register<DropShadowEffect>(context);
    dropShadowEffect
        .Property(
            DropShadowEffect::BlurRadiusProperty,
            PropertyOptions(5.0)
                .AffectsRender()
                .Validate(&::Aero::Base::Detail::Validate::NonNegative<double>))
        .Property(
            DropShadowEffect::DirectionProperty,
            PropertyOptions(315.0)
                .AffectsRender())
        .Property(
            DropShadowEffect::ShadowDepthProperty,
            PropertyOptions(5.0)
                .AffectsRender()
                .Validate(&::Aero::Base::Detail::Validate::NonNegative<double>))
        .Property(
            DropShadowEffect::OpacityProperty,
            PropertyOptions(1.0)
                .AffectsRender()
                .Validate(&ValidateUnitDouble))
        .Property(
            DropShadowEffect::ColorProperty,
            PropertyOptions(
                Base::Color{
                    0.0F, 0.0F, 0.0F, 1.0F})
                .AffectsRender())
        .Factory();
    status = dropShadowEffect.Result();
    if (!status) return status.GetStatus();

    auto pixelateEffect = Meta::Register<PixelateEffect>(context);
    pixelateEffect
        .Property(
            PixelateEffect::SizeProperty,
            PropertyOptions(1.0)
                .AffectsRender()
                .Validate(&::Aero::Base::Detail::Validate::Positive<double>))
        .Factory();
    status = pixelateEffect.Result();
    if (!status) return status.GetStatus();

    auto visualBrush = Meta::Register<VisualBrush>(context);
    visualBrush
        .Property(
            VisualBrush::VisualProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            VisualBrush::StretchProperty,
            PropertyOptions(Stretch::Fill))
        .Property(
            VisualBrush::ViewboxProperty,
            PropertyOptions(Rect{0.0, 0.0, 1.0, 1.0}))
        .Property(
            VisualBrush::AlignmentYProperty,
            PropertyOptions(VerticalAlignment::Center))
        .Factory();
    status = visualBrush.Result();
    if (!status) return status.GetStatus();

    auto command = Meta::Register<ICommand>(
        context, TypeFlags::Abstract);
    command.TextConverter(
        &ConvertRoutedCommandReference);
    status = command.Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<InputGesture>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<KeyGesture>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<RoutedCommand>(context).Result();
    if (!status) return status.GetStatus();
    return {};
}
