// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiStyling(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    auto element = Meta::Register<Element>(context, TypeFlags::Abstract);
    element
        .Property(
            Element::PPAAOutProperty,
            PropertyOptions(0.0).AffectsRender())
        .Property(
            Element::PPAAModeProperty,
            PropertyOptions(Base::String{}).AffectsRender())
        .Property(
            Element::IsFocusEngagedProperty,
            PropertyOptions(false).AffectsRender());
    status = element.Result();
    if (!status) return status.GetStatus();

    auto text = Meta::Register<TextProperties>(context, TypeFlags::Abstract);
    text.Property(
        TextProperties::PasswordLengthProperty,
        PropertyOptions(std::uint32_t{0}).AffectsRender());
    status = text.Result();
    if (!status) return status.GetStatus();

    auto richText = Meta::Register<RichText>(context, TypeFlags::Abstract);
    richText.Property(
        RichText::TextProperty,
        PropertyOptions(Base::String{}).AffectsMeasure().Changed(
            &RichText::OnTextChanged));
    status = richText.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<SetterBase>(context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto setter = Meta::Register<Setter>(context);
    setter
        .Property(
            "TargetName",
            &Setter::GetTargetName,
            &Setter::SetTargetName)
        .Property(
            "Property",
            &Setter::GetPropertyName,
            &Setter::SetPropertyName)
        .Property<
            Value,
            &Setter::GetAuthoredValue,
            &Setter::SetAuthoredValue>(
            "Value",
            PropertyFlags::AnyValue)
        .Factory();
    status = setter.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Data::IValueConverter>(context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Data::BindingBase>(context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Data::RelativeSource>(context).Factory().Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Data::Binding>(context, TypeFlags::MarkupExtension | TypeFlags::Sealed).Factory().Result();
    if (!status) return status.GetStatus();

    auto triggerBase = Meta::Register<TriggerBase>(
        context, TypeFlags::Abstract);
    triggerBase
        .Collection<Media::Animation::TriggerAction>(
            "EnterActions",
            &AddTriggerEnterAction,
            &ClearTriggerEnterActions)
        .Collection<Media::Animation::TriggerAction>(
            "ExitActions",
            &AddTriggerExitAction,
            &ClearTriggerExitActions);
    status = triggerBase.Result();
    if (!status) return status.GetStatus();

    auto trigger = Meta::Register<Trigger>(context);
    trigger
        .Property(
            "Property",
            &Trigger::GetPropertyName,
            &Trigger::SetPropertyName)
        .Property(
            "SourceName",
            &Trigger::GetSourceName,
            &Trigger::SetSourceName)
        .Property<
            Value,
            &Trigger::GetAuthoredValue,
            &Trigger::SetAuthoredValue>(
            "Value",
            PropertyFlags::AnyValue)
        .Content<Setter>(
            "Setters",
            ContentKind::Collection,
            &AddTriggerSetter,
            &ClearTriggerSetters)
        .Factory();
    status = trigger.Result();
    if (!status) return status.GetStatus();

    auto dataTrigger = Meta::Register<DataTrigger>(context);
    dataTrigger
        .Property<
            Base::Ref<Data::Binding>,
            &DataTrigger::SetBinding>(
                "Binding",
                PropertyFlags::Structural)
        .Property<
            Value,
            &DataTrigger::GetAuthoredValue,
            &DataTrigger::SetAuthoredValue>(
                "Value",
                PropertyFlags::AnyValue)
        .Property(
            "Comparison",
            &DataTrigger::GetComparison,
            &DataTrigger::SetComparison)
        .Content<Setter>(
            "Setters",
            ContentKind::Collection,
            &AddDataTriggerSetter,
            &ClearDataTriggerSetters)
        .Factory();
    status = dataTrigger.Result();
    if (!status) return status.GetStatus();

    auto condition = Meta::Register<Condition>(context);
    condition
        .Property<
            Base::Ref<Data::Binding>,
            &Condition::SetBinding>(
                "Binding",
                PropertyFlags::Structural)
        .Property(
            "Property",
            &Condition::GetPropertyName,
            &Condition::SetPropertyName)
        .Property(
            "SourceName",
            &Condition::GetSourceName,
            &Condition::SetSourceName)
        .Property<
            Value,
            &Condition::GetAuthoredValue,
            &Condition::SetAuthoredValue>(
                "Value",
                PropertyFlags::AnyValue)
        .Factory();
    status = condition.Result();
    if (!status) return status.GetStatus();

    auto multiDataTrigger =
        Meta::Register<MultiDataTrigger>(context);
    multiDataTrigger
        .Collection<Condition>(
            "Conditions",
            &AddMultiDataCondition,
            &ClearMultiDataConditions)
        .Content<Setter>(
            "Setters",
            ContentKind::Collection,
            &AddMultiDataSetter,
            &ClearMultiDataSetters)
        .Factory();
    status = multiDataTrigger.Result();
    if (!status) return status.GetStatus();

    auto multiTrigger = Meta::Register<MultiTrigger>(context);
    multiTrigger
        .Collection<Condition>(
            "Conditions",
            &AddMultiTriggerCondition,
            &ClearMultiTriggerConditions)
        .Content<Setter>(
            "Setters",
            ContentKind::Collection,
            &AddMultiTriggerSetter,
            &ClearMultiTriggerSetters)
        .Factory();
    status = multiTrigger.Result();
    if (!status) return status.GetStatus();

    auto style = Meta::Register<Style>(context);
    style
        .Property<
            TypeReference,
            &GetStyleTargetType,
            &SetStyleTargetType>(
            "TargetType",
            PropertyFlags::None)
        .Property<
            Base::Ref<Style>,
            &SetStyleBasedOn>(
            "BasedOn",
            PropertyFlags::WriteOnly)
        .Property<
            Base::Ref<ResourceDictionary>,
            &Style::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Collection<Trigger>(
            "Triggers",
            &AddStyleTrigger,
            &ClearStyleTriggers)
        .Content<Setter>(
            "Setters",
            ContentKind::Collection,
            &AddStyleSetter,
            &ClearStyleSetters)
        .Factory();
    status = style.Result();
    if (!status) return status.GetStatus();
    return {};
}
