// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulatePresentationResources(
    Core::MetadataContext& context) noexcept {
    Base::Result<void> status;
    auto resourceDictionary =
        Describe<ResourceDictionary>(context);
    resourceDictionary
        .Property<
            Base::ResourceUri,
            &ResourceDictionary::Source,
            &ResourceDictionary::SetSource>(
            "Source",
            PropertyFlags::None)
        .Collection<ResourceDictionary>(
            "MergedDictionaries",
            &AddMergedDictionary,
            &ClearMergedDictionaries)
        .Content<Base::Object>(
            "Entries",
            ContentKind::Collection)
        .Factory();
    status = resourceDictionary.Result();
    if (!status) return status.GetStatus();

    auto geometry = Describe<Geometry>(context);
    geometry
        .Property(
            "Value", &Geometry::Value, &Geometry::SetValue,
            PropertyFlags::Structural)
        .Content(MakeMemberId(
            Geometry::StaticTypeId(), MemberKind::Property, "Value"))
        .TextConverter(&ConvertGeometryText)
        .Factory();
    status = geometry.Result();
    if (!status) return status.GetStatus();

    auto fontFamily = Describe<FontFamily>(context);
    fontFamily
        .Property(
            "Source", &FontFamily::Source, &FontFamily::SetSource,
            PropertyFlags::Structural)
        .Content(MakeMemberId(
            FontFamily::StaticTypeId(), MemberKind::Property, "Source"))
        .TextConverter(&ConvertFontFamilyText)
        .Factory();
    status = fontFamily.Result();
    if (!status) return status.GetStatus();
    return {};
}
