// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsItems(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    status = Meta::Describe<ItemContainer>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<ObjectItemsSource>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto alternationConverter =
        Meta::Describe<AlternationConverter>(context);
    alternationConverter
        .Content<Base::Object>(
            "Values", ContentKind::Collection,
            [](Base::Object& owner,
               const Base::Ref<Base::Object>& value,
               void*) noexcept {
                return static_cast<AlternationConverter&>(owner)
                    .AddValue(value);
            },
            [](Base::Object& owner, void*) noexcept {
                static_cast<AlternationConverter&>(owner)
                    .ClearValues();
                return Base::Result<void>{};
            })
        .Factory();
    status = alternationConverter.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<BoxedItemValue>(context)
        .Result();
    if (!status) return status.GetStatus();

    auto itemsControl = Meta::Describe<ItemsControl>(context);
    itemsControl
        .Property(
            ItemsControl::ItemCountProperty,
            PropertyOptions(std::uint32_t{0}))
        .Property(
            ItemsControl::HasItemsProperty,
            PropertyOptions(false))
        .Property(
            ItemsControl::ItemsSourceProperty,
            PropertyOptions(
                Base::Ref<Base::Object>{})
                .AffectsMeasure()
                .Changed(&OnItemsSourceChanged))
        .Property(
            ItemsControl::AlternationCountProperty,
            PropertyOptions(std::uint32_t{0})
                .AffectsMeasure())
        .Property(
            ItemsControl::ItemTemplateProperty,
            PropertyOptions(
                Base::Ref<DataTemplate>{})
                .AffectsMeasure()
                .Changed(&OnItemTemplateChanged))
        .Property(
            ItemsControl::ItemsPanelProperty,
            PropertyOptions(
                Base::Ref<ItemsPanelTemplate>{})
                .AffectsMeasure()
                .Changed(&OnItemsPanelChanged))
        .Property(
            ItemsControl::ItemContainerStyleProperty,
            PropertyOptions(Base::Ref<Style>{})
                .AffectsMeasure()
                .Changed(
                    &OnItemContainerStyleChanged))
        .Content<Base::Object>(
            "Items", ContentKind::Collection,
            &AddItemsControlItem, &ClearItemsControlItems)
        .Factory();
    status = itemsControl.Result();
    if (!status) return status.GetStatus();

    auto headeredItemsControl = Meta::Describe<HeaderedItemsControl>(
        context, TypeFlags::Abstract);
    headeredItemsControl
        .Property(
            HeaderedItemsControl::HeaderProperty,
            PropertyOptions(Base::String{}).AffectsMeasure())
        .Property(
            HeaderedItemsControl::HeaderTemplateProperty,
            PropertyOptions(Base::Ref<DataTemplate>{}).AffectsMeasure());
    status = headeredItemsControl.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<ItemsPresenter>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto selector = Meta::Describe<Selector>(
        context, TypeFlags::Abstract);
    selector
        .Event(
            Selector::
                SelectionChangedRoutedEvent)
        .Property(
            Selector::SelectionModeProperty,
            PropertyOptions(SelectionMode::Single))
        .Property(
            Selector::SelectedIndexProperty,
            PropertyOptions(UINT32_MAX)
                .BindsTwoWayByDefault())
        .Property(
            Selector::SelectedItemProperty,
            PropertyOptions(Base::Ref<Base::Object>{})
                .BindsTwoWayByDefault()
                .Coerce(&CoerceSelectedObject))
        .Property(
            Selector::SelectedValueProperty,
            PropertyOptions(Base::Ref<Base::Object>{})
                .BindsTwoWayByDefault()
                .Coerce(&CoerceSelectedObject))
        .Property(
            Selector::SelectedValuePathProperty,
            PropertyOptions(Base::String{}))
        .Property(
            Selector::IsSelectedProperty,
            PropertyOptions(false)
                .AffectsRender()
                .BindsTwoWayByDefault());
    status = selector.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<ListBox>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto listBoxItem = Meta::Describe<ListBoxItem>(context);
    listBoxItem
        .Property(
            ListBoxItem::IsSelectedProperty,
            PropertyOptions(false)
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Override(
            Aero::UIElement::IsTabStopProperty,
            PropertyOptions(true))
        .Factory();
    status = listBoxItem.Result();
    if (!status) return status.GetStatus();

    auto comboBox = Meta::Describe<ComboBox>(context);
    comboBox
        .Event(ComboBox::DropDownOpenedEvent)
        .Event(ComboBox::DropDownClosedEvent)
        .Property(
            ComboBox::IsDropDownOpenProperty,
            PropertyOptions(false)
                .AffectsMeasure()
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Property(
            ComboBox::MaxDropDownHeightProperty,
            PropertyOptions(240.0)
                .AffectsMeasure()
                .Validate(
                    &Validate::Positive<double>))
        .Property(
            ComboBox::IsEditableProperty,
            PropertyOptions(false)
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            ComboBox::IsReadOnlyProperty,
            PropertyOptions(false)
                .AffectsRender())
        .Property(
            ComboBox::TextProperty,
            PropertyOptions(Base::String{})
                .AffectsMeasure()
                .BindsTwoWayByDefault())
        .Property(
            ComboBox::PlaceholderProperty,
            PropertyOptions(Base::String{})
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            ComboBox::SelectionBoxTextProperty,
            PropertyOptions(Base::String{}))
        .Property(
            ComboBox::SelectionBoxItemProperty,
            PropertyOptions(
                Core::Value::NullObject(
                    Core::TypeOf<Base::Object>())))
        .Override(
            Aero::UIElement::
                IsTabStopProperty,
            PropertyOptions(true))
        .Factory();
    status = comboBox.Result();
    if (!status) return status.GetStatus();

    auto comboBoxItem =
        Meta::Describe<ComboBoxItem>(context);
    comboBoxItem
        .Property(
            ComboBoxItem::IsSelectedProperty,
            PropertyOptions(false)
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Override(
            Aero::UIElement::
                IsTabStopProperty,
            PropertyOptions(true))
        .Factory();
    status = comboBoxItem.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<UserControl>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<Page>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto popup = Meta::Describe<Popup>(context);
    popup
        .Event(Popup::OpenedEvent)
        .Event(Popup::ClosedEvent)
        .Property(
            Popup::IsOpenProperty,
            PropertyOptions(false)
                .AffectsMeasure()
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Property(
            Popup::PlacementProperty,
            PropertyOptions(
                PlacementMode::Bottom)
                .AffectsArrange())
        .Property(
            Popup::HorizontalOffsetProperty,
            PropertyOptions(0.0)
                .AffectsArrange()
                .Validate(
                    &Validate::Finite<double>))
        .Property(
            Popup::VerticalOffsetProperty,
            PropertyOptions(0.0)
                .AffectsArrange()
                .Validate(
                    &Validate::Finite<double>))
        .Property(
            Popup::StaysOpenProperty,
            PropertyOptions(true))
        .Property(
            Popup::
                MatchPlacementTargetWidthProperty,
            PropertyOptions(false)
                .AffectsArrange())
        .Property(
            Popup::PlacementTargetProperty,
            PropertyOptions(
                Base::Ref<UIElement>{})
                .AffectsArrange())
        .Property(
            Popup::PopupAnimationProperty,
            PropertyOptions(
                PopupAnimation::None)
                .AffectsRender())
        .Property(
            Popup::AllowsTransparencyProperty,
            PropertyOptions(false)
                .AffectsRender())
        .Factory();
    status = popup.Result();
    if (!status) return status.GetStatus();

    auto treeView = Meta::Describe<TreeView>(context);
    treeView
        .Event(
            TreeView::SelectedItemChangedEvent)
        .Property(
            TreeView::SelectedItemProperty,
            PropertyOptions(
                Base::Ref<Base::Object>{}))
        .Factory();
    status = treeView.Result();
    if (!status) return status.GetStatus();

    auto treeViewItem =
        Meta::Describe<TreeViewItem>(context);
    treeViewItem
        .Event(TreeViewItem::ExpandedEvent)
        .Event(TreeViewItem::CollapsedEvent)
        .Event(TreeViewItem::SelectedEvent)
        .Event(TreeViewItem::UnselectedEvent)
        .Property(
            TreeViewItem::HeaderProperty,
            PropertyOptions(Base::String{})
                .AffectsMeasure())
        .Property(
            TreeViewItem::IconProperty,
            PropertyOptions(Base::String{})
                .AffectsMeasure())
        .Property(
            TreeViewItem::HeaderTemplateProperty,
            PropertyOptions(
                Base::Ref<DataTemplate>{})
                .AffectsMeasure())
        .Property(
            TreeViewItem::IsExpandedProperty,
            PropertyOptions(false)
                .AffectsMeasure()
                .BindsTwoWayByDefault())
        .Property(
            TreeViewItem::IsSelectedProperty,
            PropertyOptions(false)
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Property(
            TreeViewItem::HasItemsProperty,
            PropertyOptions(false))
        .Property(
            TreeViewItem::ItemsPanelProperty,
            PropertyOptions(
                Base::Ref<ItemsPanelTemplate>{})
                .AffectsMeasure())
        .Override(
            Aero::UIElement::
                IsTabStopProperty,
            PropertyOptions(true))
        .Content<Base::Object>(
            "Items", ContentKind::Collection,
            &AddTreeViewItem,
            &ClearTreeViewItems)
        .Factory();
    status = treeViewItem.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<Menu>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto menuItem = Meta::Describe<MenuItem>(context);
    menuItem
        .Event(MenuItem::ClickEvent)
        .Property(
            MenuItem::InputGestureTextProperty,
            PropertyOptions(Base::String{})
                .AffectsMeasure())
        .Property(
            MenuItem::IsCheckableProperty,
            PropertyOptions(false)
                .AffectsMeasure())
        .Property(
            MenuItem::IsCheckedProperty,
            PropertyOptions(false)
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Property(
            MenuItem::IsHighlightedProperty,
            PropertyOptions(false).AffectsRender())
        .Property(
            MenuItem::IsSubmenuOpenProperty,
            PropertyOptions(false)
                .AffectsMeasure()
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Property(
            MenuItem::RoleProperty,
            PropertyOptions(MenuItemRole::TopLevelItem)
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            MenuItem::CommandProperty,
            PropertyOptions(
                Base::Ref<ICommand>{}))
        .Property(
            MenuItem::CommandParameterProperty,
            PropertyOptions(
                Base::Ref<Base::Object>{}))
        .Factory();
    status = menuItem.Result();
    if (!status) return status.GetStatus();

    auto contextMenu =
        Meta::Describe<ContextMenu>(context);
    contextMenu
        .Event(ContextMenu::OpenedEvent)
        .Event(ContextMenu::ClosedEvent)
        .Property(
            ContextMenu::IsOpenProperty,
            PropertyOptions(false)
                .AffectsMeasure()
                .AffectsRender()
                .BindsTwoWayByDefault())
        .Property(
            ContextMenu::PlacementTargetProperty,
            PropertyOptions(
                Base::Ref<UIElement>{}))
        .Factory();
    status = contextMenu.Result();
    if (!status) return status.GetStatus();

    auto contextMenuService =
        Meta::Describe<ContextMenuService>(
            context, TypeFlags::Abstract);
    contextMenuService.Property(
        ContextMenuService::
            ContextMenuProperty,
        PropertyOptions(
            Base::Ref<ContextMenu>{}));
    status = contextMenuService.Result();
    if (!status) return status.GetStatus();

    auto gridViewColumnHeader =
        Meta::Describe<GridViewColumnHeader>(context);
    gridViewColumnHeader
        .Property(
            GridViewColumnHeader::RoleProperty,
            PropertyOptions(
                GridViewColumnHeaderRole::Normal))
        .Factory();
    status = gridViewColumnHeader.Result();
    if (!status) return status.GetStatus();

    auto gridViewColumn =
        Meta::Describe<GridViewColumn>(context);
    gridViewColumn
        .Property(
            GridViewColumn::HeaderProperty,
            PropertyOptions(Base::String{}))
        .Property(
            GridViewColumn::WidthProperty,
            PropertyOptions(100.0)
                .Validate(
                    &Validate::NonNegative<double>))
        .Property(
            GridViewColumn::CellTemplateProperty,
            PropertyOptions(
                Base::Ref<DataTemplate>{}))
        .Property(
            GridViewColumn::HeaderTemplateProperty,
            PropertyOptions(
                Base::Ref<DataTemplate>{}))
        .Property(
            GridViewColumn::
                DisplayMemberPathProperty,
            PropertyOptions(Base::String{}))
        .Property(
            GridViewColumn::
                DisplayMemberBindingProperty,
            PropertyOptions(
                Base::Ref<Data::Binding>{}))
        .Property(
            GridViewColumn::HeaderContainerStyleProperty,
            PropertyOptions(Base::Ref<Style>{}))
        .Factory();
    status = gridViewColumn.Result();
    if (!status) return status.GetStatus();

    auto gridView = Meta::Describe<GridView>(context);
    gridView
        .Property<
            Base::Ref<Style>,
            &GridView::ColumnHeaderContainerStyle,
            &GridView::SetColumnHeaderContainerStyle>(
                "ColumnHeaderContainerStyle",
                PropertyFlags::Structural)
        .Content<Base::Object>(
            "Columns",
            ContentKind::Collection,
            &AddGridViewColumn,
            &ClearGridViewColumns)
        .Factory();
    status = gridView.Result();
    if (!status) return status.GetStatus();

    auto gridViewHeaderPresenter =
        Meta::Describe<GridViewHeaderRowPresenter>(context);
    gridViewHeaderPresenter
        .Property(
            GridViewHeaderRowPresenter::
                AllowsColumnReorderProperty,
            PropertyOptions(false))
        .Property(
            GridViewHeaderRowPresenter::
                ColumnHeaderContainerStyleProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            GridViewHeaderRowPresenter::
                ColumnHeaderContextMenuProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            GridViewHeaderRowPresenter::
                ColumnHeaderTemplateProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            GridViewHeaderRowPresenter::
                ColumnHeaderTemplateSelectorProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            GridViewHeaderRowPresenter::ColumnHeaderToolTipProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            GridViewHeaderRowPresenter::ColumnsProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Factory();
    status = gridViewHeaderPresenter.Result();
    if (!status) return status.GetStatus();

    auto gridViewRowPresenter =
        Meta::Describe<GridViewRowPresenter>(context);
    gridViewRowPresenter
        .Property(
            GridViewRowPresenter::ColumnsProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Property(
            GridViewRowPresenter::ContentProperty,
            PropertyOptions(Base::Ref<Base::Object>{}))
        .Factory();
    status = gridViewRowPresenter.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<ListView>(context)
        .Property(
            ListView::ViewProperty,
            PropertyOptions(
                Base::Ref<GridView>{})
                .AffectsMeasure())
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto listViewItem =
        Meta::Describe<ListViewItem>(context);
    listViewItem
        .Override(
            Aero::UIElement::
                IsTabStopProperty,
            PropertyOptions(true))
        .Factory();
    status = listViewItem.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<Separator>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto toolBar = Meta::Describe<ToolBar>(context);
    toolBar
        .Property(
            ToolBar::HeaderProperty,
            PropertyOptions(Core::Value::NullObject(
                Core::TypeOf<Base::Object>()))
                .AffectsMeasure())
        .Property(
            ToolBar::HeaderTemplateProperty,
            PropertyOptions(Base::Ref<DataTemplate>{})
                .AffectsMeasure())
        .Property(
            ToolBar::OrientationProperty,
            PropertyOptions(
                Orientation::Horizontal)
                .AffectsMeasure())
        .Property(
            ToolBar::
                OverflowCapacityProperty,
            PropertyOptions(UINT32_MAX)
                .AffectsMeasure())
        .Property(
            ToolBar::IsOverflowOpenProperty,
            PropertyOptions(false)
                .AffectsRender())
        .Property(
            ToolBar::
                HasOverflowItemsProperty,
            PropertyOptions(false))
        .Property(
            ToolBar::
                OverflowItemCountProperty,
            PropertyOptions(
                std::uint32_t{0U}))
        .Factory();
    status = toolBar.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<ToolBarPanel>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<ToolBarOverflowPanel>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto toolBarTray = Meta::Describe<ToolBarTray>(context, TypeFlags::Abstract);
    toolBarTray.Property(
        ToolBarTray::IsLockedProperty,
        PropertyOptions(false));
    status = toolBarTray.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<StatusBar>(context)
        .Property(
            StatusBar::
                IsSizingGripVisibleProperty,
            PropertyOptions(true)
                .AffectsRender())
        .Factory()
        .Result();
    if (!status) return status.GetStatus();
    status = Meta::Describe<StatusBarItem>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto toolTip = Meta::Describe<ToolTip>(context);
    toolTip
        .Property(
            ToolTip::InitialShowDelayProperty,
            PropertyOptions(
                std::uint32_t{500U}))
        .Property(
            ToolTip::ShowDurationProperty,
            PropertyOptions(
                std::uint32_t{5000U}))
        .Factory();
    status = toolTip.Result();
    if (!status) return status.GetStatus();

    auto toolTipService =
        Meta::Describe<ToolTipService>(
            context, TypeFlags::Abstract);
    toolTipService
        .Property(
            ToolTipService::ToolTipProperty,
            PropertyOptions(
                Base::Ref<ToolTip>{}))
        .Property(
            ToolTipService::
                InitialShowDelayProperty,
            PropertyOptions(
                std::uint32_t{500U}))
        .Property(
            ToolTipService::
                ShowDurationProperty,
            PropertyOptions(
                std::uint32_t{5000U}));
    status = toolTipService.Result();
    if (!status) return status.GetStatus();

    auto headered = Meta::Describe<HeaderedContentControl>(
        context, TypeFlags::Abstract);
    headered
        .Property(
            HeaderedContentControl::HeaderProperty,
            PropertyOptions(Core::Value::NullObject(
                Core::TypeOf<Base::Object>()))
                .AffectsMeasure())
        .Property(
            HeaderedContentControl::HeaderTemplateProperty,
            PropertyOptions(Base::Ref<DataTemplate>{})
                .AffectsMeasure());
    status = headered.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<GroupBox>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<Label>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto expander = Meta::Describe<Expander>(context);
    expander
        .Event(Expander::ExpandedEvent)
        .Event(Expander::CollapsedEvent)
        .Property(
            Expander::IsExpandedProperty,
            PropertyOptions(false)
                .AffectsMeasure())
        .Property(
            Expander::ExpandDirectionProperty,
            PropertyOptions(ExpandDirection::Down)
                .AffectsMeasure())
        .Factory();
    status = expander.Result();
    if (!status) return status.GetStatus();

    auto tabItem = Meta::Describe<TabItem>(context);
    tabItem
        .Property(
            TabItem::IsSelectedProperty,
            PropertyOptions(false)
                .AffectsRender())
        .Factory();
    status = tabItem.Result();
    if (!status) return status.GetStatus();

    auto tabControl = Meta::Describe<TabControl>(context);
    tabControl
        .Event(TabControl::SelectionChangedEvent)
        .Property(
            TabControl::SelectedIndexProperty,
            PropertyOptions(UINT32_MAX)
                .AffectsMeasure()
                .BindsTwoWayByDefault())
        .Property(
            TabControl::SelectedContentProperty,
            PropertyOptions(
                Core::Value::NullObject(
                    Core::TypeOf<Base::Object>())))
        .Property(
            TabControl::ItemsSourceProperty,
            PropertyOptions(Base::Ref<Base::Object>{})
                .AffectsMeasure())
        .Property(
            TabControl::ItemTemplateProperty,
            PropertyOptions(Base::Ref<DataTemplate>{})
                .AffectsMeasure())
        .Property(
            TabControl::ContentTemplateProperty,
            PropertyOptions(Base::Ref<DataTemplate>{})
                .AffectsMeasure())
        .Property(
            TabControl::TabStripPlacementProperty,
            PropertyOptions(Dock::Top)
                .AffectsMeasure())
        .Content<TabItem>(
            "Items",
            ContentKind::Collection,
            &AddTabControlItem,
            &ClearTabControlItems,
            ContentFlags::Visual)
        .Factory();
    status = tabControl.Result();
    if (!status) return status.GetStatus();

    status = Meta::Describe<TabPanel>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();
    return {};
}
