// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsPanels(
    Core::MetadataContext& context) noexcept {
    Base::Result<void> status;
    auto stackPanel = Describe<StackPanel>(context);
    stackPanel
        .Property(
            StackPanel::OrientationProperty,
            PropertyOptions(Orientation::Vertical)
                .AffectsMeasure())
        .Factory();
    status = stackPanel.Result();
    if (!status) return status.GetStatus();

    auto dockPanel = Describe<DockPanel>(context);
    dockPanel
        .Property(
            DockPanel::LastChildFillProperty,
            PropertyOptions(true)
                .AffectsArrange())
        .Property(
            DockPanel::DockProperty,
            PropertyOptions(Dock::Left)
                .AffectsParentMeasure())
        .Factory();
    status = dockPanel.Result();
    if (!status) return status.GetStatus();

    auto wrapPanel = Describe<WrapPanel>(context);
    wrapPanel
        .Property(
            WrapPanel::OrientationProperty,
            PropertyOptions(Orientation::Horizontal)
                .AffectsMeasure())
        .Property(
            WrapPanel::ItemWidthProperty,
            PropertyOptions(0.0)
                .AffectsMeasure()
                .Validate(&Validate::NonNegative<double>))
        .Property(
            WrapPanel::ItemHeightProperty,
            PropertyOptions(0.0)
                .AffectsMeasure()
                .Validate(&Validate::NonNegative<double>))
        .Factory();
    status = wrapPanel.Result();
    if (!status) return status.GetStatus();

    auto uniformGrid = Describe<UniformGrid>(context);
    uniformGrid
        .Property(
            UniformGrid::RowsProperty,
            PropertyOptions(std::uint32_t{0})
                .AffectsMeasure())
        .Property(
            UniformGrid::ColumnsProperty,
            PropertyOptions(std::uint32_t{0})
                .AffectsMeasure())
        .Property(
            UniformGrid::FirstColumnProperty,
            PropertyOptions(std::uint32_t{0})
                .AffectsMeasure()
                .AffectsArrange())
        .Factory();
    status = uniformGrid.Result();
    if (!status) return status.GetStatus();

    auto scrollUnit = Describe<ScrollUnit>(context);
    scrollUnit
        .Value("Item", ScrollUnit::Item)
        .Value("Pixel", ScrollUnit::Pixel);
    status = scrollUnit.Result();
    if (!status) return status.GetStatus();

    auto virtualizationMode = Describe<VirtualizationMode>(context);
    virtualizationMode
        .Value("Standard", VirtualizationMode::Standard)
        .Value("Recycling", VirtualizationMode::Recycling);
    status = virtualizationMode.Result();
    if (!status) return status.GetStatus();

    auto virtualizingPanel = Describe<VirtualizingPanel>(
        context, TypeFlags::Abstract);
    virtualizingPanel.Property(
        VirtualizingPanel::ScrollUnitProperty,
        PropertyOptions(ScrollUnit::Item)
            .AffectsParentMeasure());
    virtualizingPanel.Property(
        VirtualizingPanel::VirtualizationModeProperty,
        PropertyOptions(VirtualizationMode::Standard)
            .AffectsParentMeasure());
    status = virtualizingPanel.Result();
    if (!status) return status.GetStatus();

    auto virtualizingStackPanel =
        Describe<VirtualizingStackPanel>(context);
    virtualizingStackPanel
        .Property(
            VirtualizingStackPanel::OrientationProperty,
            PropertyOptions(Orientation::Vertical)
                .AffectsMeasure())
        .Property(
            VirtualizingStackPanel::OverscanCountProperty,
            PropertyOptions(std::uint32_t{2})
                .AffectsMeasure())
        .Property(
            VirtualizingStackPanel::
                EstimatedItemExtentProperty,
            PropertyOptions(24.0)
                .AffectsMeasure()
                .Validate(&Validate::Positive<double>))
        .Factory();
    status = virtualizingStackPanel.Result();
    if (!status) return status.GetStatus();

    auto canvas = Describe<Canvas>(context);
    canvas
        .Property(
            Canvas::LeftProperty,
            PropertyOptions(0.0)
                .AffectsParentMeasure()
                .Validate(&Validate::Finite<double>))
        .Property(
            Canvas::TopProperty,
            PropertyOptions(0.0)
                .AffectsParentMeasure()
                .Validate(&Validate::Finite<double>))
        .Property(
            Canvas::RightProperty,
            PropertyOptions(0.0)
                .AffectsParentArrange()
                .Validate(&Validate::Finite<double>))
        .Property(
            Canvas::BottomProperty,
            PropertyOptions(0.0)
                .AffectsParentArrange()
                .Validate(&Validate::Finite<double>))
        .Factory();
    status = canvas.Result();
    if (!status) return status.GetStatus();

    auto columnDefinition =
        Describe<ColumnDefinition>(context);
    columnDefinition
        .Property<
            GridLength,
            &ColumnDefinition::Width,
            &ColumnDefinition::SetWidth>(
                "Width",
                PropertyFlags::Structural)
        .Property<
            double,
            &ColumnDefinition::MaxWidth,
            &ColumnDefinition::SetMaxWidth>(
                "MaxWidth",
                PropertyFlags::Structural)
        .Property<
            Base::String,
            &ColumnDefinition::SharedSizeGroup,
            &ColumnDefinition::SetSharedSizeGroup>(
                "SharedSizeGroup",
                PropertyFlags::Structural)
        .Factory();
    status = columnDefinition.Result();
    if (!status) return status.GetStatus();

    auto rowDefinition =
        Describe<RowDefinition>(context);
    rowDefinition
        .Property<
            GridLength,
            &RowDefinition::Height,
            &RowDefinition::SetHeight>(
                "Height",
                PropertyFlags::Structural)
        .Property<
            double,
            &RowDefinition::MaxHeight,
            &RowDefinition::SetMaxHeight>(
                "MaxHeight",
                PropertyFlags::Structural)
        .Property<
            Base::String,
            &RowDefinition::SharedSizeGroup,
            &RowDefinition::SetSharedSizeGroup>(
                "SharedSizeGroup",
                PropertyFlags::Structural)
        .Factory();
    status = rowDefinition.Result();
    if (!status) return status.GetStatus();

    auto grid = Describe<Grid>(context);
    grid
        .Property(
            Grid::IsSharedSizeScopeProperty,
            PropertyOptions(false))
        .Property(
            Grid::ColumnDefinitionsTextProperty,
            PropertyOptions(Base::String{})
                .AffectsMeasure()
                .Validate(
                    &ValidateGridDefinitionsText)
                .Changed(
                    &OnGridColumnsChanged))
        .Property(
            Grid::RowDefinitionsTextProperty,
            PropertyOptions(Base::String{})
                .AffectsMeasure()
                .Validate(
                    &ValidateGridDefinitionsText)
                .Changed(
                    &OnGridRowsChanged))
        .Collection<ColumnDefinition>(
            "ColumnDefinitions",
            &AddGridColumnDefinition,
            &ClearGridColumnDefinitions)
        .Collection<RowDefinition>(
            "RowDefinitions",
            &AddGridRowDefinition,
            &ClearGridRowDefinitions)
        .Collection<Presentation::KeyBinding>(
            "InputBindings",
            &AddGridInputBinding,
            &ClearGridInputBindings)
        .Property(
            Grid::RowProperty,
            PropertyOptions(std::uint32_t{0})
                .AffectsParentMeasure())
        .Property(
            Grid::ColumnProperty,
            PropertyOptions(std::uint32_t{0})
                .AffectsParentMeasure())
        .Property(
            Grid::RowSpanProperty,
            PropertyOptions(std::uint32_t{1})
                .AffectsParentMeasure()
                .Validate(&Validate::Positive<std::uint32_t>))
        .Property(
            Grid::ColumnSpanProperty,
            PropertyOptions(std::uint32_t{1})
                .AffectsParentMeasure()
                .Validate(&Validate::Positive<std::uint32_t>))
        .Factory();
    status = grid.Result();
    if (!status) return status.GetStatus();

    auto border = Describe<Border>(context);
    border
        .Property(
            Border::BackgroundProperty,
            PropertyOptions(
                Base::Ref<Presentation::Brush>{})
                .AffectsRender())
        .Property(
            Border::BorderBrushProperty,
            PropertyOptions(
                Base::Ref<Presentation::Brush>{})
                .AffectsRender())
        .Property(
            Border::BorderThicknessProperty,
            PropertyOptions(Presentation::Thickness{})
                .AffectsMeasure()
                .AffectsRender()
                .Validate(&ValidateThicknessValue))
        .Property(
            Border::CornerRadiusProperty,
            PropertyOptions(
                Presentation::CornerRadius{})
                .AffectsRender()
                .Validate(
                    &ValidateCornerRadiusValue))
        .Property(
            Border::PaddingProperty,
            PropertyOptions(Presentation::Thickness{})
                .AffectsMeasure()
                .Validate(&ValidateThicknessValue))
        .Factory();
    status = border.Result();
    if (!status) return status.GetStatus();
    return {};
}
