// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsTemplates(
    Core::MetadataContext& context) noexcept {
    Base::Result<void> status;
    auto frameworkTemplate = Describe<FrameworkTemplate>(
        context, TypeFlags::Abstract);
    frameworkTemplate
        .Property<
            Base::Ref<Presentation::ResourceDictionary>,
            &FrameworkTemplate::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Collection<Base::Object>(
            "Triggers",
            &AddTemplateTrigger,
            &ClearTemplateTriggers);
    status = frameworkTemplate.Result();
    if (!status) return status.GetStatus();

    auto controlTemplate = Describe<ControlTemplate>(context);
    controlTemplate
        .Property<
            Core::TypeReference,
            &GetControlTemplateTargetType,
            &SetControlTemplateTargetType>(
            "TargetType",
            PropertyFlags::None)
        .Collection<Base::Object>(
            "VisualStateGroups",
            &AddTemplateVisualStateGroup,
            &ClearTemplateVisualStateGroups)
        .Content<Base::Object>(
            "VisualTree",
            ContentKind::Single,
            &SetDeferredTemplateVisualTree<
                ControlTemplate>,
            &ClearDeferredTemplateVisualTree<
                ControlTemplate>,
            ContentFlags::Visual)
        .Factory();
    status = controlTemplate.Result();
    if (!status) return status.GetStatus();

    auto dataTemplate = Describe<DataTemplate>(context);
    dataTemplate
        .Property<
            Core::TypeReference,
            &GetDataTemplateType,
            &SetDataTemplateType>(
            "DataType",
            PropertyFlags::None)
        .Property<
            Base::Ref<Base::Object>,
            &DataTemplate::HierarchicalItemsSource,
            &DataTemplate::SetHierarchicalItemsSource>(
                "ItemsSource", PropertyFlags::None)
        .Property<
            Base::Ref<Base::Object>,
            &DataTemplate::HierarchicalItemTemplate,
            &DataTemplate::SetHierarchicalItemTemplate>(
                "ItemTemplate", PropertyFlags::None)
        .Property<
            Base::Ref<Presentation::ResourceDictionary>,
            &DataTemplate::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Collection<Presentation::TriggerBase>(
            "Triggers",
            &AddDataTemplateTrigger,
            &ClearDataTemplateTriggers)
        .Content<Base::Object>(
            "VisualTree",
            ContentKind::Single,
            &SetDeferredTemplateVisualTree<DataTemplate>,
            &ClearDeferredTemplateVisualTree<DataTemplate>,
            ContentFlags::Visual)
        .Factory();
    status = dataTemplate.Result();
    if (!status) return status.GetStatus();

    auto itemsPanelTemplate =
        Describe<ItemsPanelTemplate>(context);
    itemsPanelTemplate
        .Property<
            Base::Ref<Presentation::ResourceDictionary>,
            &ItemsPanelTemplate::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Content<Base::Object>(
            "VisualTree",
            ContentKind::Single,
            &SetDeferredTemplateVisualTree<ItemsPanelTemplate>,
            &ClearDeferredTemplateVisualTree<ItemsPanelTemplate>,
            ContentFlags::Visual)
        .Factory();
    status = itemsPanelTemplate.Result();
    if (!status) return status.GetStatus();
    return {};
}
