// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsValues(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    auto orientation = Meta::Register<Orientation>(context);
    orientation
        .Value("Horizontal", Orientation::Horizontal)
        .Value("Vertical", Orientation::Vertical);
    status = orientation.Result();
    if (!status) return status.GetStatus();

    auto menuItemRole = Meta::Register<MenuItemRole>(context);
    menuItemRole
        .Value("TopLevelItem", MenuItemRole::TopLevelItem)
        .Value("TopLevelHeader", MenuItemRole::TopLevelHeader)
        .Value("SubmenuItem", MenuItemRole::SubmenuItem)
        .Value("SubmenuHeader", MenuItemRole::SubmenuHeader);
    status = menuItemRole.Result();
    if (!status) return status.GetStatus();

    auto gridViewColumnHeaderRole =
        Meta::Register<GridViewColumnHeaderRole>(context);
    gridViewColumnHeaderRole
        .Value("Normal", GridViewColumnHeaderRole::Normal)
        .Value("Floating", GridViewColumnHeaderRole::Floating)
        .Value("Padding", GridViewColumnHeaderRole::Padding);
    status = gridViewColumnHeaderRole.Result();
    if (!status) return status.GetStatus();

    auto penLineJoin =
        Meta::Register<PenLineJoin>(context);
    penLineJoin
        .Value("Miter", PenLineJoin::Miter)
        .Value("Bevel", PenLineJoin::Bevel)
        .Value("Round", PenLineJoin::Round);
    status = penLineJoin.Result();
    if (!status) return status.GetStatus();

    auto penLineCap = Meta::Register<PenLineCap>(context);
    penLineCap
        .Value("Flat", PenLineCap::Flat)
        .Value("Square", PenLineCap::Square)
        .Value("Round", PenLineCap::Round)
        .Value("Triangle", PenLineCap::Triangle);
    status = penLineCap.Result();
    if (!status) return status.GetStatus();

    auto tickPlacement =
        Meta::Register<TickPlacement>(context);
    tickPlacement
        .Value("None", TickPlacement::None)
        .Value("TopLeft", TickPlacement::TopLeft)
        .Value(
            "BottomRight",
            TickPlacement::BottomRight)
        .Value("Both", TickPlacement::Both);
    status = tickPlacement.Result();
    if (!status) return status.GetStatus();

    auto tickBarPlacement =
        Meta::Register<TickBarPlacement>(context);
    tickBarPlacement
        .Value("Top", TickBarPlacement::Top)
        .Value("Bottom", TickBarPlacement::Bottom)
        .Value("Left", TickBarPlacement::Left)
        .Value("Right", TickBarPlacement::Right);
    status = tickBarPlacement.Result();
    if (!status) return status.GetStatus();

    auto scrollBarVisibility =
        Meta::Register<ScrollBarVisibility>(context);
    scrollBarVisibility
        .Value(
            "Disabled",
            ScrollBarVisibility::Disabled)
        .Value("Auto", ScrollBarVisibility::Auto)
        .Value("Hidden", ScrollBarVisibility::Hidden)
        .Value("Visible", ScrollBarVisibility::Visible);
    status = scrollBarVisibility.Result();
    if (!status) return status.GetStatus();

    auto panningMode = Meta::Register<PanningMode>(context);
    panningMode
        .Value("None", PanningMode::None)
        .Value("HorizontalOnly", PanningMode::HorizontalOnly)
        .Value("VerticalOnly", PanningMode::VerticalOnly)
        .Value("Both", PanningMode::Both)
        .Value("HorizontalFirst", PanningMode::HorizontalFirst)
        .Value("VerticalFirst", PanningMode::VerticalFirst);
    status = panningMode.Result();
    if (!status) return status.GetStatus();

    auto gridResizeDirection = Meta::Register<GridResizeDirection>(context);
    gridResizeDirection
        .Value("Auto", GridResizeDirection::Auto)
        .Value("Columns", GridResizeDirection::Columns)
        .Value("Rows", GridResizeDirection::Rows);
    status = gridResizeDirection.Result();
    if (!status) return status.GetStatus();

    auto gridResizeBehavior = Meta::Register<GridResizeBehavior>(context);
    gridResizeBehavior
        .Value(
            "BasedOnAlignment",
            GridResizeBehavior::BasedOnAlignment)
        .Value("CurrentAndNext", GridResizeBehavior::CurrentAndNext)
        .Value(
            "PreviousAndCurrent",
            GridResizeBehavior::PreviousAndCurrent)
        .Value("PreviousAndNext", GridResizeBehavior::PreviousAndNext);
    status = gridResizeBehavior.Result();
    if (!status) return status.GetStatus();

    auto dock = Meta::Register<Dock>(context);
    dock
        .Value("Left", Dock::Left)
        .Value("Top", Dock::Top)
        .Value("Right", Dock::Right)
        .Value("Bottom", Dock::Bottom);
    status = dock.Result();
    if (!status) return status.GetStatus();

    auto textWrapping = Meta::Register<Text::TextWrapping>(context);
    textWrapping
        .Value("NoWrap", Text::TextWrapping::NoWrap)
        .Value("Wrap", Text::TextWrapping::Wrap)
        .Value(
            "WrapWithOverflow",
            Text::TextWrapping::WrapWithOverflow);
    status = textWrapping.Result();
    if (!status) return status.GetStatus();

    auto textTrimming = Meta::Register<Text::TextTrimming>(context);
    textTrimming
        .Value("None", Text::TextTrimming::None)
        .Value(
            "CharacterEllipsis",
            Text::TextTrimming::CharacterEllipsis)
        .Value(
            "WordEllipsis",
            Text::TextTrimming::WordEllipsis);
    status = textTrimming.Result();
    if (!status) return status.GetStatus();

    auto textAlignment = Meta::Register<Text::TextAlignment>(context);
    textAlignment
        .Value("Left", Text::TextAlignment::Start)
        .Value("Center", Text::TextAlignment::Center)
        .Value("Right", Text::TextAlignment::End)
        .Value("Justify", Text::TextAlignment::Justify);
    status = textAlignment.Result();
    if (!status) return status.GetStatus();

    auto fontWeight = Meta::Register<FontWeight>(context);
    fontWeight
        .Value("Normal", FontWeight::Normal)
        .Value("SemiBold", FontWeight::SemiBold)
        .Value("Bold", FontWeight::Bold);
    status = fontWeight.Result();
    if (!status) return status.GetStatus();

    auto fontStyle = Meta::Register<Text::FontStyle>(context);
    fontStyle
        .Value("Normal", Text::FontStyle::Normal)
        .Value("Italic", Text::FontStyle::Italic)
        .Value("Oblique", Text::FontStyle::Oblique);
    status = fontStyle.Result();
    if (!status) return status.GetStatus();

    auto textDecorations =
        Meta::Register<TextDecorations>(context);
    textDecorations
        .Value("None", TextDecorations::None)
        .Value(
            "Underline",
            TextDecorations::Underline);
    status = textDecorations.Result();
    if (!status) return status.GetStatus();

    auto gridLength = Meta::Register<GridLength>(context);
    gridLength
        .ValueSemantics({
            sizeof(GridLength),
            alignof(GridLength),
            nullptr,
            nullptr,
            &EqualGridLength,
            nullptr,
            true})
        .TextConverter<&ConvertGridLength>();
    status = gridLength.Result();
    if (!status) return status.GetStatus();

    auto clickMode = Meta::Register<ClickMode>(context);
    clickMode
        .Value("Release", ClickMode::Release)
        .Value("Press", ClickMode::Press)
        .Value("Hover", ClickMode::Hover);
    status = clickMode.Result();
    if (!status) return status.GetStatus();

    auto selectionMode = Meta::Register<SelectionMode>(context);
    selectionMode
        .Value("Single", SelectionMode::Single)
        .Value("Multiple", SelectionMode::Multiple)
        .Value("Extended", SelectionMode::Extended);
    status = selectionMode.Result();
    if (!status) return status.GetStatus();

    auto expandDirection =
        Meta::Register<ExpandDirection>(context);
    expandDirection
        .Value("Down", ExpandDirection::Down)
        .Value("Up", ExpandDirection::Up)
        .Value("Left", ExpandDirection::Left)
        .Value("Right", ExpandDirection::Right);
    status = expandDirection.Result();
    if (!status) return status.GetStatus();

    auto placementMode =
        Meta::Register<PlacementMode>(context);
    placementMode
        .Value("Bottom", PlacementMode::Bottom)
        .Value("Top", PlacementMode::Top)
        .Value("Left", PlacementMode::Left)
        .Value("Right", PlacementMode::Right)
        .Value("Center", PlacementMode::Center)
        .Value("Mouse", PlacementMode::Mouse);
    status = placementMode.Result();
    if (!status) return status.GetStatus();

    auto popupAnimation =
        Meta::Register<PopupAnimation>(context);
    popupAnimation
        .Value("None", PopupAnimation::None)
        .Value("Fade", PopupAnimation::Fade)
        .Value("Slide", PopupAnimation::Slide)
        .Value("Scroll", PopupAnimation::Scroll);
    status = popupAnimation.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<ScrollChangedEventArgs>(context).Result();
    if (!status) return status.GetStatus();
    status = Meta::Register<RangeValueChangedEventArgs>(
        context).Result();
    if (!status) return status.GetStatus();
    return {};
}
