#include <Aero/Interactivity/Conditions.hpp>
#include <Aero/Interactivity/Interaction.hpp>
#include <Aero/Interactivity/TriggerAction.hpp>
// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiAnimation(
    ::Aero::Meta::Registration& context) noexcept {
    Register<Media::Animation::Duration>(context)
        .ValueSemantics()
        .TextConverter<&Media::Animation::Duration::TryParse>();

    Register<Media::Animation::TimeSpan>(context)
        .ValueSemantics()
        .TextConverter<&Media::Animation::TimeSpan::TryParse>();

    Register<Media::Animation::RepeatBehavior>(context)
        .ValueSemantics()
        .TextConverter<&Media::Animation::RepeatBehavior::TryParse>();

    Register<Media::Animation::KeyTime>(context)
        .ValueSemantics()
        .TextConverter<&Media::Animation::KeyTime::TryParse>();

    Register<Media::Animation::Timeline>(context, TypeFlags::Abstract)
        .Property(Media::Animation::Timeline::BeginTimeProperty, Media::Animation::TimeSpan::Zero())
        .Property(Media::Animation::Timeline::DurationProperty, Media::Animation::Duration::Automatic())
        .Property(Media::Animation::Timeline::RepeatBehaviorProperty, Media::Animation::RepeatBehavior::Once())
        .Property(Media::Animation::Timeline::SpeedRatioProperty, 1.0)
        .Property(Media::Animation::Timeline::AutoReverseProperty, false)
        .Property(Media::Animation::Timeline::FillBehaviorProperty, FillBehavior::HoldEnd);

    Register<Media::Animation::AnimationTimeline>(context, TypeFlags::Abstract);
    Register<Media::Animation::TimelineGroup>(context, TypeFlags::Abstract);

    Register<Media::Animation::ParallelTimeline>(context)
        .Content<Media::Animation::Timeline>("Children", ContentKind::Collection, &AddStoryboardTimeline, &ClearStoryboardTimelines)
        .Factory();

    Register<Media::Animation::Storyboard>(context)
        .Property(Media::Animation::Storyboard::TargetNameProperty, Base::String{})
        .Property(Media::Animation::Storyboard::TargetPropertyProperty, Base::String{})
        .Content<Media::Animation::Timeline>("Children", ContentKind::Collection, &AddStoryboardTimeline, &ClearStoryboardTimelines)
        .Factory();

    Register<Media::Animation::EasingFunctionBase>(context, TypeFlags::Abstract)
        .Property(Media::Animation::EasingFunctionBase::EasingModeProperty, EasingMode::EaseOut);

    Register<Media::Animation::SineEase>(context).Factory();
    Register<Media::Animation::QuadraticEase>(context).Factory();
    Register<Media::Animation::CubicEase>(context).Factory();
    Register<Media::Animation::QuarticEase>(context).Factory();
    Register<Media::Animation::QuinticEase>(context).Factory();
    Register<Media::Animation::CircleEase>(context).Factory();
    Register<Media::Animation::ExponentialEase>(context)
        .Property(Media::Animation::ExponentialEase::ExponentProperty, 2.0)
        .Factory();

    Register<Media::Animation::PowerEase>(context)
        .Property(Media::Animation::PowerEase::PowerProperty, 2.0)
        .Factory();

    Register<Media::Animation::BackEase>(context)
        .Property(Media::Animation::BackEase::AmplitudeProperty, 1.0)
        .Factory();

    Register<Media::Animation::BounceEase>(context)
        .Property(Media::Animation::BounceEase::BouncesProperty, 3.0)
        .Property(Media::Animation::BounceEase::BouncinessProperty, 3.0)
        .Factory();

    Register<Media::Animation::ElasticEase>(context)
        .Property(Media::Animation::ElasticEase::OscillationsProperty, 3.0)
        .Property(Media::Animation::ElasticEase::SpringinessProperty, 3.0)
        .Factory();

    Register<Media::Animation::DoubleAnimationBase>(context, TypeFlags::Abstract)
        .Property<double, &Media::Animation::DoubleAnimationBase::GetFrom, &Media::Animation::DoubleAnimationBase::SetFrom>("From")
        .Property<double, &Media::Animation::DoubleAnimationBase::GetTo, &Media::Animation::DoubleAnimationBase::SetTo>("To");

    Register<Media::Animation::DoubleAnimation>(context)
        .Property<double, &Media::Animation::DoubleAnimation::GetAccelerationRatio, &Media::Animation::DoubleAnimation::SetAccelerationRatio>("AccelerationRatio")
        .Property<double, &Media::Animation::DoubleAnimation::GetDecelerationRatio, &Media::Animation::DoubleAnimation::SetDecelerationRatio>("DecelerationRatio")
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::DoubleAnimation::GetEasingFunction, &Media::Animation::DoubleAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::ColorAnimationBase>(context, TypeFlags::Abstract)
        .Property<Color, &Media::Animation::ColorAnimationBase::GetFrom, &Media::Animation::ColorAnimationBase::SetFrom>("From")
        .Property<Color, &Media::Animation::ColorAnimationBase::GetTo, &Media::Animation::ColorAnimationBase::SetTo>("To");

    Register<Media::Animation::ColorAnimation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::ColorAnimation::GetEasingFunction, &Media::Animation::ColorAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::PointAnimationBase>(context, TypeFlags::Abstract)
        .Property<Point, &Media::Animation::PointAnimationBase::GetFrom, &Media::Animation::PointAnimationBase::SetFrom>("From")
        .Property<Point, &Media::Animation::PointAnimationBase::GetTo, &Media::Animation::PointAnimationBase::SetTo>("To");

    Register<Media::Animation::PointAnimation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::PointAnimation::GetEasingFunction, &Media::Animation::PointAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::RectAnimationBase>(context, TypeFlags::Abstract)
        .Property<Rect, &Media::Animation::RectAnimationBase::GetFrom, &Media::Animation::RectAnimationBase::SetFrom>("From")
        .Property<Rect, &Media::Animation::RectAnimationBase::GetTo, &Media::Animation::RectAnimationBase::SetTo>("To");

    Register<Media::Animation::RectAnimation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::RectAnimation::GetEasingFunction, &Media::Animation::RectAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::ThicknessAnimationBase>(context, TypeFlags::Abstract)
        .Property<Base::Thickness, &Media::Animation::ThicknessAnimationBase::GetFrom, &Media::Animation::ThicknessAnimationBase::SetFrom>("From")
        .Property<Base::Thickness, &Media::Animation::ThicknessAnimationBase::GetTo, &Media::Animation::ThicknessAnimationBase::SetTo>("To");

    Register<Media::Animation::ThicknessAnimation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::ThicknessAnimation::GetEasingFunction, &Media::Animation::ThicknessAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::Int16AnimationBase>(context, TypeFlags::Abstract)
        .Property<std::int16_t, &Media::Animation::Int16AnimationBase::GetFrom, &Media::Animation::Int16AnimationBase::SetFrom>("From")
        .Property<std::int16_t, &Media::Animation::Int16AnimationBase::GetTo, &Media::Animation::Int16AnimationBase::SetTo>("To");
    Register<Media::Animation::Int16Animation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::Int16Animation::GetEasingFunction, &Media::Animation::Int16Animation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::Int32AnimationBase>(context, TypeFlags::Abstract)
        .Property<std::int32_t, &Media::Animation::Int32AnimationBase::GetFrom, &Media::Animation::Int32AnimationBase::SetFrom>("From")
        .Property<std::int32_t, &Media::Animation::Int32AnimationBase::GetTo, &Media::Animation::Int32AnimationBase::SetTo>("To");
    Register<Media::Animation::Int32Animation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::Int32Animation::GetEasingFunction, &Media::Animation::Int32Animation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::Int64AnimationBase>(context, TypeFlags::Abstract)
        .Property<std::int64_t, &Media::Animation::Int64AnimationBase::GetFrom, &Media::Animation::Int64AnimationBase::SetFrom>("From")
        .Property<std::int64_t, &Media::Animation::Int64AnimationBase::GetTo, &Media::Animation::Int64AnimationBase::SetTo>("To");
    Register<Media::Animation::Int64Animation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::Int64Animation::GetEasingFunction, &Media::Animation::Int64Animation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::SizeAnimationBase>(context, TypeFlags::Abstract)
        .Property<Base::Size, &Media::Animation::SizeAnimationBase::GetFrom, &Media::Animation::SizeAnimationBase::SetFrom>("From")
        .Property<Base::Size, &Media::Animation::SizeAnimationBase::GetTo, &Media::Animation::SizeAnimationBase::SetTo>("To");
    Register<Media::Animation::SizeAnimation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::SizeAnimation::GetEasingFunction, &Media::Animation::SizeAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::MatrixAnimationBase>(context, TypeFlags::Abstract)
        .Property<Base::Transform2D, &Media::Animation::MatrixAnimationBase::GetFrom, &Media::Animation::MatrixAnimationBase::SetFrom>("From")
        .Property<Base::Transform2D, &Media::Animation::MatrixAnimationBase::GetTo, &Media::Animation::MatrixAnimationBase::SetTo>("To");
    Register<Media::Animation::MatrixAnimation>(context)
        .Property<Base::Ref<Media::Animation::EasingFunctionBase>, &Media::Animation::MatrixAnimation::GetEasingFunction, &Media::Animation::MatrixAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::KeyFrameBase>(context, TypeFlags::Abstract)
        .Property(Media::Animation::KeyFrameBase::KeyTimeProperty, Media::Animation::KeyTime{})
        .Property(Media::Animation::KeyFrameBase::EasingFunctionProperty, Base::Ref<Media::Animation::EasingFunctionBase>{}, AffectsRender)
        .Property(Media::Animation::KeyFrameBase::KeySplineProperty, FrameworkPropertyMetadata(Base::String{}) .Changed(&Media::Animation::KeyFrameBase::OnKeySplineChanged));

    Register<Media::Animation::DoubleKeyFrame>(context, TypeFlags::Abstract)
        .Property<double, &Media::Animation::DoubleKeyFrame::GetValue, &Media::Animation::DoubleKeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearDoubleKeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteDoubleKeyFrame>(context).Factory();
    Register<Media::Animation::EasingDoubleKeyFrame>(context).Factory();
    Register<Media::Animation::SplineDoubleKeyFrame>(context).Factory();

    Register<Media::Animation::DoubleAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::DoubleKeyFrame>("KeyFrames", ContentKind::Collection, &AddDoubleKeyFrame, &ClearDoubleKeyFrames)
        .Factory();

    Register<Media::Animation::PointKeyFrame>(context, TypeFlags::Abstract)
        .Property("Value", &Media::Animation::PointKeyFrame::GetValue, &Media::Animation::PointKeyFrame::SetValue);
    Register<Media::Animation::LinearPointKeyFrame>(context).Factory();
    Register<Media::Animation::DiscretePointKeyFrame>(context).Factory();
    Register<Media::Animation::EasingPointKeyFrame>(context).Factory();
    Register<Media::Animation::SplinePointKeyFrame>(context).Factory();

    Register<Media::Animation::PointAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::PointKeyFrame>("KeyFrames", ContentKind::Collection, &AddPointKeyFrame, &ClearPointKeyFrames)
        .Factory();

    Register<Media::Animation::ThicknessKeyFrame>(context, TypeFlags::Abstract)
        .Property<Thickness, &Media::Animation::ThicknessKeyFrame::GetValue, &Media::Animation::ThicknessKeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearThicknessKeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteThicknessKeyFrame>(context).Factory();
    Register<Media::Animation::EasingThicknessKeyFrame>(context).Factory();
    Register<Media::Animation::SplineThicknessKeyFrame>(context).Factory();

    Register<Media::Animation::ThicknessAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::ThicknessKeyFrame>("KeyFrames", ContentKind::Collection, &AddThicknessKeyFrame, &ClearThicknessKeyFrames)
        .Factory();

    Register<Media::Animation::ColorKeyFrame>(context, TypeFlags::Abstract)
        .Property<Base::Color, &Media::Animation::ColorKeyFrame::GetValue, &Media::Animation::ColorKeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearColorKeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteColorKeyFrame>(context).Factory();
    Register<Media::Animation::EasingColorKeyFrame>(context).Factory();
    Register<Media::Animation::SplineColorKeyFrame>(context).Factory();

    Register<Media::Animation::ColorAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::ColorKeyFrame>("KeyFrames", ContentKind::Collection, &AddColorKeyFrame, &ClearColorKeyFrames)
        .Factory();

    Register<Media::Animation::ObjectKeyFrame>(context, TypeFlags::Abstract)
        .Property<Value, &Media::Animation::ObjectKeyFrame::GetValue, &Media::Animation::ObjectKeyFrame::SetValue>("Value", PropertyFlags::AnyValue);
    Register<Media::Animation::DiscreteObjectKeyFrame>(context).Factory();

    Register<Media::Animation::ObjectAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::ObjectKeyFrame>("KeyFrames", ContentKind::Collection, &AddObjectKeyFrame, &ClearObjectKeyFrames)
        .Factory();

    Register<Media::Animation::BooleanKeyFrame>(context, TypeFlags::Abstract)
        .Property<bool, &Media::Animation::BooleanKeyFrame::GetValue, &Media::Animation::BooleanKeyFrame::SetValue>("Value");
    Register<Media::Animation::DiscreteBooleanKeyFrame>(context).Factory();

    Register<Media::Animation::BooleanAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::BooleanKeyFrame>("KeyFrames", ContentKind::Collection, &AddBooleanKeyFrame, &ClearBooleanKeyFrames)
        .Factory();

    Register<Media::Animation::Int16KeyFrame>(context, TypeFlags::Abstract)
        .Property<std::int16_t, &Media::Animation::Int16KeyFrame::GetValue, &Media::Animation::Int16KeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearInt16KeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteInt16KeyFrame>(context).Factory();
    Register<Media::Animation::EasingInt16KeyFrame>(context).Factory();
    Register<Media::Animation::SplineInt16KeyFrame>(context).Factory();
    Register<Media::Animation::Int16AnimationUsingKeyFrames>(context)
        .Content<Media::Animation::Int16KeyFrame>("KeyFrames", ContentKind::Collection, &AddInt16KeyFrame, &ClearInt16KeyFrames)
        .Factory();

    Register<Media::Animation::Int32KeyFrame>(context, TypeFlags::Abstract)
        .Property<std::int32_t, &Media::Animation::Int32KeyFrame::GetValue, &Media::Animation::Int32KeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearInt32KeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteInt32KeyFrame>(context).Factory();
    Register<Media::Animation::EasingInt32KeyFrame>(context).Factory();
    Register<Media::Animation::SplineInt32KeyFrame>(context).Factory();
    Register<Media::Animation::Int32AnimationUsingKeyFrames>(context)
        .Content<Media::Animation::Int32KeyFrame>("KeyFrames", ContentKind::Collection, &AddInt32KeyFrame, &ClearInt32KeyFrames)
        .Factory();

    Register<Media::Animation::Int64KeyFrame>(context, TypeFlags::Abstract)
        .Property<std::int64_t, &Media::Animation::Int64KeyFrame::GetValue, &Media::Animation::Int64KeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearInt64KeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteInt64KeyFrame>(context).Factory();
    Register<Media::Animation::EasingInt64KeyFrame>(context).Factory();
    Register<Media::Animation::SplineInt64KeyFrame>(context).Factory();
    Register<Media::Animation::Int64AnimationUsingKeyFrames>(context)
        .Content<Media::Animation::Int64KeyFrame>("KeyFrames", ContentKind::Collection, &AddInt64KeyFrame, &ClearInt64KeyFrames)
        .Factory();

    Register<Media::Animation::SizeKeyFrame>(context, TypeFlags::Abstract)
        .Property<Base::Size, &Media::Animation::SizeKeyFrame::GetValue, &Media::Animation::SizeKeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearSizeKeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteSizeKeyFrame>(context).Factory();
    Register<Media::Animation::EasingSizeKeyFrame>(context).Factory();
    Register<Media::Animation::SplineSizeKeyFrame>(context).Factory();
    Register<Media::Animation::SizeAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::SizeKeyFrame>("KeyFrames", ContentKind::Collection, &AddSizeKeyFrame, &ClearSizeKeyFrames)
        .Factory();

    Register<Media::Animation::MatrixKeyFrame>(context, TypeFlags::Abstract)
        .Property<Base::Transform2D, &Media::Animation::MatrixKeyFrame::GetValue, &Media::Animation::MatrixKeyFrame::SetValue>("Value");
    Register<Media::Animation::LinearMatrixKeyFrame>(context).Factory();
    Register<Media::Animation::DiscreteMatrixKeyFrame>(context).Factory();
    Register<Media::Animation::EasingMatrixKeyFrame>(context).Factory();
    Register<Media::Animation::SplineMatrixKeyFrame>(context).Factory();
    Register<Media::Animation::MatrixAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::MatrixKeyFrame>("KeyFrames", ContentKind::Collection, &AddMatrixKeyFrame, &ClearMatrixKeyFrames)
        .Factory();

    Register<Media::Animation::StringKeyFrame>(context, TypeFlags::Abstract)
        .Property<Base::String, &Media::Animation::StringKeyFrame::GetValue, &Media::Animation::StringKeyFrame::SetValue>("Value");
    Register<Media::Animation::DiscreteStringKeyFrame>(context).Factory();
    Register<Media::Animation::StringAnimationUsingKeyFrames>(context)
        .Content<Media::Animation::StringKeyFrame>("KeyFrames", ContentKind::Collection, &AddStringKeyFrame, &ClearStringKeyFrames)
        .Factory();

    Register<Aero::Interactivity::TriggerAction>(context, TypeFlags::Abstract);

    Register<KeyBinding>(context)
        .Property("Command", &KeyBinding::GetCommandName, &KeyBinding::SetCommandName)
        .Property("Key", &KeyBinding::GetKeyName, &KeyBinding::SetKeyName)
        .Property("Modifiers", &KeyBinding::GetModifiersName, &KeyBinding::SetModifiersName)
        .Factory();

    Register<MouseBinding>(context)
        .Property("Command", &MouseBinding::GetCommandName, &MouseBinding::SetCommandName)
        .Factory();

    Register<Aero::Interactivity::ChangePropertyAction>(context)
        .Property("TargetName", &Aero::Interactivity::ChangePropertyAction::GetTargetName, &Aero::Interactivity::ChangePropertyAction::SetTargetName)
        .Property<Base::Ref<Data::Binding>, &Aero::Interactivity::ChangePropertyAction::GetTargetObject, &Aero::Interactivity::ChangePropertyAction::SetTargetObject>("TargetObject", PropertyFlags::Structural)
        .Property("PropertyName", &Aero::Interactivity::ChangePropertyAction::GetPropertyName, &Aero::Interactivity::ChangePropertyAction::SetPropertyName)
        .Property<Meta::PropertyValue, &Aero::Interactivity::ChangePropertyAction::GetValue, &Aero::Interactivity::ChangePropertyAction::SetValue>("Value", PropertyFlags::AnyValue)
        .Factory();

    Register<Aero::Interactivity::SetFocusAction>(context)
        .Property("TargetName", &Aero::Interactivity::SetFocusAction::GetTargetName, &Aero::Interactivity::SetFocusAction::SetTargetName)
        .Property<Base::Ref<Data::Binding>, &Aero::Interactivity::SetFocusAction::GetTargetObject, &Aero::Interactivity::SetFocusAction::SetTargetObject>("TargetObject", PropertyFlags::Structural)
        .Property("Engage", &Aero::Interactivity::SetFocusAction::GetEngage, &Aero::Interactivity::SetFocusAction::SetEngage)
        .Factory();

    Register<Aero::Interactivity::LaunchUriOrFileAction>(context)
        .Property("Path", &Aero::Interactivity::LaunchUriOrFileAction::GetPath, &Aero::Interactivity::LaunchUriOrFileAction::SetPath)
        .Factory();

    Register<Aero::Interactivity::RemoveElementAction>(context)
        .Property<Base::Ref<Data::Binding>, &Aero::Interactivity::RemoveElementAction::GetTargetObject, &Aero::Interactivity::RemoveElementAction::SetTargetObject>("TargetObject", PropertyFlags::Structural)
        .Factory();

    Register<Media::Animation::ControllableStoryboardAction>(context, TypeFlags::Abstract)
        .Property("BeginStoryboardName", &Media::Animation::ControllableStoryboardAction::GetBeginStoryboardName, &Media::Animation::ControllableStoryboardAction::SetBeginStoryboardName);

    Register<Media::Animation::BeginStoryboard>(context)
        .Property("Name", &Media::Animation::BeginStoryboard::GetName, &Media::Animation::BeginStoryboard::SetName)
        .Content<Media::Animation::Storyboard>("Storyboard", ContentKind::Single, &SetBeginStoryboardContent, &ClearBeginStoryboardContent)
        .Factory();

    Register<Media::Animation::ControlStoryboardAction>(context)
        .Property("Storyboard", &Media::Animation::ControlStoryboardAction::GetStoryboard, &Media::Animation::ControlStoryboardAction::SetStoryboard)
        .Property("ControlStoryboardOption", &Media::Animation::ControlStoryboardAction::GetControlOption, &Media::Animation::ControlStoryboardAction::SetControlOption)
        .Factory();

    Register<Media::Animation::PauseStoryboard>(context).Factory();
    Register<Media::Animation::ResumeStoryboard>(context).Factory();
    Register<Media::Animation::StopStoryboard>(context).Factory();
    Register<Media::Animation::RemoveStoryboard>(context).Factory();
    Register<Media::Animation::SeekStoryboard>(context)
        .Property("Offset", &Media::Animation::SeekStoryboard::GetOffset, &Media::Animation::SeekStoryboard::SetOffset)
        .Factory();

    Register<Media::Animation::EventTrigger>(context)
        .Property("RoutedEvent", &Media::Animation::EventTrigger::GetRoutedEvent, &Media::Animation::EventTrigger::SetRoutedEvent)
        .Property("EventName", &Media::Animation::EventTrigger::GetEventName, &Media::Animation::EventTrigger::SetEventName)
        .Property("SourceName", &Media::Animation::EventTrigger::GetSourceName, &Media::Animation::EventTrigger::SetSourceName)
        .Content<Aero::Interactivity::TriggerAction>("Actions", ContentKind::Collection, &AddEventTriggerAction, &ClearEventTriggerActions)
        .Factory();

    Register<Media::Animation::TimerTrigger>(context)
        .Property("TotalTicks", &Media::Animation::TimerTrigger::GetTotalTicks, &Media::Animation::TimerTrigger::SetTotalTicks)
        .Property<Meta::PropertyValue, &Media::Animation::TimerTrigger::GetMillisecondsPerTick, &Media::Animation::TimerTrigger::SetMillisecondsPerTick>("MillisecondsPerTick", PropertyFlags::AnyValue)
        .Factory();

    Register<Aero::Interactivity::PropertyChangedTrigger>(context)
        .Property<Base::Ref<Data::Binding>, &Aero::Interactivity::PropertyChangedTrigger::GetBinding, &Aero::Interactivity::PropertyChangedTrigger::SetBinding>("Binding")
        .Content<Aero::Interactivity::TriggerAction>("Actions", ContentKind::Collection, &AddPropertyChangedTriggerAction, &ClearPropertyChangedTriggerActions)
        .Factory();

    Register<Aero::Interactivity::KeyTrigger>(context)
        .Property("Key", &Aero::Interactivity::KeyTrigger::GetKey, &Aero::Interactivity::KeyTrigger::SetKey)
        .Property("ActiveOnFocus", &Aero::Interactivity::KeyTrigger::GetActiveOnFocus, &Aero::Interactivity::KeyTrigger::SetActiveOnFocus)
        .Content<Aero::Interactivity::TriggerAction>("Actions", ContentKind::Collection, &AddKeyTriggerAction, &ClearKeyTriggerActions)
        .Factory();

    Register<Aero::Interactivity::InvokeCommandAction>(context)
        .Property("Command", &Aero::Interactivity::InvokeCommandAction::GetCommand, &Aero::Interactivity::InvokeCommandAction::SetCommand)
        .Property<Meta::PropertyValue, &Aero::Interactivity::InvokeCommandAction::GetCommandParameter, &Aero::Interactivity::InvokeCommandAction::SetCommandParameter>("CommandParameter", PropertyFlags::AnyValue)
        .Factory();

    Register<Aero::Interactivity::SelectAction>(context)
        .Factory();
    Register<Aero::Interactivity::SelectAllAction>(context)
        .Factory();

    Register<Aero::Interactivity::PlaySoundAction>(context)
        .Property("Source", &Aero::Interactivity::PlaySoundAction::GetSource, &Aero::Interactivity::PlaySoundAction::SetSource)
        .Property("Volume", &Aero::Interactivity::PlaySoundAction::GetVolume, &Aero::Interactivity::PlaySoundAction::SetVolume)
        .Property(Aero::Interactivity::PlaySoundAction::IsEnabledProperty, true)
        .Factory();

    Register<Media::Animation::PlayMediaAction>(context)
        .Property("TargetName", &Media::Animation::PlayMediaAction::GetTargetName, &Media::Animation::PlayMediaAction::SetTargetName)
        .Factory();

    Register<Media::Animation::PauseMediaAction>(context)
        .Property("TargetName", &Media::Animation::PauseMediaAction::GetTargetName, &Media::Animation::PauseMediaAction::SetTargetName)
        .Factory();

    Register<Media::Animation::StopMediaAction>(context)
        .Property("TargetName", &Media::Animation::StopMediaAction::GetTargetName, &Media::Animation::StopMediaAction::SetTargetName)
        .Factory();

    Register<Aero::Interactivity::ComparisonCondition>(context)
        .Property<Base::Ref<Data::Binding>, &Aero::Interactivity::ComparisonCondition::GetLeftOperand, &Aero::Interactivity::ComparisonCondition::SetLeftOperand>("LeftOperand")
        .Property<Meta::PropertyValue, &Aero::Interactivity::ComparisonCondition::GetRightOperand, &Aero::Interactivity::ComparisonCondition::SetRightOperand>("RightOperand", PropertyFlags::AnyValue)
        .Property("Operator", &Aero::Interactivity::ComparisonCondition::GetComparisonOperator, &Aero::Interactivity::ComparisonCondition::SetComparisonOperator)
        .Factory();

    Register<Aero::Interactivity::ConditionalExpression>(context)
        .Property("ForwardChaining", &Aero::Interactivity::ConditionalExpression::GetChaining, &Aero::Interactivity::ConditionalExpression::SetChaining)
        .Content<Aero::Interactivity::ComparisonCondition>("Conditions", ContentKind::Collection, &AddConditionalComparison, &ClearConditionalComparisons)
        .Factory();

    Register<Aero::Interactivity::ConditionBehavior>(context)
        .Content<Aero::Interactivity::ConditionalExpression>("Expression", ContentKind::Single, &SetConditionBehaviorExpression, &ClearConditionBehaviorExpression)
        .Factory();

    Register<Media::Animation::StoryboardCompletedTrigger>(context)
        .Property("Storyboard", &Media::Animation::StoryboardCompletedTrigger::GetStoryboard, &Media::Animation::StoryboardCompletedTrigger::SetStoryboard)
        .Content<Aero::Interactivity::TriggerAction>("Actions", ContentKind::Collection, &AddStoryboardCompletedTriggerAction, &ClearStoryboardCompletedTriggerActions)
        .Factory();

    Register<Interactivity::Behavior>(context, TypeFlags::Abstract);

    Register<Interactivity::MouseDragElementBehavior>(context)
        .Property(Interactivity::MouseDragElementBehavior::XProperty, FrameworkPropertyMetadata(0.0) .Changed(&Interactivity::MouseDragElementBehavior::OnPositionChanged))
        .Property(Interactivity::MouseDragElementBehavior::YProperty, FrameworkPropertyMetadata(0.0) .Changed(&Interactivity::MouseDragElementBehavior::OnPositionChanged))
        .Property(Interactivity::MouseDragElementBehavior::ConstrainToParentBoundsProperty, false)
        .Factory();

    Register<Interactivity::BackgroundEffectBehavior>(context)
        .Property(Interactivity::BackgroundEffectBehavior::SourceProperty, FrameworkPropertyMetadata(Base::Ref<Base::Object>{}) .Changed(&Interactivity::BackgroundEffectBehavior::OnBehaviorPropertyChanged))
        .Property(Interactivity::BackgroundEffectBehavior::EffectProperty, FrameworkPropertyMetadata(Base::Ref<Media::Effect>{}) .Changed(&Interactivity::BackgroundEffectBehavior::OnBehaviorPropertyChanged))
        .Content<Media::Effect>("Content", ContentKind::Single, &SetBackgroundEffectBehaviorEffect, &ClearBackgroundEffectBehaviorEffect)
        .Factory();

    Register<Interactivity::StyleBehaviorCollection>(context)
        .Content<Base::Object>("Items", ContentKind::Collection, &AddStyleBehaviorItem, &ClearStyleBehaviorItems)
        .Factory();

    Register<Interactivity::StyleTriggerCollection>(context)
        .Content<Base::Object>("Items", ContentKind::Collection, &AddStyleTriggerItem, &ClearStyleTriggerItems)
        .Factory();

    Register<Interactivity::StyleInteraction>(context, TypeFlags::Abstract)
        .Property(Interactivity::StyleInteraction::BehaviorsProperty, FrameworkPropertyMetadata(Base::Ref<Interactivity::StyleBehaviorCollection>{}) .Changed(&Interactivity::StyleInteraction::OnBehaviorsChanged))
        .Property(Interactivity::StyleInteraction::TriggersProperty, FrameworkPropertyMetadata(Base::Ref<Interactivity::StyleTriggerCollection>{}) .Changed(&Interactivity::StyleInteraction::OnTriggersChanged));

    Register<Interactivity::Interaction>(context, TypeFlags::Abstract)
        .Collection<Base::Object>("Triggers", &AddInteractionTrigger, &ClearInteractionTriggers, PropertyFlags::Attached | PropertyFlags::Structural)
        .Collection<Base::Object>("Behaviors", &AddInteractionBehavior, &ClearInteractionBehaviors, PropertyFlags::Attached | PropertyFlags::Structural);
    return {};
}
