#include <Aero/Interactivity/Conditions.hpp>
#include <Aero/Interactivity/Interaction.hpp>
#include <Aero/Interactivity/TriggerAction.hpp>
// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiAnimation(
    ::Aero::Meta::Registration& context) noexcept {
    using namespace Media::Animation;
    using namespace Interactivity;
    // Prefer public Animation types over Model::* (AnimationEngine.hpp).
    using Media::Animation::ColorAnimation;
    using Media::Animation::ColorKeyFrame;
    using Media::Animation::DoubleAnimation;
    using Media::Animation::DoubleKeyFrame;
    using Media::Animation::MatrixAnimation;
    using Media::Animation::MatrixKeyFrame;
    using Media::Animation::PointAnimation;
    using Media::Animation::PointKeyFrame;
    using Media::Animation::RectAnimation;
    using Media::Animation::RepeatBehavior;
    using Media::Animation::SizeAnimation;
    using Media::Animation::SizeKeyFrame;
    using Media::Animation::ThicknessAnimation;
    using Media::Animation::ThicknessKeyFrame;
    // Prefer geometry typedefs over BrushRendering/AnimationModel conversion fns in Animation.
    using ::Aero::Base::Color;
    using ::Aero::Base::Point;
    using ::Aero::Base::Rect;
    using ::Aero::Base::Size;
    using ::Aero::Base::Thickness;

    Register<Duration>(context)
        .ValueSemantics()
        .TextConverter<&Duration::TryParse>();

    Register<TimeSpan>(context)
        .ValueSemantics()
        .TextConverter<&TimeSpan::TryParse>();

    Register<RepeatBehavior>(context)
        .ValueSemantics()
        .TextConverter<&RepeatBehavior::TryParse>();

    Register<KeyTime>(context)
        .ValueSemantics()
        .TextConverter<&KeyTime::TryParse>();

    Register<Timeline>(context, TypeFlags::Abstract)
        .Property(Timeline::BeginTimeProperty, TimeSpan::Zero())
        .Property(Timeline::DurationProperty, Duration::Automatic())
        .Property(Timeline::RepeatBehaviorProperty, RepeatBehavior::Once())
        .Property(Timeline::SpeedRatioProperty, 1.0)
        .Property(Timeline::AutoReverseProperty, false)
        .Property(Timeline::FillBehaviorProperty, FillBehavior::HoldEnd);

    Register<AnimationTimeline>(context, TypeFlags::Abstract);
    Register<TimelineGroup>(context, TypeFlags::Abstract);

    Register<ParallelTimeline>(context)
        .Content<Timeline>("Children", ContentKind::Collection, &AddStoryboardTimeline, &ClearStoryboardTimelines)
        .Factory();

    Register<Storyboard>(context)
        .Property(Storyboard::TargetNameProperty, Base::String{})
        .Property(Storyboard::TargetPropertyProperty, Base::String{})
        .Content<Timeline>("Children", ContentKind::Collection, &AddStoryboardTimeline, &ClearStoryboardTimelines)
        .Factory();

    Register<EasingFunctionBase>(context, TypeFlags::Abstract)
        .Property(EasingFunctionBase::EasingModeProperty, EasingMode::EaseOut)
        .Property(EasingFunctionBase::ExponentProperty, 2.0)
        .Property(EasingFunctionBase::PowerProperty, 2.0)
        .Property(EasingFunctionBase::AmplitudeProperty, 1.0)
        .Property(EasingFunctionBase::BouncesProperty, 3.0)
        .Property(EasingFunctionBase::BouncinessProperty, 3.0)
        .Property(EasingFunctionBase::OscillationsProperty, 3.0)
        .Property(EasingFunctionBase::SpringinessProperty, 3.0);

#define AERO_EASE_FACTORY(name, kind) \
    +[]() noexcept -> Base::Result<Base::Ref<Base::Object>> { \
        auto created = Base::MakeRef<EasingFunctionBase>( \
            ::Aero::Meta::MakeTypeId(::Aero::Meta::AeroNamespaceUri(), #name), \
            EasingFunctionBase::Kind::kind); \
        if (!created) return created.GetStatus(); \
        return Base::Ref<Base::Object>(std::move(created).Value()); \
    }
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "SineEase"),
        AERO_EASE_FACTORY(SineEase, Sine));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "QuadraticEase"),
        AERO_EASE_FACTORY(QuadraticEase, Quadratic));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "CubicEase"),
        AERO_EASE_FACTORY(CubicEase, Cubic));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "QuarticEase"),
        AERO_EASE_FACTORY(QuarticEase, Quartic));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "QuinticEase"),
        AERO_EASE_FACTORY(QuinticEase, Quintic));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "CircleEase"),
        AERO_EASE_FACTORY(CircleEase, Circle));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "ExponentialEase"),
        AERO_EASE_FACTORY(ExponentialEase, Exponential));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "PowerEase"),
        AERO_EASE_FACTORY(PowerEase, Power));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "BackEase"),
        AERO_EASE_FACTORY(BackEase, Back));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "BounceEase"),
        AERO_EASE_FACTORY(BounceEase, Bounce));
    SetObjectFactory(
        RegisterAlias<EasingFunctionBase>(context, "ElasticEase"),
        AERO_EASE_FACTORY(ElasticEase, Elastic));
#undef AERO_EASE_FACTORY

#define AERO_FROM_TO_BASE(Name, CppType) \
    Register<Name##AnimationBase>(context, TypeFlags::Abstract) \
        .Property<CppType, &Name##AnimationBase::GetFrom, &Name##AnimationBase::SetFrom>("From") \
        .Property<CppType, &Name##AnimationBase::GetTo, &Name##AnimationBase::SetTo>("To");

#define AERO_FROM_TO_ANIMATION(Name, CppType) \
    AERO_FROM_TO_BASE(Name, CppType) \
    Register<Name##Animation>(context) \
        .Property<Base::Ref<EasingFunctionBase>, &Name##Animation::GetEasingFunction, &Name##Animation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural) \
        .Factory();

    AERO_FROM_TO_BASE(Double, double)
    Register<DoubleAnimation>(context)
        .Property<double, &DoubleAnimation::GetAccelerationRatio, &DoubleAnimation::SetAccelerationRatio>("AccelerationRatio")
        .Property<double, &DoubleAnimation::GetDecelerationRatio, &DoubleAnimation::SetDecelerationRatio>("DecelerationRatio")
        .Property<Base::Ref<EasingFunctionBase>, &DoubleAnimation::GetEasingFunction, &DoubleAnimation::SetEasingFunction>("EasingFunction", PropertyFlags::Structural)
        .Factory();
    AERO_FROM_TO_ANIMATION(Color, Color)
    AERO_FROM_TO_ANIMATION(Point, Point)
    AERO_FROM_TO_ANIMATION(Rect, Rect)
    AERO_FROM_TO_ANIMATION(Thickness, Base::Thickness)
    AERO_FROM_TO_ANIMATION(Int16, std::int16_t)
    AERO_FROM_TO_ANIMATION(Int32, std::int32_t)
    AERO_FROM_TO_ANIMATION(Int64, std::int64_t)
    AERO_FROM_TO_ANIMATION(Size, Base::Size)
    AERO_FROM_TO_ANIMATION(Matrix, Base::Transform2D)
#undef AERO_FROM_TO_BASE
#undef AERO_FROM_TO_ANIMATION

#define AERO_KEY_FACTORY(Type, name, interpolation) \
    +[]() noexcept -> Base::Result<Base::Ref<Base::Object>> { \
        auto created = Base::MakeRef<Type>( \
            ::Aero::Meta::MakeTypeId(::Aero::Meta::AeroNamespaceUri(), #name), \
            KeyFrameBase::Interpolation::interpolation); \
        if (!created) return created.GetStatus(); \
        return Base::Ref<Base::Object>(std::move(created).Value()); \
    }
#define AERO_KEYFRAME_ALIAS(Name, Kind) \
    SetObjectFactory( \
        RegisterAlias<Name##KeyFrame>(context, #Kind #Name "KeyFrame"), \
        AERO_KEY_FACTORY(Name##KeyFrame, Kind##Name##KeyFrame, Kind));
#define AERO_KEYFRAME_ALIASES(Name) \
    AERO_KEYFRAME_ALIAS(Name, Linear) \
    AERO_KEYFRAME_ALIAS(Name, Discrete) \
    AERO_KEYFRAME_ALIAS(Name, Easing) \
    AERO_KEYFRAME_ALIAS(Name, Spline)
#define AERO_KEYFRAME_VALUE(Name, CppType) \
    Register<Name##KeyFrame>(context, TypeFlags::Abstract) \
        .Property<CppType, &Name##KeyFrame::GetValue, &Name##KeyFrame::SetValue>("Value");
#define AERO_KEYFRAME_COLLECTION(Name) \
    Register<Name##AnimationUsingKeyFrames>(context) \
        .Content<Name##KeyFrame>("KeyFrames", ContentKind::Collection, &Add##Name##KeyFrame, &Clear##Name##KeyFrames) \
        .Factory();
#define AERO_KEYFRAMES(Name, CppType) \
    AERO_KEYFRAME_VALUE(Name, CppType) \
    AERO_KEYFRAME_ALIASES(Name) \
    AERO_KEYFRAME_COLLECTION(Name)
#define AERO_DISCRETE_KEYFRAMES(Name, CppType) \
    AERO_KEYFRAME_VALUE(Name, CppType) \
    AERO_KEYFRAME_ALIAS(Name, Discrete) \
    AERO_KEYFRAME_COLLECTION(Name)
    Register<KeyFrameBase>(context, TypeFlags::Abstract)
        .Property(KeyFrameBase::KeyTimeProperty, KeyTime{})
        .Property(KeyFrameBase::EasingFunctionProperty, Base::Ref<EasingFunctionBase>{}, AffectsRender)
        .Property(KeyFrameBase::KeySplineProperty, FrameworkPropertyMetadata(Base::String{}) .Changed(&KeyFrameBase::OnKeySplineChanged));

    AERO_KEYFRAMES(Double, double)
    AERO_KEYFRAMES(Point, Point)
    AERO_KEYFRAMES(Thickness, Thickness)
    AERO_KEYFRAMES(Color, Base::Color)
    AERO_KEYFRAMES(Int16, std::int16_t)
    AERO_KEYFRAMES(Int32, std::int32_t)
    AERO_KEYFRAMES(Int64, std::int64_t)
    AERO_KEYFRAMES(Size, Base::Size)
    AERO_KEYFRAMES(Matrix, Base::Transform2D)

    Register<ObjectKeyFrame>(context, TypeFlags::Abstract)
        .Property<Value, &ObjectKeyFrame::GetValue, &ObjectKeyFrame::SetValue>("Value", PropertyFlags::AnyValue);
    AERO_KEYFRAME_ALIAS(Object, Discrete)
    AERO_KEYFRAME_COLLECTION(Object)

    AERO_DISCRETE_KEYFRAMES(Boolean, bool)
    AERO_DISCRETE_KEYFRAMES(String, Base::String)
#undef AERO_KEYFRAME_ALIAS
#undef AERO_KEYFRAME_ALIASES
#undef AERO_KEYFRAME_VALUE
#undef AERO_KEYFRAME_COLLECTION
#undef AERO_KEYFRAMES
#undef AERO_DISCRETE_KEYFRAMES

    Register<TriggerAction>(context, TypeFlags::Abstract);

    Register<KeyBinding>(context)
        .Property("Command", &KeyBinding::GetCommandName, &KeyBinding::SetCommandName)
        .Property("Key", &KeyBinding::GetKeyName, &KeyBinding::SetKeyName)
        .Property("Modifiers", &KeyBinding::GetModifiersName, &KeyBinding::SetModifiersName)
        .Factory();

    Register<MouseBinding>(context)
        .Property("Command", &MouseBinding::GetCommandName, &MouseBinding::SetCommandName)
        .Factory();

    Register<ChangePropertyAction>(context)
        .Property("TargetName", &ChangePropertyAction::GetTargetName, &ChangePropertyAction::SetTargetName)
        .Property<Base::Ref<Data::Binding>, &ChangePropertyAction::GetTargetObject, &ChangePropertyAction::SetTargetObject>("TargetObject", PropertyFlags::Structural)
        .Property("PropertyName", &ChangePropertyAction::GetPropertyName, &ChangePropertyAction::SetPropertyName)
        .Property<Meta::PropertyValue, &ChangePropertyAction::GetValue, &ChangePropertyAction::SetValue>("Value", PropertyFlags::AnyValue)
        .Factory();

    Register<SetFocusAction>(context)
        .Property("TargetName", &SetFocusAction::GetTargetName, &SetFocusAction::SetTargetName)
        .Property<Base::Ref<Data::Binding>, &SetFocusAction::GetTargetObject, &SetFocusAction::SetTargetObject>("TargetObject", PropertyFlags::Structural)
        .Property("Engage", &SetFocusAction::GetEngage, &SetFocusAction::SetEngage)
        .Factory();

    Register<LaunchUriOrFileAction>(context)
        .Property("Path", &LaunchUriOrFileAction::GetPath, &LaunchUriOrFileAction::SetPath)
        .Factory();

    Register<RemoveElementAction>(context)
        .Property<Base::Ref<Data::Binding>, &RemoveElementAction::GetTargetObject, &RemoveElementAction::SetTargetObject>("TargetObject", PropertyFlags::Structural)
        .Factory();

    Register<ControllableStoryboardAction>(context, TypeFlags::Abstract)
        .Property("BeginStoryboardName", &ControllableStoryboardAction::GetBeginStoryboardName, &ControllableStoryboardAction::SetBeginStoryboardName);

    Register<BeginStoryboard>(context)
        .Property("Name", &BeginStoryboard::GetName, &BeginStoryboard::SetName)
        .Content<Storyboard>("Storyboard", ContentKind::Single, &SetBeginStoryboardContent, &ClearBeginStoryboardContent)
        .Factory();

    Register<ControlStoryboardAction>(context)
        .Property("Storyboard", &ControlStoryboardAction::GetStoryboard, &ControlStoryboardAction::SetStoryboard)
        .Property("ControlStoryboardOption", &ControlStoryboardAction::GetControlOption, &ControlStoryboardAction::SetControlOption)
        .Factory();

    Register<PauseStoryboard>(context).Factory();
    Register<ResumeStoryboard>(context).Factory();
    Register<StopStoryboard>(context).Factory();
    Register<RemoveStoryboard>(context).Factory();
    Register<SeekStoryboard>(context)
        .Property("Offset", &SeekStoryboard::GetOffset, &SeekStoryboard::SetOffset)
        .Factory();

    Register<EventTrigger>(context)
        .Property("RoutedEvent", &EventTrigger::GetRoutedEvent, &EventTrigger::SetRoutedEvent)
        .Property("EventName", &EventTrigger::GetEventName, &EventTrigger::SetEventName)
        .Property("SourceName", &EventTrigger::GetSourceName, &EventTrigger::SetSourceName)
        .Content<TriggerAction>("Actions", ContentKind::Collection, &AddEventTriggerAction, &ClearEventTriggerActions)
        .Factory();

    Register<TimerTrigger>(context)
        .Property("TotalTicks", &TimerTrigger::GetTotalTicks, &TimerTrigger::SetTotalTicks)
        .Property<Meta::PropertyValue, &TimerTrigger::GetMillisecondsPerTick, &TimerTrigger::SetMillisecondsPerTick>("MillisecondsPerTick", PropertyFlags::AnyValue)
        .Factory();

    Register<PropertyChangedTrigger>(context)
        .Property<Base::Ref<Data::Binding>, &PropertyChangedTrigger::GetBinding, &PropertyChangedTrigger::SetBinding>("Binding")
        .Content<TriggerAction>("Actions", ContentKind::Collection, &AddPropertyChangedTriggerAction, &ClearPropertyChangedTriggerActions)
        .Factory();

    Register<KeyTrigger>(context)
        .Property("Key", &KeyTrigger::GetKey, &KeyTrigger::SetKey)
        .Property("ActiveOnFocus", &KeyTrigger::GetActiveOnFocus, &KeyTrigger::SetActiveOnFocus)
        .Content<TriggerAction>("Actions", ContentKind::Collection, &AddKeyTriggerAction, &ClearKeyTriggerActions)
        .Factory();

    Register<InvokeCommandAction>(context)
        .Property("Command", &InvokeCommandAction::GetCommand, &InvokeCommandAction::SetCommand)
        .Property<Meta::PropertyValue, &InvokeCommandAction::GetCommandParameter, &InvokeCommandAction::SetCommandParameter>("CommandParameter", PropertyFlags::AnyValue)
        .Factory();

    Register<SelectAction>(context)
        .Factory();
    Register<SelectAllAction>(context)
        .Factory();

    Register<PlaySoundAction>(context)
        .Property("Source", &PlaySoundAction::GetSource, &PlaySoundAction::SetSource)
        .Property("Volume", &PlaySoundAction::GetVolume, &PlaySoundAction::SetVolume)
        .Property(PlaySoundAction::IsEnabledProperty, true)
        .Factory();

    Register<PlayMediaAction>(context)
        .Property("TargetName", &PlayMediaAction::GetTargetName, &PlayMediaAction::SetTargetName)
        .Factory();

    Register<PauseMediaAction>(context)
        .Property("TargetName", &PauseMediaAction::GetTargetName, &PauseMediaAction::SetTargetName)
        .Factory();

    Register<StopMediaAction>(context)
        .Property("TargetName", &StopMediaAction::GetTargetName, &StopMediaAction::SetTargetName)
        .Factory();

    Register<ComparisonCondition>(context)
        .Property<Base::Ref<Data::Binding>, &ComparisonCondition::GetLeftOperand, &ComparisonCondition::SetLeftOperand>("LeftOperand")
        .Property<Meta::PropertyValue, &ComparisonCondition::GetRightOperand, &ComparisonCondition::SetRightOperand>("RightOperand", PropertyFlags::AnyValue)
        .Property("Operator", &ComparisonCondition::GetComparisonOperator, &ComparisonCondition::SetComparisonOperator)
        .Factory();

    Register<ConditionalExpression>(context)
        .Property("ForwardChaining", &ConditionalExpression::GetChaining, &ConditionalExpression::SetChaining)
        .Content<ComparisonCondition>("Conditions", ContentKind::Collection, &AddConditionalComparison, &ClearConditionalComparisons)
        .Factory();

    Register<ConditionBehavior>(context)
        .Content<ConditionalExpression>("Expression", ContentKind::Single, &SetConditionBehaviorExpression, &ClearConditionBehaviorExpression)
        .Factory();

    Register<StoryboardCompletedTrigger>(context)
        .Property("Storyboard", &StoryboardCompletedTrigger::GetStoryboard, &StoryboardCompletedTrigger::SetStoryboard)
        .Content<TriggerAction>("Actions", ContentKind::Collection, &AddStoryboardCompletedTriggerAction, &ClearStoryboardCompletedTriggerActions)
        .Factory();

    Register<Behavior>(context, TypeFlags::Abstract);

    Register<MouseDragElementBehavior>(context)
        .Property(MouseDragElementBehavior::XProperty, FrameworkPropertyMetadata(0.0) .Changed(&MouseDragElementBehavior::OnPositionChanged))
        .Property(MouseDragElementBehavior::YProperty, FrameworkPropertyMetadata(0.0) .Changed(&MouseDragElementBehavior::OnPositionChanged))
        .Property(MouseDragElementBehavior::ConstrainToParentBoundsProperty, false)
        .Factory();

    Register<BackgroundEffectBehavior>(context)
        .Property(BackgroundEffectBehavior::SourceProperty, FrameworkPropertyMetadata(Base::Ref<Base::Object>{}) .Changed(&BackgroundEffectBehavior::OnBehaviorPropertyChanged))
        .Property(BackgroundEffectBehavior::EffectProperty, FrameworkPropertyMetadata(Base::Ref<Media::Effect>{}) .Changed(&BackgroundEffectBehavior::OnBehaviorPropertyChanged))
        .Content<Media::Effect>("Content", ContentKind::Single, &SetBackgroundEffectBehaviorEffect, &ClearBackgroundEffectBehaviorEffect)
        .Factory();

    Register<StyleBehaviorCollection>(context)
        .Content<Base::Object>("Items", ContentKind::Collection, &AddStyleBehaviorItem, &ClearStyleBehaviorItems)
        .Factory();

    Register<StyleTriggerCollection>(context)
        .Content<Base::Object>("Items", ContentKind::Collection, &AddStyleTriggerItem, &ClearStyleTriggerItems)
        .Factory();

    Register<StyleInteraction>(context, TypeFlags::Abstract)
        .Property(StyleInteraction::BehaviorsProperty, FrameworkPropertyMetadata(Base::Ref<StyleBehaviorCollection>{}) .Changed(&StyleInteraction::OnBehaviorsChanged))
        .Property(StyleInteraction::TriggersProperty, FrameworkPropertyMetadata(Base::Ref<StyleTriggerCollection>{}) .Changed(&StyleInteraction::OnTriggersChanged));

    Register<Interaction>(context, TypeFlags::Abstract)
        .Collection<Base::Object>("Triggers", &AddInteractionTrigger, &ClearInteractionTriggers, PropertyFlags::Attached | PropertyFlags::Structural)
        .Collection<Base::Object>("Behaviors", &AddInteractionBehavior, &ClearInteractionBehaviors, PropertyFlags::Attached | PropertyFlags::Structural);
    return {};
}
#undef AERO_KEY_FACTORY
