// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiInput(
    ::Aero::Meta::Registration& context) noexcept {
    Register<EventArgs>(context);
    Register<RoutedEventArgs>(context);
    Register<InputEventArgs>(context);
    Register<MouseEventArgs>(context);
    Register<MouseButtonEventArgs>(context);
    Register<MouseWheelEventArgs>(context);
    Register<DragEventArgs>(context);
    Register<GiveFeedbackEventArgs>(context);
    Register<DragCompletedEventArgs>(context);
    Register<KeyEventArgs>(context);
    Register<TextCompositionEventArgs>(context);
    Register<KeyboardFocusChangedEventArgs>(context);
    Register<KeyboardNavigation>(context, TypeFlags::Abstract)
        .Property(KeyboardNavigation::DirectionalNavigationProperty, KeyboardNavigationMode::Continue)
        .Property(KeyboardNavigation::TabNavigationProperty, KeyboardNavigationMode::Continue)
        .Property(KeyboardNavigation::ControlTabNavigationProperty, KeyboardNavigationMode::Continue)
        .Property(KeyboardNavigation::TabIndexProperty, std::uint32_t{0})
        .Property(KeyboardNavigation::AcceptsReturnProperty, false)
        .Property(KeyboardNavigation::IsTabStopProperty, false);

    Register<FocusManager>(context, TypeFlags::Abstract)
        .Property(FocusManager::IsFocusScopeProperty, false)
        .Property(FocusManager::FocusedElementProperty, Base::Ref<Base::Object>{});

    Register<CanExecuteRoutedEventArgs>(context);
    Register<ExecutedRoutedEventArgs>(context);

    Register<Cursor>(context);
    return {};
}
