// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiMedia(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    Register<Length>(context)
        .ValueSemantics({sizeof(Length), alignof(Length), nullptr, nullptr, &EqualLength, nullptr, true})
        .TextConverter<&ConvertLength>();

    Register<Thickness>(context)
        .Field<&Thickness::left>("Left")
        .Field<&Thickness::top>("Top")
        .Field<&Thickness::right>("Right")
        .Field<&Thickness::bottom>("Bottom")
        .ValueSemantics({sizeof(Thickness), alignof(Thickness), nullptr, nullptr, &EqualThickness, nullptr, true})
        .TextConverter<&ConvertThickness>();

    Register<CornerRadius>(context)
        .Field<&CornerRadius::topLeft>("TopLeft")
        .Field<&CornerRadius::topRight>("TopRight")
        .Field<&CornerRadius::bottomRight>("BottomRight")
        .Field<&CornerRadius::bottomLeft>("BottomLeft")
        .ValueSemantics({ sizeof(CornerRadius), alignof(CornerRadius), nullptr, nullptr, &EqualCornerRadius, nullptr, true})
        .TextConverter<&ConvertCornerRadius>();

    Register<Color>(context)
        .Field<&Color::red>("Red")
        .Field<&Color::green>("Green")
        .Field<&Color::blue>("Blue")
        .Field<&Color::alpha>("Alpha")
        .ValueSemantics({sizeof(Color), alignof(Color), nullptr, nullptr, &EqualColor, nullptr, true})
        .TextConverter<&ConvertColor>();

    Register<Point>(context)
        .Field<&Point::x>("X")
        .Field<&Point::y>("Y")
        .ValueSemantics()
        .TextConverter<&ConvertPoint>();

    Register<Rect>(context)
        .Field<&Rect::x>("X")
        .Field<&Rect::y>("Y")
        .Field<&Rect::width>("Width")
        .Field<&Rect::height>("Height")
        .ValueSemantics()
        .TextConverter<&ConvertRect>();

    Register<Base::Size>(context)
        .Field<&Base::Size::width>("Width")
        .Field<&Base::Size::height>("Height")
        .ValueSemantics()
        .TextConverter<&ConvertSize>();

    // Brush.RelativeTransform is a Transform-valued dependency property, so
    // the abstract value type must exist before Brush metadata is authored.
    Register<Transform>(context, TypeFlags::Abstract);

    Register<Brush>(context, TypeFlags::Abstract)
        .Property(Brush::OpacityProperty, FrameworkPropertyMetadata(1.0) .Validate(&ValidateUnitDouble) .AffectsRender())
        .Property(Brush::ShaderProperty, FrameworkPropertyMetadata(Base::Ref<Base::Object>{}) .AffectsRender())
        .Property(Brush::RelativeTransformProperty, FrameworkPropertyMetadata(Base::Ref<Transform>{}) .AffectsRender())
        .TextConverter(&ConvertBrushText);

    Register<SolidColorBrush>(context)
        .Property(SolidColorBrush::ColorProperty, FrameworkPropertyMetadata(Color{}).Structural())
        .Content(MakeMemberId(SolidColorBrush::StaticTypeId(), MemberKind::Property, "Color"))
        .Factory();

    Register<GradientStop>(context)
        .Property(GradientStop::OffsetProperty, FrameworkPropertyMetadata(0.0) .Validate(&ValidateUnitDouble))
        .Property(GradientStop::ColorProperty, FrameworkPropertyMetadata(Color{}))
        .Factory();

    Register<GradientStopCollection>(context)
        .Implements<Collections::IItemsSource>()
        .Content<GradientStop>("Items", ContentKind::Collection, &AddGradientStopCollectionItem, &ClearGradientStopCollectionItems)
        .Factory();

    Register<BrushShader>(context, TypeFlags::Abstract)
        .Factory();

    Register<MonochromeShader>(context)
        .Property(MonochromeShader::ColorProperty, FrameworkPropertyMetadata(Color{}).AffectsRender())
        .Factory();

    Register<ConicGradientShader>(context)
        .Content<GradientStop>("GradientStops", ContentKind::Collection, [](Base::Object& owner, const Base::Ref<Base::Object>& value, void*) noexcept { static_cast<ConicGradientShader&>(owner).AddGradientStop(Base::Ref<GradientStop>::FromBorrowed(static_cast<GradientStop&>(*value))); }, [](Base::Object& owner, void*) noexcept { static_cast<ConicGradientShader&>(owner).ClearGradientStops(); })
        .Factory();

    Register<WavesShader>(context)
        .Property(WavesShader::TimeProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<GradientBrush>(context, TypeFlags::Abstract)
        .Property(GradientBrush::MappingModeProperty, FrameworkPropertyMetadata(BrushMappingMode::RelativeToBoundingBox))
        .Property(GradientBrush::SpreadMethodProperty, FrameworkPropertyMetadata(GradientSpreadMethod::Pad) .AffectsRender())
        .Content<GradientStop>("GradientStops", ContentKind::Collection, &AddGradientStop, &ClearGradientStops);

    Register<LinearGradientBrush>(context)
        .Property(LinearGradientBrush::StartPointProperty, FrameworkPropertyMetadata(Point{0.0, 0.0}))
        .Property(LinearGradientBrush::EndPointProperty, FrameworkPropertyMetadata(Point{1.0, 1.0}))
        .Factory();

    Register<RadialGradientBrush>(context)
        .Property(RadialGradientBrush::CenterProperty, FrameworkPropertyMetadata(Point{0.5, 0.5}))
        .Property(RadialGradientBrush::GradientOriginProperty, FrameworkPropertyMetadata(Point{0.5, 0.5}))
        .Property(RadialGradientBrush::RadiusXProperty, FrameworkPropertyMetadata(0.5) .Validate(&Base::Validate::Positive<double>))
        .Property(RadialGradientBrush::RadiusYProperty, FrameworkPropertyMetadata(0.5) .Validate(&Base::Validate::Positive<double>))
        .Factory();

    Register<ImageSource>(context, TypeFlags::Abstract)
        .TextConverter(&ConvertImageSourceText);

    Register<TileBrush>(context, TypeFlags::Abstract)
        .Property(TileBrush::StretchProperty, FrameworkPropertyMetadata(Stretch::Fill))
        .Property(TileBrush::ViewboxProperty, FrameworkPropertyMetadata(Rect{0.0, 0.0, 1.0, 1.0}))
        .Property(TileBrush::ViewportProperty, FrameworkPropertyMetadata(Rect{0.0, 0.0, 1.0, 1.0}))
        .Property(TileBrush::ViewboxUnitsProperty, FrameworkPropertyMetadata(BrushMappingMode::RelativeToBoundingBox))
        .Property(TileBrush::ViewportUnitsProperty, FrameworkPropertyMetadata(BrushMappingMode::RelativeToBoundingBox))
        .Property(TileBrush::TileModeProperty, FrameworkPropertyMetadata(TileMode::None))
        .Property(TileBrush::AlignmentXProperty, FrameworkPropertyMetadata(HorizontalAlignment::Center))
        .Property(TileBrush::AlignmentYProperty, FrameworkPropertyMetadata(VerticalAlignment::Center));

    Register<BitmapImage>(context)
        .Property(BitmapImage::UriSourceProperty, FrameworkPropertyMetadata(Base::ResourceUri{}))
        .Factory();

    Register<CroppedBitmap>(context)
        .Property(CroppedBitmap::SourceProperty, FrameworkPropertyMetadata(Base::Ref<ImageSource>{}))
        .Property(CroppedBitmap::SourceRectProperty, FrameworkPropertyMetadata(Base::Rect{}))
        .Factory();

    Register<ImageBrush>(context)
        .Property(ImageBrush::ImageSourceProperty, FrameworkPropertyMetadata(Base::Ref<ImageSource>{}))
        .Factory();

    Register<Base::Transform2D>(context)
        .Field<&Base::Transform2D::m11>("M11")
        .Field<&Base::Transform2D::m12>("M12")
        .Field<&Base::Transform2D::m21>("M21")
        .Field<&Base::Transform2D::m22>("M22")
        .Field<&Base::Transform2D::dx>("OffsetX")
        .Field<&Base::Transform2D::dy>("OffsetY")
        .ValueSemantics()
        .TextConverter<&ConvertMatrix>();

    Register<Base::Transform3>(context)
        .Field<&Base::Transform3::m11>("M11")
        .Field<&Base::Transform3::m12>("M12")
        .Field<&Base::Transform3::m13>("M13")
        .Field<&Base::Transform3::m21>("M21")
        .Field<&Base::Transform3::m22>("M22")
        .Field<&Base::Transform3::m23>("M23")
        .Field<&Base::Transform3::m31>("M31")
        .Field<&Base::Transform3::m32>("M32")
        .Field<&Base::Transform3::m33>("M33")
        .Field<&Base::Transform3::dx>("OffsetX")
        .Field<&Base::Transform3::dy>("OffsetY")
        .Field<&Base::Transform3::dz>("OffsetZ")
        .ValueSemantics()
        .TextConverter<&ConvertTransform3>();

    Register<TranslateTransform>(context)
        .Property(TranslateTransform::XProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(TranslateTransform::YProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<ScaleTransform>(context)
        .Property(ScaleTransform::ScaleXProperty, FrameworkPropertyMetadata(1.0).AffectsRender())
        .Property(ScaleTransform::ScaleYProperty, FrameworkPropertyMetadata(1.0).AffectsRender())
        .Property(ScaleTransform::CenterXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(ScaleTransform::CenterYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<RotateTransform>(context)
        .Property(RotateTransform::AngleProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(RotateTransform::CenterXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(RotateTransform::CenterYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<SkewTransform>(context)
        .Property(SkewTransform::AngleXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(SkewTransform::AngleYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(SkewTransform::CenterXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(SkewTransform::CenterYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<MatrixTransform>(context)
        .Property(MatrixTransform::MatrixProperty, FrameworkPropertyMetadata(Base::Transform2D{}).AffectsRender())
        .Factory();

    Register<CompositeTransform>(context)
        .Property(CompositeTransform::CenterXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform::CenterYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform::ScaleXProperty, FrameworkPropertyMetadata(1.0).AffectsRender())
        .Property(CompositeTransform::ScaleYProperty, FrameworkPropertyMetadata(1.0).AffectsRender())
        .Property(CompositeTransform::SkewXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform::SkewYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform::RotationProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform::TranslateXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform::TranslateYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<TransformGroup>(context)
        .Content<Transform>("Children", ContentKind::Collection, &AddTransformGroupChild, &ClearTransformGroupChildren)
        .Factory();

    Register<Transform3D>(context, TypeFlags::Abstract);

    Register<CompositeTransform3D>(context)
        .Property(CompositeTransform3D::CenterXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::CenterYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::CenterZProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::RotationXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::RotationYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::RotationZProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::ScaleXProperty, FrameworkPropertyMetadata(1.0).AffectsRender())
        .Property(CompositeTransform3D::ScaleYProperty, FrameworkPropertyMetadata(1.0).AffectsRender())
        .Property(CompositeTransform3D::ScaleZProperty, FrameworkPropertyMetadata(1.0).AffectsRender())
        .Property(CompositeTransform3D::TranslateXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::TranslateYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(CompositeTransform3D::TranslateZProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<PerspectiveTransform3D>(context)
        .Property(PerspectiveTransform3D::DepthProperty, FrameworkPropertyMetadata(Base::DefaultPerspectiveDepth) .AffectsRender())
        .Property(PerspectiveTransform3D::OffsetXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(PerspectiveTransform3D::OffsetYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<MatrixTransform3D>(context)
        .Property(MatrixTransform3D::MatrixProperty, FrameworkPropertyMetadata(Base::IdentityTransform3()) .AffectsRender())
        .Factory();

    Register<Effect>(context, TypeFlags::Abstract);

    Register<BlurEffect>(context)
        .Property(BlurEffect::RadiusProperty, FrameworkPropertyMetadata(5.0) .AffectsRender() .Validate(&Base::Validate::NonNegative<double>))
        .Factory();

    Register<DropShadowEffect>(context)
        .Property(DropShadowEffect::BlurRadiusProperty, FrameworkPropertyMetadata(5.0) .AffectsRender() .Validate(&Base::Validate::NonNegative<double>))
        .Property(DropShadowEffect::DirectionProperty, FrameworkPropertyMetadata(315.0) .AffectsRender())
        .Property(DropShadowEffect::ShadowDepthProperty, FrameworkPropertyMetadata(5.0) .AffectsRender() .Validate(&Base::Validate::NonNegative<double>))
        .Property(DropShadowEffect::OpacityProperty, FrameworkPropertyMetadata(1.0) .AffectsRender() .Validate(&ValidateUnitDouble))
        .Property(DropShadowEffect::ColorProperty, FrameworkPropertyMetadata(Base::Color{ 0.0F, 0.0F, 0.0F, 1.0F}) .AffectsRender())
        .Factory();

    Register<PixelateEffect>(context)
        .Property(PixelateEffect::SizeProperty, FrameworkPropertyMetadata(1.0) .AffectsRender() .Validate(&Base::Validate::Positive<double>))
        .Factory();

    Register<TintEffect>(context)
        .Property(TintEffect::ColorProperty, FrameworkPropertyMetadata(Base::Color{0.0F, 0.0F, 1.0F, 1.0F}) .AffectsRender())
        .Factory();

    Register<DirectionalBlurEffect>(context)
        .Property(DirectionalBlurEffect::RadiusProperty, FrameworkPropertyMetadata(0.0) .AffectsRender() .Validate(&Base::Validate::NonNegative<double>))
        .Property(DirectionalBlurEffect::AngleProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<ShaderEffect>(context)
        .Property(ShaderEffect::PixelShaderProperty, FrameworkPropertyMetadata(Base::String{}) .AffectsRender() .Changed(&ShaderEffect::OnPixelShaderChanged))
        .Factory();

    Register<MediaElement>(context)
        .Event(MediaElement::BufferingEndedEvent, RoutingStrategy::Direct)
        .Event(MediaElement::BufferingStartedEvent, RoutingStrategy::Direct)
        .Event(MediaElement::MediaEndedEvent, RoutingStrategy::Direct)
        .Event(MediaElement::MediaFailedEvent, RoutingStrategy::Direct)
        .Event(MediaElement::MediaOpenedEvent, RoutingStrategy::Direct)
        .Property(MediaElement::SourceProperty, FrameworkPropertyMetadata(Base::String{}))
        .Property(MediaElement::StretchProperty, FrameworkPropertyMetadata(Stretch::Uniform) .AffectsMeasure() .AffectsRender())
        .Property(MediaElement::StretchDirectionProperty, FrameworkPropertyMetadata(StretchDirection::Both) .AffectsMeasure() .AffectsRender())
        .Property(MediaElement::LoadedBehaviorProperty, FrameworkPropertyMetadata(MediaState::Play))
        .Property(MediaElement::UnloadedBehaviorProperty, FrameworkPropertyMetadata(MediaState::Close))
        .Property(MediaElement::IsMutedProperty, FrameworkPropertyMetadata(false))
        .Property(MediaElement::VolumeProperty, FrameworkPropertyMetadata(0.5))
        .Property(MediaElement::BalanceProperty, FrameworkPropertyMetadata(0.0))
        .Property(MediaElement::ScrubbingEnabledProperty, FrameworkPropertyMetadata(false))
        .Factory();

    Register<VisualBrush>(context)
        .Property(VisualBrush::VisualProperty, FrameworkPropertyMetadata(Base::Ref<Base::Object>{}))
        .Factory();

    Register<ICommand>(context, TypeFlags::Abstract)
        .TextConverter(&ConvertRoutedCommandReference);
    Register<InputGesture>(context, TypeFlags::Abstract);
    Register<KeyGesture>(context);
    Register<RoutedCommand>(context)
        .TextConverter(&ConvertRoutedCommandReference);
    Register<RoutedUICommand>(context);
    Register<InputBinding>(context, TypeFlags::Abstract);
    Register<CommandBinding>(context)
        .Property("Command", &CommandBinding::GetCommandName, &CommandBinding::SetCommandName)
        .Property("Executed", &CommandBinding::GetExecutedName, &CommandBinding::SetExecutedName)
        .Property("CanExecute", &CommandBinding::GetCanExecuteName, &CommandBinding::SetCanExecuteName)
        .Factory();
    Register<ApplicationCommands>(context, TypeFlags::Abstract);
    status = ApplicationCommands::RegisterDefaults();
    if (!status) return status.GetStatus();
    return {};
}
