// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateUiResources(
    ::Aero::Meta::Registration& context) noexcept {
    Register<ResourceDictionary>(context)
        .Property<Base::ResourceUri, &ResourceDictionary::GetSource, &ResourceDictionary::SetSource>("Source", PropertyFlags::None)
        .Collection<ResourceDictionary>("MergedDictionaries", &AddMergedDictionary, &ClearMergedDictionaries)
        .Content<Base::Object>("Entries", ContentKind::Collection)
        .Factory();

    Register<Media::Geometry>(context)
        .Property("Transform", &Media::Geometry::GetTransform, &Media::Geometry::SetTransform, PropertyFlags::Structural)
        .Content(MakeMemberId(Media::Geometry::StaticTypeId(), MemberKind::Property, "Transform"))
        .TextConverter(&ConvertGeometryText)
        .Factory();

    Register<Media::DashStyle>(context)
        .Factory();

    Register<Media::Pen>(context)
        .Property<Base::Ref<Media::Brush>, &Media::Pen::GetBrush, &Media::Pen::SetBrush>("Brush", PropertyFlags::None)
        .Property(Media::Pen::ThicknessProperty, FrameworkPropertyMetadata(1.0) .Validate(&Base::Validate::NonNegative<double>))
        .Property<Base::Ref<Media::DashStyle>, &Media::Pen::GetDashStyle, &Media::Pen::SetDashStyle>("DashStyle", PropertyFlags::None)
        .Property(Media::Pen::LineJoinProperty, FrameworkPropertyMetadata(Media::PenLineJoin::Miter))
        .Property(Media::Pen::StartLineCapProperty, FrameworkPropertyMetadata(Media::PenLineCap::Flat))
        .Property(Media::Pen::EndLineCapProperty, FrameworkPropertyMetadata(Media::PenLineCap::Flat))
        .Property(Media::Pen::MiterLimitProperty, FrameworkPropertyMetadata(10.0) .Validate(&Base::Validate::NonNegative<double>))
        .Factory();

    Register<Media::StreamGeometry>(context)
        .Property("Data", &Media::StreamGeometry::GetData, &Media::StreamGeometry::SetData, PropertyFlags::Structural)
        .Content(MakeMemberId(Media::StreamGeometry::StaticTypeId(), MemberKind::Property, "Data"))
        .TextConverter(&ConvertGeometryText)
        .Factory();

    Register<Media::PathSegment>(context, TypeFlags::Abstract);

    Register<Media::LineSegment>(context)
        .Property(Media::LineSegment::PointProperty, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Factory();

    Register<Media::PathFigure>(context)
        .Property(Media::PathFigure::StartPointProperty, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(Media::PathFigure::IsClosedProperty, FrameworkPropertyMetadata(false).AffectsRender())
        .Content<Media::PathSegment>("Segments", ContentKind::Collection, &AddPathFigureSegment, &ClearPathFigureSegments)
        .Factory();

    Register<Media::PathGeometry>(context)
        .Content<Media::PathFigure>("Figures", ContentKind::Collection, &AddPathGeometryFigure, &ClearPathGeometryFigures)
        .Factory();

    Register<Media::BezierSegment>(context)
        .Property(Media::BezierSegment::Point1Property, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(Media::BezierSegment::Point2Property, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(Media::BezierSegment::Point3Property, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Factory();

    Register<Media::QuadraticBezierSegment>(context)
        .Property(Media::QuadraticBezierSegment::Point1Property, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(Media::QuadraticBezierSegment::Point2Property, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Factory();

    Register<Media::ArcSegment>(context)
        .Property(Media::ArcSegment::PointProperty, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(Media::ArcSegment::SizeProperty, FrameworkPropertyMetadata(Size{}).AffectsRender())
        .Property(Media::ArcSegment::RotationAngleProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(Media::ArcSegment::IsLargeArcProperty, FrameworkPropertyMetadata(false).AffectsRender())
        .Property(Media::ArcSegment::SweepDirectionProperty, FrameworkPropertyMetadata(Media::SweepDirection::Counterclockwise) .AffectsRender())
        .Factory();

    Register<Media::PolyLineSegment>(context)
        .Property<Base::String, &Media::PolyLineSegment::SetPointsText>("Points", PropertyFlags::None)
        .Factory();

    Register<Media::PolyBezierSegment>(context)
        .Property<Base::String, &Media::PolyBezierSegment::SetPointsText>("Points", PropertyFlags::None)
        .Factory();

    Register<Media::PolyQuadraticBezierSegment>(context)
        .Property<Base::String, &Media::PolyQuadraticBezierSegment::SetPointsText>("Points", PropertyFlags::None)
        .Factory();

    Register<Media::LineGeometry>(context)
        .Property(Media::LineGeometry::StartPointProperty, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(Media::LineGeometry::EndPointProperty, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Factory();

    Register<Media::RectangleGeometry>(context)
        .Property(Media::RectangleGeometry::RectProperty, FrameworkPropertyMetadata(Rect{}).AffectsRender())
        .Property(Media::RectangleGeometry::RadiusXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(Media::RectangleGeometry::RadiusYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<Media::EllipseGeometry>(context)
        .Property(Media::EllipseGeometry::CenterProperty, FrameworkPropertyMetadata(Point{}).AffectsRender())
        .Property(Media::EllipseGeometry::RadiusXProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Property(Media::EllipseGeometry::RadiusYProperty, FrameworkPropertyMetadata(0.0).AffectsRender())
        .Factory();

    Register<Media::GeometryGroup>(context)
        .Content<Media::Geometry>("Children", ContentKind::Collection, &AddGeometryGroupChild, &ClearGeometryGroupChildren)
        .Factory();

    Register<Media::CombinedGeometry>(context)
        .Property("Geometry1", &Media::CombinedGeometry::GetGeometry1, &Media::CombinedGeometry::SetGeometry1, PropertyFlags::Structural)
        .Property("Geometry2", &Media::CombinedGeometry::GetGeometry2, &Media::CombinedGeometry::SetGeometry2, PropertyFlags::Structural)
        .Property(Media::CombinedGeometry::GeometryCombineModeProperty, FrameworkPropertyMetadata(Media::GeometryCombineMode::Union) .AffectsRender())
        .Factory();

    Register<Media::FontFamily>(context)
        .Property("Source", &Media::FontFamily::GetSource, &Media::FontFamily::SetSource, PropertyFlags::Structural)
        .Content(MakeMemberId(Media::FontFamily::StaticTypeId(), MemberKind::Property, "Source"))
        .TextConverter(&ConvertFontFamilyText)
        .Factory();
    return {};
}
