# Explicit installed SDK header whitelist.
# Adding a public header is an API decision and must update this file.
set(AERO_PUBLIC_HEADERS
    include/AeroApp/App.hpp
    include/AeroAudio/Audio.hpp
    include/Aero/Base/Allocator.hpp
    include/Aero/Base/Assert.hpp
    include/Aero/Base/Config.hpp
    include/Aero/Base/Delegate.hpp
    include/Aero/Base/Geometry.hpp
    include/Aero/Base/Hash.hpp
    include/Aero/Base/HashMap.hpp
    include/Aero/Base/HashSet.hpp
    include/Aero/Base/MetadataId.hpp
    include/Aero/Base/Object.hpp
    include/Aero/Base/Ref.hpp
    include/Aero/Base/ResourceUri.hpp
    include/Aero/Base/Result.hpp
    include/Aero/Base/Span.hpp
    include/Aero/Base/Stream.hpp
    include/Aero/Base/String.hpp
    include/Aero/Base/StringView.hpp
    include/Aero/Base/Utf8.hpp
    include/Aero/Base/Vector.hpp
    include/Aero/CAPI.h
    include/Aero/Controls.hpp
    include/Aero/Controls/UserControl.hpp
    include/Aero/Controls/CheckBox.hpp
    include/Aero/Controls/RadioButton.hpp
    include/Aero/Controls/ComboBox.hpp
    include/Aero/Controls/ListView.hpp
    include/Aero/Controls/ScrollViewer.hpp
    include/Aero/Collections.hpp
    include/Aero/Diagnostics.hpp
    include/Aero/Diagnostics/DependencyProperty.hpp
    include/Aero/Diagnostics/Layout.hpp
    include/Aero/Diagnostics/PropertyValueSource.hpp
    include/Aero/Diagnostics/Rendering.hpp
    include/Aero/Threading.hpp
    include/Aero/Meta.hpp
    include/Aero/Value.hpp
    include/Aero/Documents.hpp
    include/Aero/Documents/Bold.hpp
    include/Aero/Documents/Hyperlink.hpp
    include/Aero/Documents/Inline.hpp
    include/Aero/Documents/InlineCollection.hpp
    include/Aero/Documents/InlineCollectionView.hpp
    include/Aero/Documents/Italic.hpp
    include/Aero/Documents/LineBreak.hpp
    include/Aero/Documents/NavigationService.hpp
    include/Aero/Documents/Run.hpp
    include/Aero/Documents/Span.hpp
    include/Aero/Documents/TextElement.hpp
    include/Aero/Documents/TextPointer.hpp
    include/Aero/Documents/TextRange.hpp
    include/Aero/Documents/Underline.hpp
    include/Aero/Media/DrawingContext.hpp
    include/Aero/Events/ApplicationEventArgs.hpp
    include/Aero/Events/CommandEventArgs.hpp
    include/Aero/Events/ControlEventArgs.hpp
    include/Aero/Events/Event.hpp
    include/Aero/Events/EventArgs.hpp
    include/Aero/Events.hpp
    include/Aero/Events/NavigationEventArgs.hpp
    include/Aero/Events/PropertyEventArgs.hpp
    include/Aero/Events/WindowEventArgs.hpp
    include/Aero/Freezable.hpp
    include/Aero/Gui.hpp
    include/AeroApp/Application.hpp
    include/AeroApp/Window.hpp
    include/Aero/DependencyObject.hpp
    include/Aero/DispatcherObject.hpp
    include/Aero/TryCast.hpp
    include/Aero/DependencyProperty.hpp
    include/Aero/RoutedEvent.hpp
    include/Aero/Visual.hpp
    include/Aero/Visibility.hpp
    include/Aero/HorizontalAlignment.hpp
    include/Aero/UIElement.hpp
    include/Aero/FrameworkElement.hpp
    include/Aero/FrameworkContentElement.hpp
    include/Aero/Controls/Control.hpp
    include/Aero/Controls/ContentControl.hpp
    include/Aero/Controls/Panel.hpp
    include/Aero/Controls/ButtonBase.hpp
    include/Aero/Controls/RepeatButton.hpp
    include/Aero/Controls/Button.hpp
    include/Aero/Controls/ToggleButton.hpp
    include/Aero/Controls/Grid.hpp
    include/Aero/Controls/GridLength.hpp
    include/Aero/Controls/StackPanel.hpp
    include/Aero/Controls/Border.hpp
    include/Aero/Controls/ItemsControl.hpp
    include/Aero/Controls/ItemCollection.hpp
    include/Aero/Controls/AlternationConverter.hpp
    include/Aero/Controls/ItemsPanelTemplate.hpp
    include/Aero/Controls/ItemsPresenter.hpp
    include/Aero/Controls/HeaderedItemsControl.hpp
    include/Aero/Controls/ItemContainerGenerator.hpp
    include/Aero/Controls/ListBox.hpp
    include/Aero/Controls/ListBoxItem.hpp
    include/Aero/Controls/TreeView.hpp
    include/Aero/Controls/TextBlock.hpp
    include/Aero/Controls/TextBoxBase.hpp
    include/Aero/Controls/TextBox.hpp
    include/Aero/Data/Binding.hpp
    include/Aero/Resources.hpp
    include/Aero/Style.hpp
    include/Aero/FrameworkTemplate.hpp
    include/Aero/Controls/ControlTemplate.hpp
    include/Aero/VisualStateManager.hpp
    include/Aero/DataTemplate.hpp
    include/Aero/Media/Animation.hpp
    include/Aero/Media/BlendMode.hpp
    include/Aero/Media/Brushes.hpp
    include/Aero/Media/Geometry.hpp
    include/Aero/Media/Transforms.hpp
    include/Aero/Markup/XamlDocument.hpp
    include/Aero/Markup/XamlReader.hpp
    include/Aero/Media/CompositionTarget.hpp
    include/Aero/View.hpp
    include/Aero/IRenderer.hpp
    include/AeroRender/Render.hpp
    include/AeroRender/RenderDevice.hpp
    include/AeroRender/Texture.hpp
    include/AeroRender/RenderTarget.hpp
    include/AeroRender/WindowInterop.hpp
    include/Aero/Input.hpp
    include/Aero/InputInterop.hpp
    include/AeroApp/WindowInterop.hpp
    include/AeroRender/D3D11.hpp
    include/AeroRender/OpenGL33.hpp
    include/Aero/Markup/ReloadCoordinator.hpp
    include/Aero/Markup/ResourceScope.hpp
    include/Aero/Markup/ServiceProvider.hpp
    include/Aero/Media/FontProvider.hpp
    include/Aero/Media/TextureProvider.hpp
    include/Aero/Markup/XamlProvider.hpp
    include/Aero/ViewOptions.hpp
    include/Aero/Layout.hpp
    include/Aero/Media/Effects.hpp
    include/Aero/Media/Fonts.hpp
    include/Aero/Media/Images.hpp
    include/Aero/Module.hpp
    include/Aero/Shapes.hpp
    include/Aero/Shapes/Ellipse.hpp
    include/Aero/Shapes/Path.hpp
    include/Aero/Shapes/Rectangle.hpp
    include/Aero/Shapes/Shape.hpp
    include/Aero/Triggers/Conditions.hpp
    include/Aero/Triggers/DataTrigger.hpp
    include/Aero/Media/Animation/EventTrigger.hpp
    include/Aero/Interactivity/InteractionTriggers.hpp
    include/Aero/Interactivity/Conditions.hpp
    include/Aero/Triggers/MultiDataTrigger.hpp
    include/Aero/Triggers/MultiTrigger.hpp
    include/Aero/Media/Animation/StoryboardCompletedTrigger.hpp
    include/Aero/Media/Animation/TimerTrigger.hpp
    include/Aero/Triggers/Trigger.hpp
    include/Aero/Interactivity/TriggerAction.hpp
    include/Aero/Triggers/TriggerBase.hpp
    include/Aero/Triggers/Triggers.hpp
    include/Aero/Interactivity/Behavior.hpp
    include/Aero/Interactivity/BlendBehaviors.hpp
    include/Aero/Interactivity/ChangePropertyAction.hpp
    include/Aero/Interactivity/LaunchUriOrFileAction.hpp
    include/Aero/Interactivity/RemoveElementAction.hpp
    include/Aero/Interactivity/SetFocusAction.hpp
    include/Aero/Media/Animation/StoryboardActions.hpp
    include/Aero/Media/MediaElement.hpp
    include/Aero/Media/Animation/MediaActions.hpp
    include/Aero/TextFormatting.hpp
    include/Aero/Controls/Decorator.hpp
    include/Aero/Controls/ContentPresenter.hpp
    include/Aero/Controls/Primitives.hpp
    include/Aero/Controls/Primitives/Selector.hpp
    include/Aero/Controls/Primitives/Thumb.hpp
    include/Aero/Controls/Primitives/Track.hpp
    include/Aero/Controls/Primitives/RangeBase.hpp
    include/Aero/Controls/Primitives/ScrollBar.hpp
    include/Aero/Controls/Primitives/TickBar.hpp
    include/Aero/Controls/RangeBase.hpp
    include/Aero/Controls/Slider.hpp
    include/Aero/Controls/ProgressBar.hpp
    include/Aero/Controls/GridSplitter.hpp
    include/Aero/Controls/Popup.hpp
    include/Aero/Controls/HeaderedContentControl.hpp
    include/Aero/Controls/VirtualizingPanel.hpp
    include/Aero/Controls/VirtualizingStackPanel.hpp
    include/Aero/Controls/Menu.hpp
    include/Aero/Controls/ToolBar.hpp
    include/Aero/Controls/StatusBar.hpp
    include/Aero/Controls/ToolTip.hpp
    include/Aero/Controls/Image.hpp
    include/Aero/Controls/PasswordBox.hpp
    include/Aero/ContentElement.hpp
    include/Aero/VisualTreeHelper.hpp
    include/Aero/LogicalTreeHelper.hpp
    include/Aero/Controls/DockPanel.hpp
    include/Aero/Controls/WrapPanel.hpp
    include/Aero/Controls/UniformGrid.hpp
    include/Aero/Controls/Canvas.hpp
    include/Aero/Controls/Viewbox.hpp
    include/Aero/Controls/GroupBox.hpp
    include/Aero/Controls/Label.hpp
    include/Aero/Controls/Expander.hpp
    include/Aero/Controls/TabItem.hpp
    include/Aero/Controls/TabControl.hpp
    include/Aero/Controls/TabPanel.hpp
    include/Aero/Controls/Primitives/ButtonBase.hpp
    include/Aero/Controls/Primitives/ToggleButton.hpp
    include/Aero/Controls/Primitives/RepeatButton.hpp
)
