# Explicit installed SDK header whitelist.
# Adding a public header is an API decision and must update this file.
set(AERO_PUBLIC_HEADERS
    include/Aero/Animation.hpp
    include/Aero/App.hpp
    include/Aero/Application.hpp
    include/Aero/Audio/Audio.hpp
    include/Aero/Base/Allocator.hpp
    include/Aero/Base/Assert.hpp
    include/Aero/Base/Config.hpp
    include/Aero/Base/Delegate.hpp
    include/Aero/Base/Geometry.hpp
    include/Aero/Base/Hash.hpp
    include/Aero/Base/HashMap.hpp
    include/Aero/Base/HashSet.hpp
    include/Aero/Base/MetadataId.hpp
    include/Aero/Base/Object.hpp
    include/Aero/Base/Ref.hpp
    include/Aero/Base/ResourceUri.hpp
    include/Aero/Base/Result.hpp
    include/Aero/Base/Span.hpp
    include/Aero/Base/Stream.hpp
    include/Aero/Base/String.hpp
    include/Aero/Base/StringView.hpp
    include/Aero/Base/Utf8.hpp
    include/Aero/Base/Vector.hpp
    include/Aero/CAPI.h
    include/Aero/ContentElement.hpp
    include/Aero/Controls.hpp
    include/Aero/Controls/Core.hpp
    include/Aero/Controls/Items.hpp
    include/Aero/Controls/Panels.hpp
    include/Aero/Controls/Primitives.hpp
    include/Aero/Controls/Common.hpp
    include/Aero/Controls/Text.hpp
    include/Aero/Collections.hpp
    include/Aero/Diagnostics.hpp
    include/Aero/Threading.hpp
    include/Aero/Meta.hpp
    include/Aero/Value.hpp
    include/Aero/DependencyProperty.hpp
    include/Aero/Diagnostics/PropertyValueSource.hpp
    include/Aero/Data.hpp
    include/Aero/DependencyObject.hpp
    include/Aero/Diagnostics/DependencyProperty.hpp
    include/Aero/Documents.hpp
    include/Aero/DrawingContext.hpp
    include/Aero/Events/ApplicationEventArgs.hpp
    include/Aero/Events/CommandEventArgs.hpp
    include/Aero/Events/ControlEventArgs.hpp
    include/Aero/Events/Event.hpp
    include/Aero/Events/EventArgs.hpp
    include/Aero/Events.hpp
    include/Aero/Events/NavigationEventArgs.hpp
    include/Aero/Events/PropertyEventArgs.hpp
    include/Aero/Events/RoutedEvent.hpp
    include/Aero/Events/WindowEventArgs.hpp
    include/Aero/FrameworkElement.hpp
    include/Aero/Gui.hpp
    include/Aero/Input.hpp
    include/Aero/Integration.hpp
    include/Aero/Integration/Platform.hpp
    include/Aero/Integration/NativeWindow.hpp
    include/Aero/View.hpp
    include/Aero/Integration/D3D11.hpp
    include/Aero/Integration/OpenGL33.hpp
    include/Aero/Integration/ReloadCoordinator.hpp
    include/Aero/Integration/RenderDevice.hpp
    include/Aero/Integration/Providers/FontProvider.hpp
    include/Aero/Integration/Providers/Providers.hpp
    include/Aero/Integration/Providers/TextureProvider.hpp
    include/Aero/Integration/Providers/XamlProvider.hpp
    include/Aero/Integration/ViewOptions.hpp
    include/Aero/App/WindowInterop.hpp
    include/Aero/Layout.hpp
    include/Aero/Markup.hpp
    include/Aero/Media/Brushes.hpp
    include/Aero/Media/Effects.hpp
    include/Aero/Media/Geometry.hpp
    include/Aero/Media/Images.hpp
    include/Aero/Media/Transforms.hpp
    include/Aero/Module.hpp
    include/Aero/Resources.hpp
    include/Aero/Shapes.hpp
    include/Aero/Style.hpp
    include/Aero/Styling.hpp
    include/Aero/Triggers/Conditions.hpp
    include/Aero/Triggers/DataTrigger.hpp
    include/Aero/Triggers/EventTrigger.hpp
    include/Aero/Triggers/MultiDataTrigger.hpp
    include/Aero/Triggers/MultiTrigger.hpp
    include/Aero/Triggers/StoryboardCompletedTrigger.hpp
    include/Aero/Triggers/TimerTrigger.hpp
    include/Aero/Triggers/Trigger.hpp
    include/Aero/Triggers/TriggerAction.hpp
    include/Aero/Triggers/TriggerBase.hpp
    include/Aero/Triggers/Triggers.hpp
    include/Aero/Triggers/ChangePropertyAction.hpp
    include/Aero/Triggers/LaunchUriOrFileAction.hpp
    include/Aero/Triggers/RemoveElementAction.hpp
    include/Aero/Triggers/SetFocusAction.hpp
    include/Aero/Triggers/StoryboardActions.hpp
    include/Aero/UIElement.hpp
    include/Aero/Visual.hpp
    include/Aero/Window.hpp
)
