// Controls metadata: widgets (templates + primitives + items).
// ---- From Templates.inl (merged; registration order preserved) ----
// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsTemplates(
    ::Aero::Meta::Registration& context) noexcept {
    Register<FrameworkTemplate>(context, TypeFlags::Abstract)
        .Property<Base::Ref<Aero::ResourceDictionary>, &FrameworkTemplate::SetResources>("Resources", PropertyFlags::Structural)
        .Collection<Base::Object>("Triggers", &AddTemplateTrigger, &ClearTemplateTriggers);

    Register<ControlTemplate>(context)
        .Property<Meta::TypeReference, &GetControlTemplateTargetType, &SetControlTemplateTargetType>("TargetType", PropertyFlags::None)
        .Collection<Base::Object>("VisualStateGroups", &AddTemplateVisualStateGroup, &ClearTemplateVisualStateGroups)
        .Content<Base::Object>("VisualTree", ContentKind::Single, &SetDeferredTemplateVisualTree<ControlTemplate>, &ClearDeferredTemplateVisualTree<ControlTemplate>, ContentFlags::Visual)
        .Factory();

    Register<DataTemplate>(context)
        .Property<Meta::TypeReference, &GetDataTemplateType, &SetDataTemplateType>("DataType", PropertyFlags::None)
        .Property<Base::Ref<Aero::ResourceDictionary>, &DataTemplate::SetResources>("Resources", PropertyFlags::Structural)
        .Collection<Aero::TriggerBase>("Triggers", &AddDataTemplateTrigger, &ClearDataTemplateTriggers)
        .Content<Base::Object>("VisualTree", ContentKind::Single, &SetDeferredTemplateVisualTree<DataTemplate>, &ClearDeferredTemplateVisualTree<DataTemplate>, ContentFlags::Visual)
        .Factory();

    Register<DataTemplateSelector>(context)
        .Factory();

    Register<HierarchicalDataTemplate>(context)
        .Property<Base::Ref<Base::Object>, &HierarchicalDataTemplate::GetItemsSource, &HierarchicalDataTemplate::SetItemsSource>("ItemsSource", PropertyFlags::None)
        .Property<Base::Ref<Base::Object>, &HierarchicalDataTemplate::GetItemTemplate, &HierarchicalDataTemplate::SetItemTemplate>("ItemTemplate", PropertyFlags::None)
        .Content<Base::Object>("VisualTree", ContentKind::Single, &SetDeferredTemplateVisualTree<DataTemplate>, &ClearDeferredTemplateVisualTree<DataTemplate>, ContentFlags::Visual)
        .Factory();

    Register<ItemsPanelTemplate>(context)
        .Property<Base::Ref<Aero::ResourceDictionary>, &ItemsPanelTemplate::SetResources>("Resources", PropertyFlags::Structural)
        .Content<Base::Object>("VisualTree", ContentKind::Single, &SetDeferredTemplateVisualTree<ItemsPanelTemplate>, &ClearDeferredTemplateVisualTree<ItemsPanelTemplate>, ContentFlags::Visual)
        .Factory();

    return {};
}

// ---- From Primitives.inl (merged; registration order preserved) ----
// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsPrimitives(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;

    Register<Panel>(context, TypeFlags::Abstract)
        .Property(Panel::BackgroundProperty, Base::Ref<Media::Brush>{}, AffectsRender)
        .Property(Panel::ZIndexProperty, std::int32_t{0}, AffectsParentArrange)
        .Property(Panel::IsItemsHostProperty, false)
        .Content<Aero::UIElement>("Children", ContentKind::Collection, &SetPanelContent, &ClearPanelContent, ContentFlags::Visual);

    Register<Decorator>(context)
        .Content<Aero::UIElement>("Content", ContentKind::Single, &SetDecoratorContent, &ClearDecoratorContent, ContentFlags::Visual)
        .Factory();

    // Bullet is the explicit WPF property-element name. Treating the same
    // visual collection as implicit content lets the following child element
    // populate the regular content slot while retaining both tree edges.
    Register<BulletDecorator>(context)
        .Property(BulletDecorator::BackgroundProperty, Base::Ref<Aero::Media::Brush>{}, AffectsRender)
        .Content<Aero::UIElement>("Bullet", ContentKind::Collection, &AddBulletDecoratorContent, &ClearBulletDecoratorContent, ContentFlags::Visual)
        .Factory();

    Register<Viewbox>(context)
        .Property(Viewbox::StretchProperty, Stretch::Uniform, AffectsMeasure)
        .Property(Viewbox::StretchDirectionProperty, StretchDirection::Both, AffectsMeasure)
        .Content<Aero::UIElement>("Content", ContentKind::Single, &SetDecoratorContent, &ClearDecoratorContent, ContentFlags::Visual)
        .Factory();

    Register<Control>(context)
        .Event(Control::PreviewMouseDoubleClickEvent, RoutingStrategy::Tunnel)
        .Event(Control::MouseDoubleClickEvent)
        .Override(UIElement::FocusableProperty, true, FrameworkPropertyMetadataOptions::None)
        .Override(UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None)
        .Property(Control::BackgroundProperty, Base::Ref<Media::Brush>{}, AffectsRender)
        .Property(Control::BorderBrushProperty, Base::Ref<Media::Brush>{}, AffectsRender)
        .Property(Control::BorderThicknessProperty, Aero::Thickness{}, AffectsMeasure | AffectsRender, &ValidateThicknessValue)
        .Property(Control::PaddingProperty, Aero::Thickness{}, AffectsMeasure, &ValidateThicknessValue)
        .Property(Control::FontWeightProperty, FontWeight::Normal, AffectsMeasure)
        .Property(Control::HorizontalContentAlignmentProperty, Aero::HorizontalAlignment::Left, AffectsArrange)
        .Property(Control::VerticalContentAlignmentProperty, Aero::VerticalAlignment::Top, AffectsArrange)
        .Property(Control::FontSizeProperty, 15.0, Inherits | AffectsMeasure, &ValidatePositiveFiniteDouble)
        .Property(Control::FocusVisualStyleProperty, Base::Ref<Aero::Style>{})
        .Property(Control::OverridesDefaultStyleProperty, false)
        .Property(Control::TemplateProperty, Base::Ref<ControlTemplate>{}, AffectsMeasure)
        .Factory<BasicControl>();

    Register<ContentControl>(context)
        .Property(ContentControl::ContentProperty, FrameworkPropertyMetadata(Meta::Value::NullObject(Meta::TypeOf<Base::Object>()), AffectsMeasure).Structural().Changed(&AeroGuiInternal::OnContentControlPropertyChanged))
        .Property(ContentControl::ContentTemplateProperty, Base::Ref<Base::Object>{}, AffectsMeasure)
        .Property(ContentControl::ContentTemplateSelectorProperty, Base::Ref<Base::Object>{}, AffectsMeasure)
        .ContentAccessor(MakeMemberId(ContentControl::StaticTypeId(), MemberKind::Property, "Content"), ContentKind::Single, &SetContentControlContent, &ClearContentControlContent, ContentFlags::Visual)
        .Factory<BasicContentControl>();

    // UserControl is a concrete ContentControl root for LoadComponent. Content
    // and resource semantics are inherited from ContentControl; the distinct
    // factory preserves the application's registered runtime type.
    Register<UserControl>(context)
        .Factory();

    Register<ButtonBase>(context, TypeFlags::Abstract)
        .Event(ButtonBase::ClickEvent)
        .Property(ButtonBase::ClickModeProperty, ClickMode::Release)
        .Property(ButtonBase::CommandProperty, Base::Ref<ICommand>{})
        .Property(ButtonBase::CommandParameterProperty, Value::NullObject(TypeOf<Base::Object>()))
        .Property(ButtonBase::CommandTargetProperty, Base::Ref<UIElement>{})
        .Override(UIElement::IsEnabledProperty, FrameworkPropertyMetadata(true, Inherits | AffectsRender).Coerce(&CoerceButtonEnabled))
        .Override(UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None);

    Register<Button>(context)
        .Factory();

    Register<RepeatButton>(context)
        .Property(RepeatButton::DelayProperty, std::uint32_t{400})
        .Property(RepeatButton::IntervalProperty, std::uint32_t{100}, FrameworkPropertyMetadataOptions::None, &Base::Validate::Positive<std::uint32_t>)
        .Override(ButtonBase::ClickModeProperty, ClickMode::Press, FrameworkPropertyMetadataOptions::None)
        .Factory();

    Register<ToggleButton>(context)
        .Event(ToggleButton::CheckedEvent)
        .Event(ToggleButton::UncheckedEvent)
        .Event(ToggleButton::IndeterminateEvent)
        .Property(ToggleButton::IsCheckedProperty, Nullable<bool>{false}, BindsTwoWayByDefault | AffectsRender)
        .Property(ToggleButton::IsThreeStateProperty, false, AffectsRender)
        .Factory();

    Register<CheckBox>(context)
        .Factory();

    Register<RadioButton>(context)
        .Property(RadioButton::GroupNameProperty, Base::String{})
        .Factory();

    Register<ScrollContentPresenter>(context)
        .Property(ScrollContentPresenter::CanContentScrollProperty, false, AffectsMeasure)
        .Factory();

    Register<ScrollViewer>(context)
        .Event(ScrollViewer::ScrollChangedEvent)
        .Property(ScrollViewer::HorizontalOffsetProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::VerticalOffsetProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::ExtentWidthProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::ExtentHeightProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::ViewportWidthProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::ViewportHeightProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::ScrollableWidthProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::ScrollableHeightProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollViewer::ComputedHorizontalScrollBarVisibilityProperty, Visibility::Collapsed, AffectsMeasure | AffectsRender)
        .Property(ScrollViewer::ComputedVerticalScrollBarVisibilityProperty, Visibility::Collapsed, AffectsMeasure | AffectsRender)
        .Property(ScrollViewer::HorizontalScrollBarVisibilityProperty, FrameworkPropertyMetadata(ScrollBarVisibility::Disabled, AffectsMeasure | AffectsRender).Changed(&OnScrollViewerVisibilityChanged))
        .Property(ScrollViewer::VerticalScrollBarVisibilityProperty, FrameworkPropertyMetadata(ScrollBarVisibility::Visible, AffectsMeasure | AffectsRender).Changed(&OnScrollViewerVisibilityChanged))
        .Property(ScrollViewer::CanHorizontallyScrollProperty, true, AffectsMeasure)
        .Property(ScrollViewer::CanVerticallyScrollProperty, true, AffectsMeasure)
        .Property(ScrollViewer::CanContentScrollProperty, false, AffectsMeasure)
        .Property(ScrollViewer::PanningModeProperty, PanningMode::None)
        .TemplatePart("PART_VerticalScrollBar", TypeOf<ScrollBar>())
        .TemplatePart("PART_HorizontalScrollBar", TypeOf<ScrollBar>())
        .Factory();

    Register<Thumb>(context)
        .Property(Thumb::IsDraggingProperty, false, AffectsRender)
        .Factory();

    Register<Track>(context)
        .Property(Track::OrientationProperty, Orientation::Vertical, AffectsMeasure)
        .Property(Track::MinimumProperty, 0.0, AffectsArrange, &::Aero::Base::Validate::Finite<double>)
        .Property(Track::MaximumProperty, 1.0, AffectsArrange, &::Aero::Base::Validate::Finite<double>)
        .Property(Track::ValueProperty, 0.0, AffectsArrange | BindsTwoWayByDefault, &::Aero::Base::Validate::Finite<double>)
        .Property(Track::ViewportSizeProperty, 0.0, AffectsArrange, &::Aero::Base::Validate::NonNegative<double>)
        .Property(Track::IsDirectionReversedProperty, false, AffectsArrange)
        .Property<Base::Ref<RepeatButton>, &Track::SetDecreaseRepeatButton>("DecreaseRepeatButton", PropertyFlags::Structural)
        .Property<Base::Ref<Thumb>, &Track::SetThumb>("Thumb", PropertyFlags::Structural)
        .Property<Base::Ref<RepeatButton>, &Track::SetIncreaseRepeatButton>("IncreaseRepeatButton", PropertyFlags::Structural)
        .Factory();

    Register<GridSplitter>(context)
        .Property(GridSplitter::DragIncrementProperty, 1.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::Positive<double>)
        .Property(GridSplitter::KeyboardIncrementProperty, 10.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::Positive<double>)
        .Property(GridSplitter::ResizeDirectionProperty, GridResizeDirection::Auto)
        .Property(GridSplitter::ResizeBehaviorProperty, GridResizeBehavior::BasedOnAlignment)
        .Property(GridSplitter::ShowsPreviewProperty, false)
        .Property(GridSplitter::PreviewStyleProperty, Base::Ref<Aero::Style>{})
        .Factory();

    Register<RangeBase>(context, TypeFlags::Abstract)
        .Event(RangeBase::ValueChangedEvent)
        .Property(RangeBase::MinimumProperty, FrameworkPropertyMetadata(0.0, AffectsArrange).Validate(&::Aero::Base::Validate::Finite<double>).Coerce(&CoerceRangeMinimum))
        .Property(RangeBase::MaximumProperty, FrameworkPropertyMetadata(100.0, AffectsArrange).Validate(&::Aero::Base::Validate::Finite<double>).Coerce(&CoerceRangeMaximum))
        .Property(RangeBase::ValueProperty, FrameworkPropertyMetadata(0.0, AffectsArrange | BindsTwoWayByDefault).Validate(&::Aero::Base::Validate::Finite<double>).Coerce(&CoerceRangeValue));

    Register<ScrollBar>(context)
        .Property(ScrollBar::OrientationProperty, Orientation::Vertical, AffectsMeasure)
        .Property(ScrollBar::ViewportSizeProperty, 0.0, AffectsArrange, &::Aero::Base::Validate::NonNegative<double>)
        .Property(ScrollBar::SmallChangeProperty, 16.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::Positive<double>)
        .Property(ScrollBar::LargeChangeProperty, 0.0, FrameworkPropertyMetadataOptions::None, &::Aero::Base::Validate::NonNegative<double>)
        .TemplatePart("PART_Track", TypeOf<Track>())
        .Factory();

    for (Base::StringView commandName : {
             Base::StringView("LineUpCommand"),
             Base::StringView("LineUp"),
             Base::StringView("LineDownCommand"),
             Base::StringView("LineDown"),
             Base::StringView("LineLeftCommand"),
             Base::StringView("LineLeft"),
             Base::StringView("LineRightCommand"),
             Base::StringView("LineRight"),
             Base::StringView("PageUpCommand"),
             Base::StringView("PageUp"),
             Base::StringView("PageDownCommand"),
             Base::StringView("PageDown"),
             Base::StringView("PageLeftCommand"),
             Base::StringView("PageLeft"),
             Base::StringView("PageRightCommand"),
             Base::StringView("PageRight"),
             Base::StringView("ScrollToTopCommand"),
             Base::StringView("ScrollToTop"),
             Base::StringView("ScrollToBottomCommand"),
             Base::StringView("ScrollToBottom"),
             Base::StringView("ScrollToLeftEndCommand"),
             Base::StringView("ScrollToLeftEnd"),
             Base::StringView("ScrollToRightEndCommand"),
             Base::StringView("ScrollToRightEnd"),
             Base::StringView("ScrollToHorizontalOffsetCommand"),
             Base::StringView("ScrollToHorizontalOffset"),
             Base::StringView("ScrollToVerticalOffsetCommand"),
             Base::StringView("ScrollToVerticalOffset"),
             Base::StringView("DeferScrollToHorizontalOffsetCommand"),
             Base::StringView("DeferScrollToHorizontalOffset"),
             Base::StringView("DeferScrollToVerticalOffsetCommand"),
             Base::StringView("DeferScrollToVerticalOffset")}) {
        status = Input::RoutedCommand::RegisterStatic(
            ScrollBar::StaticTypeId(), commandName);
        if (!status) return status.GetStatus();
    }

    for (Base::StringView commandName : {
             Base::StringView("DecreaseSmall"),
             Base::StringView("IncreaseSmall"),
             Base::StringView("DecreaseLarge"),
             Base::StringView("IncreaseLarge")}) {
        status = Input::RoutedCommand::RegisterStatic(
            Slider::StaticTypeId(), commandName);
        if (!status) return status.GetStatus();
    }

    Register<Slider>(context)
        .Property(Slider::OrientationProperty, Orientation::Horizontal, AffectsMeasure)
        .Property(Slider::SmallChangeProperty, 1.0, FrameworkPropertyMetadataOptions::None, &Base::Validate::Positive<double>)
        .Property(Slider::LargeChangeProperty, 10.0, FrameworkPropertyMetadataOptions::None, &Base::Validate::Positive<double>)
        .Property(Slider::TickPlacementProperty, TickPlacement::None, AffectsRender)
        .Property(Slider::TickFrequencyProperty, 1.0, AffectsRender, &Base::Validate::Positive<double>)
        .Property(Slider::TicksProperty, Base::String{}, AffectsRender, &ValidateSliderTicks)
        .Property(Slider::IsSnapToTickEnabledProperty, false)
        .Property(Slider::IsDirectionReversedProperty, false, AffectsArrange | AffectsRender)
        .Property(Slider::IsMoveToPointEnabledProperty, false)
        .Override(UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None)
        .Factory();

    Register<TickBar>(context)
        .Property(TickBar::FillProperty, Base::Ref<Media::Brush>{}, AffectsRender)
        .Property(TickBar::PlacementProperty, TickBarPlacement::Top, AffectsRender)
        .Factory();

    Register<ProgressBar>(context)
        .Property(ProgressBar::IsIndeterminateProperty, false, AffectsRender)
        .Property(ProgressBar::OrientationProperty, Orientation::Horizontal, AffectsMeasure)
        .Factory();

    return {};
}

// ---- From Items.inl (merged; registration order preserved) ----
// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsItems(
    ::Aero::Meta::Registration& context) noexcept {
    Register<Collections::IItemsSource>(context, TypeFlags::Abstract);

    Register<Collections::ObservableCollectionBase>(context, TypeFlags::Abstract)
        .Implements<Collections::IItemsSource>();

    Register<Collections::ObservableObjectCollection>(context)
        .Factory()
        .Implements<Collections::IItemsSource>();

    Register<Data::CollectionView>(context)
        .Implements<Collections::IItemsSource>();

    Register<Data::CollectionViewSource>(context)
        .Factory();

    Register<AlternationConverter>(context)
        .Content<Base::Object>("Values", ContentKind::Collection,
            [](Base::Object& owner, const Base::Ref<Base::Object>& value, void*) noexcept {
                static_cast<AlternationConverter&>(owner).AddValue(value);
            },
            [](Base::Object& owner, void*) noexcept {
                static_cast<AlternationConverter&>(owner).ClearValues();
            })
        .Factory();

    Register<::Aero::Controls::BoxedItemValue>(context);

    Register<ItemsControl>(context)
        .Property(ItemsControl::ItemCountProperty, std::uint32_t{0})
        .Property(ItemsControl::HasItemsProperty, false)
        .Property(ItemsControl::ItemsSourceProperty, Base::Ref<Base::Object>{}, AffectsMeasure, &OnItemsSourceChanged)
        .Property(ItemsControl::AlternationCountProperty, std::uint32_t{0}, AffectsMeasure)
        .Property(ItemsControl::DisplayMemberPathProperty, Base::String{}, AffectsMeasure, &OnDisplayMemberPathChanged)
        .Property(ItemsControl::ItemTemplateProperty, Base::Ref<DataTemplate>{}, AffectsMeasure, &OnItemTemplateChanged)
        .Property(ItemsControl::ItemTemplateSelectorProperty, Base::Ref<DataTemplateSelector>{}, AffectsMeasure, &OnItemTemplateSelectorChanged)
        .Property(ItemsControl::ItemsPanelProperty, Base::Ref<ItemsPanelTemplate>{}, AffectsMeasure, &OnItemsPanelChanged)
        .Property(ItemsControl::ItemContainerStyleProperty, Base::Ref<Style>{}, AffectsMeasure, &OnItemContainerStyleChanged)
        .Content<Base::Object>("Items", ContentKind::Collection, &AddItemsControlItem, &ClearItemsControlItems)
        .Factory();

    Register<HeaderedItemsControl>(context, TypeFlags::Abstract)
        .Property(HeaderedItemsControl::HeaderProperty, Value::NullObject(TypeOf<Base::Object>()), AffectsMeasure)
        .Property(HeaderedItemsControl::HeaderTemplateProperty, Base::Ref<DataTemplate>{}, AffectsMeasure);

    Register<ItemsPresenter>(context)
        .Factory();

    Register<Selector>(context, TypeFlags::Abstract)
        .Event(Selector::SelectionChangedRoutedEvent)
        .Property(Selector::SelectionModeProperty, SelectionMode::Single)
        .Property(Selector::SelectedIndexProperty, UINT32_MAX, BindsTwoWayByDefault)
        .Property(Selector::SelectedItemProperty, FrameworkPropertyMetadata(Base::Ref<Base::Object>{}, BindsTwoWayByDefault).Coerce(&CoerceSelectedObject))
        .Property(Selector::SelectedValueProperty, FrameworkPropertyMetadata(Base::Ref<Base::Object>{}, BindsTwoWayByDefault).Coerce(&CoerceSelectedObject))
        .Property(Selector::SelectedValuePathProperty, Base::String{})
        .Property(Selector::IsSelectedProperty, false, AffectsRender | BindsTwoWayByDefault)
        .Property(Selector::IsSynchronizedWithCurrentItemProperty, false);

    Register<ListBox>(context)
        .Factory();

    Register<ListBoxItem>(context)
        .Property(ListBoxItem::IsSelectedProperty, false, AffectsRender | BindsTwoWayByDefault)
        .Override(Aero::UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None)
        .Factory();

    Register<ComboBox>(context)
        .Event(ComboBox::DropDownOpenedEvent)
        .Event(ComboBox::DropDownClosedEvent)
        .Property(ComboBox::IsDropDownOpenProperty, false, AffectsMeasure | AffectsRender | BindsTwoWayByDefault)
        .Property(ComboBox::MaxDropDownHeightProperty, 240.0, AffectsMeasure, &Base::Validate::Positive<double>)
        .Property(ComboBox::IsEditableProperty, false, AffectsMeasure | AffectsRender)
        .Property(ComboBox::IsReadOnlyProperty, false, AffectsRender)
        .Property(ComboBox::TextProperty, Base::String{}, AffectsMeasure | BindsTwoWayByDefault)
        .Property(ComboBox::PlaceholderProperty, Base::String{}, AffectsMeasure | AffectsRender)
        .Property(ComboBox::SelectionBoxTextProperty, Base::String{})
        .Property(ComboBox::SelectionBoxItemProperty, Meta::Value::NullObject(Meta::TypeOf<Base::Object>()))
        .Override(Aero::UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None)
        .TemplatePart("PART_EditableTextBox", TypeOf<TextBox>())
        .TemplatePart("PART_Popup", TypeOf<Popup>())
        .Factory();

    Register<ComboBoxItem>(context)
        .Property(ComboBoxItem::IsSelectedProperty, false, AffectsRender | BindsTwoWayByDefault)
        .Override(Aero::UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None)
        .Factory();

    Register<Page>(context)
        .Factory();

    Register<Popup>(context)
        .Event(Popup::OpenedEvent)
        .Event(Popup::ClosedEvent)
        .Property(Popup::IsOpenProperty, false, AffectsMeasure | AffectsRender | BindsTwoWayByDefault)
        .Property(Popup::PlacementProperty, PlacementMode::Bottom, AffectsArrange)
        .Property(Popup::HorizontalOffsetProperty, 0.0, AffectsArrange, &Base::Validate::Finite<double>)
        .Property(Popup::VerticalOffsetProperty, 0.0, AffectsArrange, &Base::Validate::Finite<double>)
        .Property(Popup::StaysOpenProperty, true)
        .Property(Popup::MatchPlacementTargetWidthProperty, false, AffectsArrange)
        .Property(Popup::PlacementTargetProperty, Base::Ref<UIElement>{}, AffectsArrange)
        .Property(Popup::PopupAnimationProperty, PopupAnimation::None, AffectsRender)
        .Property(Popup::AllowsTransparencyProperty, false, AffectsRender)
        .Factory();

    Register<TreeView>(context)
        .Event(TreeView::SelectedItemChangedEvent)
        .Property(TreeView::SelectedItemProperty, Base::Ref<Base::Object>{})
        .Factory();

    Register<TreeViewItem>(context)
        .Event(TreeViewItem::ExpandedEvent)
        .Event(TreeViewItem::CollapsedEvent)
        .Event(TreeViewItem::SelectedEvent)
        .Event(TreeViewItem::UnselectedEvent)
        .Property(TreeViewItem::IconProperty, Base::String{}, AffectsMeasure)
        .Property(TreeViewItem::IsExpandedProperty, false, AffectsMeasure | BindsTwoWayByDefault)
        .Property(TreeViewItem::IsSelectedProperty, false, AffectsRender | BindsTwoWayByDefault)
        .Override(Aero::UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None)
        .Content<Base::Object>("Items", ContentKind::Collection, &AddTreeViewItem, &ClearTreeViewItems)
        .Factory();

    Register<Menu>(context)
        .Factory();

    Register<MenuItem>(context)
        .Event(MenuItem::ClickEvent)
        .Property(MenuItem::InputGestureTextProperty, Base::String{}, AffectsMeasure)
        .Property(MenuItem::IsCheckableProperty, false, AffectsMeasure)
        .Property(MenuItem::IsCheckedProperty, false, AffectsRender | BindsTwoWayByDefault)
        .Property(MenuItem::IsHighlightedProperty, false, AffectsRender)
        .Property(MenuItem::IsSubmenuOpenProperty, false, AffectsMeasure | AffectsRender | BindsTwoWayByDefault)
        .Property(MenuItem::RoleProperty, MenuItemRole::TopLevelItem, AffectsMeasure | AffectsRender)
        .Property(MenuItem::CommandProperty, Base::Ref<ICommand>{})
        .Property(MenuItem::CommandParameterProperty, Value::NullObject(TypeOf<Base::Object>()))
        .Property(MenuItem::IconProperty, Value::NullObject(TypeOf<Base::Object>()), AffectsMeasure)
        .Factory();

    Register<ContextMenu>(context)
        .Event(ContextMenu::OpenedEvent)
        .Event(ContextMenu::ClosedEvent)
        .Property(ContextMenu::IsOpenProperty, false, AffectsMeasure | AffectsRender | BindsTwoWayByDefault)
        .Property(ContextMenu::PlacementTargetProperty, Base::Ref<UIElement>{})
        .Factory();

    Register<ContextMenuService>(context, TypeFlags::Abstract)
        .Property(ContextMenuService::ContextMenuProperty, Base::Ref<ContextMenu>{});

    Register<GridViewColumnHeader>(context)
        .Property(GridViewColumnHeader::RoleProperty, GridViewColumnHeaderRole::Normal)
        .Factory();

    Register<GridViewColumn>(context)
        .Property(GridViewColumn::HeaderProperty, Value::NullObject(TypeOf<Base::Object>()))
        .Property(GridViewColumn::WidthProperty, 100.0, FrameworkPropertyMetadataOptions::None, &Base::Validate::NonNegative<double>)
        .Property(GridViewColumn::CellTemplateProperty, Base::Ref<DataTemplate>{})
        .Property(GridViewColumn::HeaderTemplateProperty, Base::Ref<DataTemplate>{})
        .Property(GridViewColumn::DisplayMemberPathProperty, Base::String{})
        .Property(GridViewColumn::DisplayMemberBindingProperty, Base::Ref<Data::Binding>{})
        .Property(GridViewColumn::HeaderContainerStyleProperty, Base::Ref<Style>{})
        .Factory();

    Register<GridView>(context)
        .Property<bool, &GridView::GetAllowsColumnReorder, &GridView::SetAllowsColumnReorder>("AllowsColumnReorder")
        .Property<Base::Ref<Style>, &GridView::GetColumnHeaderContainerStyle, &GridView::SetColumnHeaderContainerStyle>("ColumnHeaderContainerStyle", PropertyFlags::Structural)
        .Property<Base::Ref<Base::Object>, &GridView::GetColumnHeaderContextMenu, &GridView::SetColumnHeaderContextMenu>("ColumnHeaderContextMenu", PropertyFlags::Structural)
        .Property<Base::Ref<Base::Object>, &GridView::GetColumnHeaderTemplate, &GridView::SetColumnHeaderTemplate>("ColumnHeaderTemplate", PropertyFlags::Structural)
        .Property<Base::Ref<Base::Object>, &GridView::GetColumnHeaderTemplateSelector, &GridView::SetColumnHeaderTemplateSelector>("ColumnHeaderTemplateSelector", PropertyFlags::Structural)
        .Property<Base::Ref<Base::Object>, &GridView::GetColumnHeaderToolTip, &GridView::SetColumnHeaderToolTip>("ColumnHeaderToolTip", PropertyFlags::Structural)
        .Property<Base::Ref<Base::Object>, &GridView::GetColumnsObject, &GridView::SetColumnsObject>("Columns", PropertyFlags::Structural)
        .Content<Base::Object>("ColumnItems", ContentKind::Collection, &AddGridViewColumn, &ClearGridViewColumns)
        .Factory();

    Register<GridViewHeaderRowPresenter>(context)
        .Property(GridViewHeaderRowPresenter::AllowsColumnReorderProperty, false)
        .Property(GridViewHeaderRowPresenter::ColumnHeaderContainerStyleProperty, Base::Ref<Base::Object>{})
        .Property(GridViewHeaderRowPresenter::ColumnHeaderContextMenuProperty, Base::Ref<Base::Object>{})
        .Property(GridViewHeaderRowPresenter::ColumnHeaderTemplateProperty, Base::Ref<Base::Object>{})
        .Property(GridViewHeaderRowPresenter::ColumnHeaderTemplateSelectorProperty, Base::Ref<Base::Object>{})
        .Property(GridViewHeaderRowPresenter::ColumnHeaderToolTipProperty, Base::Ref<Base::Object>{})
        .Property(GridViewHeaderRowPresenter::ColumnsProperty, Base::Ref<Base::Object>{})
        .Factory();

    Register<GridViewRowPresenter>(context)
        .Property(GridViewRowPresenter::ColumnsProperty, Base::Ref<Base::Object>{})
        .Property(GridViewRowPresenter::ContentProperty, Base::Ref<Base::Object>{})
        .Factory();

    Register<ListView>(context)
        .Property(ListView::ViewProperty, Base::Ref<GridView>{}, AffectsMeasure)
        .Factory();

    Register<ListViewItem>(context)
        .Override(Aero::UIElement::IsTabStopProperty, true, FrameworkPropertyMetadataOptions::None)
        .Factory();

    Register<Separator>(context)
        .Factory();

    Register<ToolBar>(context)
        .Property(ToolBar::HeaderProperty, Meta::Value::NullObject(Meta::TypeOf<Base::Object>()), AffectsMeasure)
        .Property(ToolBar::HeaderTemplateProperty, Base::Ref<DataTemplate>{}, AffectsMeasure)
        .Property(ToolBar::OrientationProperty, Orientation::Horizontal, AffectsMeasure)
        .Property(ToolBar::OverflowCapacityProperty, UINT32_MAX, AffectsMeasure)
        .Property(ToolBar::IsOverflowOpenProperty, false, AffectsRender)
        .Property(ToolBar::HasOverflowItemsProperty, false)
        .Property(ToolBar::OverflowItemCountProperty, std::uint32_t{0U})
        .Factory();

    Register<ToolBarPanel>(context)
        .Factory();

    Register<ToolBarOverflowPanel>(context)
        .Factory();

    Register<ToolBarTray>(context, TypeFlags::Abstract)
        .Property(ToolBarTray::IsLockedProperty, false);

    Register<StatusBar>(context)
        .Property(StatusBar::IsSizingGripVisibleProperty, true, AffectsRender)
        .Factory();

    Register<StatusBarItem>(context)
        .Factory();

    Register<ToolTip>(context)
        .Property(ToolTip::InitialShowDelayProperty, std::uint32_t{500U})
        .Property(ToolTip::ShowDurationProperty, std::uint32_t{5000U})
        .Factory();

    Register<ToolTipService>(context, TypeFlags::Abstract)
        .Property(ToolTipService::ToolTipProperty, Base::Ref<ToolTip>{})
        .Property(ToolTipService::InitialShowDelayProperty, std::uint32_t{500U})
        .Property(ToolTipService::ShowDurationProperty, std::uint32_t{5000U});

    Register<HeaderedContentControl>(context)
        .Property(HeaderedContentControl::HeaderProperty, Meta::Value::NullObject(Meta::TypeOf<Base::Object>()), AffectsMeasure)
        .Property(HeaderedContentControl::HeaderTemplateProperty, Base::Ref<DataTemplate>{}, AffectsMeasure)
        .Factory<BasicHeaderedContentControl>();

    Register<GroupBox>(context)
        .Factory();

    Register<Label>(context)
        .Factory();

    Register<Expander>(context)
        .Event(Expander::ExpandedEvent)
        .Event(Expander::CollapsedEvent)
        .Property(Expander::IsExpandedProperty, false, AffectsMeasure)
        .Property(Expander::ExpandDirectionProperty, ExpandDirection::Down, AffectsMeasure)
        .Factory();

    Register<TabItem>(context)
        .Property(TabItem::IsSelectedProperty, false, AffectsRender)
        .Factory();

    Register<TabControl>(context)
        .Property(TabControl::SelectedContentProperty, Meta::Value::NullObject(Meta::TypeOf<Base::Object>()))
        .Property(TabControl::ContentTemplateProperty, Base::Ref<DataTemplate>{}, AffectsMeasure)
        .Property(TabControl::TabStripPlacementProperty, Dock::Top, AffectsMeasure)
        .Factory();

    Register<TabPanel>(context)
        .Factory();

    return {};
}
