// Controls metadata: layout (panels + text/media).
// ---- From Panels.inl (merged; registration order preserved) ----
// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsPanels(
    ::Aero::Meta::Registration& context) noexcept {
    Register<StackPanel>(context)
        .Property(StackPanel::OrientationProperty, Orientation::Vertical, AffectsMeasure)
        .Factory();

    Register<DockPanel>(context)
        .Property(DockPanel::LastChildFillProperty, true, AffectsArrange)
        .Property(DockPanel::DockProperty, Dock::Left, AffectsParentMeasure)
        .Factory();

    Register<WrapPanel>(context)
        .Property(WrapPanel::OrientationProperty, Orientation::Horizontal, AffectsMeasure)
        .Property(WrapPanel::ItemWidthProperty, 0.0, AffectsMeasure, &Base::Validate::NonNegative<double>)
        .Property(WrapPanel::ItemHeightProperty, 0.0, AffectsMeasure, &Base::Validate::NonNegative<double>)
        .Factory();

    Register<UniformGrid>(context)
        .Property(UniformGrid::RowsProperty, std::uint32_t{0}, AffectsMeasure)
        .Property(UniformGrid::ColumnsProperty, std::uint32_t{0}, AffectsMeasure)
        .Property(UniformGrid::FirstColumnProperty, std::uint32_t{0}, AffectsMeasure | AffectsArrange)
        .Factory();

    Register<VirtualizingPanel>(context, TypeFlags::Abstract)
        .Property(VirtualizingPanel::ScrollUnitProperty, ScrollUnit::Item, AffectsParentMeasure)
        .Property(VirtualizingPanel::VirtualizationModeProperty, VirtualizationMode::Standard, AffectsParentMeasure);

    Register<VirtualizationCacheLength>(context)
        .Field<&VirtualizationCacheLength::cacheBeforeViewport>("CacheBeforeViewport")
        .Field<&VirtualizationCacheLength::cacheAfterViewport>("CacheAfterViewport")
        .ValueSemantics();

    Register<VirtualizingStackPanel>(context)
        .Property(VirtualizingStackPanel::OrientationProperty, Orientation::Vertical, AffectsMeasure)
        .Property(VirtualizingStackPanel::OverscanCountProperty, std::uint32_t{2}, AffectsMeasure)
        .Property(VirtualizingStackPanel::EstimatedItemExtentProperty, 24.0, AffectsMeasure, &Base::Validate::Positive<double>)
        .Property(VirtualizingStackPanel::CacheLengthProperty, VirtualizationCacheLength{}, AffectsMeasure)
        .Property(VirtualizingStackPanel::CacheLengthUnitProperty, VirtualizationCacheLengthUnit::Item, AffectsMeasure)
        .Factory();

    Register<VirtualizingWrapPanel>(context)
        .Property(VirtualizingWrapPanel::ItemWidthProperty, 0.0, AffectsMeasure, &Base::Validate::NonNegative<double>)
        .Property(VirtualizingWrapPanel::ItemHeightProperty, 0.0, AffectsMeasure, &Base::Validate::NonNegative<double>)
        .Factory();

    Register<Canvas>(context)
        .Property(Canvas::LeftProperty, std::numeric_limits<double>::infinity(), AffectsParentArrange)
        .Property(Canvas::TopProperty, std::numeric_limits<double>::infinity(), AffectsParentArrange)
        .Property(Canvas::RightProperty, std::numeric_limits<double>::infinity(), AffectsParentArrange)
        .Property(Canvas::BottomProperty, std::numeric_limits<double>::infinity(), AffectsParentArrange)
        .Factory();

    Register<ColumnDefinition>(context)
        .Property<GridLength, &ColumnDefinition::GetWidth, &ColumnDefinition::SetWidth>("Width", PropertyFlags::Structural)
        .Property<double, &ColumnDefinition::GetMaxWidth, &ColumnDefinition::SetMaxWidth>("MaxWidth", PropertyFlags::Structural)
        .Property<Base::String, &ColumnDefinition::GetSharedSizeGroup, &ColumnDefinition::SetSharedSizeGroup>("SharedSizeGroup", PropertyFlags::Structural)
        .Factory();

    Register<RowDefinition>(context)
        .Property<GridLength, &RowDefinition::GetHeight, &RowDefinition::SetHeight>("Height", PropertyFlags::Structural)
        .Property<double, &RowDefinition::GetMaxHeight, &RowDefinition::SetMaxHeight>("MaxHeight", PropertyFlags::Structural)
        .Property<Base::String, &RowDefinition::GetSharedSizeGroup, &RowDefinition::SetSharedSizeGroup>("SharedSizeGroup", PropertyFlags::Structural)
        .Factory();

    Register<Grid>(context)
        .Property(Grid::IsSharedSizeScopeProperty, false)
        .Property(Grid::ColumnDefinitionsTextProperty, Base::String{}, AffectsMeasure, &ValidateGridDefinitionsText, &OnGridColumnsChanged)
        .Property(Grid::RowDefinitionsTextProperty, Base::String{}, AffectsMeasure, &ValidateGridDefinitionsText, &OnGridRowsChanged)
        .Collection<ColumnDefinition>("ColumnDefinitions", &AddGridColumnDefinition, &ClearGridColumnDefinitions)
        .Collection<RowDefinition>("RowDefinitions", &AddGridRowDefinition, &ClearGridRowDefinitions)
        .Property(Grid::RowProperty, std::uint32_t{0}, AffectsParentMeasure)
        .Property(Grid::ColumnProperty, std::uint32_t{0}, AffectsParentMeasure)
        .Property(Grid::RowSpanProperty, std::uint32_t{1}, AffectsParentMeasure, &Base::Validate::Positive<std::uint32_t>)
        .Property(Grid::ColumnSpanProperty, std::uint32_t{1}, AffectsParentMeasure, &Base::Validate::Positive<std::uint32_t>)
        .Factory();

    Register<Border>(context)
        .Property(Border::BackgroundProperty, Base::Ref<Media::Brush>{}, AffectsRender)
        .Property(Border::BorderBrushProperty, Base::Ref<Media::Brush>{}, AffectsRender)
        .Property(Border::BorderThicknessProperty, Aero::Thickness{}, AffectsMeasure | AffectsRender, &ValidateThicknessValue)
        .Property(Border::CornerRadiusProperty, Aero::CornerRadius{}, AffectsRender, &ValidateCornerRadiusValue)
        .Property(Border::PaddingProperty, Aero::Thickness{}, AffectsMeasure, &ValidateThicknessValue)
        .Factory();

    return {};
}

// ---- From TextMedia.inl (merged; registration order preserved) ----
// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsTextMedia(
    ::Aero::Meta::Registration& context) noexcept {
    namespace Docs = Aero::Documents; // alias — do not using namespace Documents (Span collision)
    using namespace Aero::Media;
    Base::Result<void> status;

    const auto makeBrush = [](Base::Color color) noexcept {
        Base::Result<Base::Ref<Brush>> made = MakeSolidColorBrush(color);
        return made ? std::move(made).Value() : Base::Ref<Brush>{};
    };
    const Base::Ref<Brush> black = makeBrush({0.0F, 0.0F, 0.0F, 1.0F});

    Register<TextBlock>(context)
        .Property(TextBlock::TextProperty, Base::String{}, AffectsMeasure)
        .Property(TextBlock::BackgroundProperty, Base::Ref<Brush>{}, AffectsRender)
        .Property(TextBlock::StrokeProperty, Base::Ref<Brush>{}, AffectsRender)
        .AddOwner(TextBlock::FontSizeProperty, 15.0, Inherits | AffectsMeasure, &ValidatePositiveFiniteDouble)
        .Property(TextBlock::FontWeightProperty, FontWeight::Normal, AffectsMeasure)
        .Property(TextBlock::FontStyleProperty, FontStyle::Normal, AffectsMeasure)
        .Property(TextBlock::TextDecorationsProperty, TextDecorations::None, AffectsRender)
        .Property(TextBlock::StrokeThicknessProperty, 0.0, AffectsMeasure | AffectsRender, &Base::Validate::NonNegative<double>)
        .Property(TextBlock::TextWrappingProperty, TextWrapping::NoWrap, AffectsMeasure)
        .Property(TextBlock::TextTrimmingProperty, TextTrimming::None, AffectsMeasure)
        .Property(TextBlock::TextAlignmentProperty, TextAlignment::Left, AffectsMeasure)
        .Property(TextBlock::LineHeightProperty, 0.0, AffectsMeasure, &Base::Validate::NonNegative<double>)
        .Property(TextBlock::PaddingProperty, Aero::Thickness{}, AffectsMeasure | AffectsArrange, &ValidateThicknessValue)
        .Property<Value, &TextBlock::GetMetadataInlines, &TextBlock::SetInlineValue>("Inlines", PropertyFlags::AnyValue | PropertyFlags::Collection | PropertyFlags::Structural)
        .ContentAccessor(MakeMemberId(TextBlock::StaticTypeId(), MemberKind::Property, "Inlines"), ContentKind::Collection, &AddTextBlockInline, &ClearTextBlockInlines, ContentFlags::None)
        .Factory();

    Register<Docs::TextElement>(context, TypeFlags::Abstract)
        .AddOwner(Docs::TextElement::FontFamilyProperty, Aero::FrameworkElement::FontFamilyProperty, Base::Ref<FontFamily>{}, Inherits | AffectsMeasure)
        .Property(Docs::TextElement::FontWeightProperty, FontWeight::Normal, Inherits | AffectsMeasure)
        .AddOwner(Docs::TextElement::ForegroundProperty, Aero::FrameworkElement::ForegroundProperty, black, Inherits)
        .Property(Docs::TextElement::FontSizeProperty, 15.0, Inherits, &ValidatePositiveFiniteDouble)
        .Property(Docs::TextElement::FontStyleProperty, FontStyle::Normal, Inherits)
        .Property(Docs::TextElement::TextDecorationsProperty, TextDecorations::None, Inherits);

    Register<Docs::Inline>(context, TypeFlags::Abstract);

    Register<Docs::Run>(context)
        .Property(Docs::Run::TextProperty, FrameworkPropertyMetadata(Base::String{}).Structural())
        .Content(Docs::Run::TextProperty.Id())
        .Factory();

    Register<Docs::Span>(context)
        .Property<Value, &Docs::Span::GetMetadataInlines, &Docs::Span::SetInlineValue>("Inlines", PropertyFlags::AnyValue | PropertyFlags::Collection | PropertyFlags::Structural)
        .ContentAccessor(MakeMemberId(Docs::Span::StaticTypeId(), MemberKind::Property, "Inlines"), ContentKind::Collection, &AddSpanInline, &ClearSpanInlines, ContentFlags::None)
        .Factory();

    Register<Docs::Bold>(context)
        .Override(Docs::TextElement::FontWeightProperty, FontWeight::Bold, AffectsMeasure)
        .Factory();

    Register<Docs::Italic>(context)
        .Override(Docs::TextElement::FontStyleProperty, FontStyle::Italic, AffectsMeasure)
        .Factory();

    Register<Docs::Underline>(context)
        .Override(Docs::TextElement::TextDecorationsProperty, TextDecorations::Underline, AffectsRender)
        .Factory();

    Register<Docs::LineBreak>(context)
        .Factory();

    Register<Docs::RequestNavigateEventArgs>(context);

    Register<Docs::Hyperlink>(context)
        .Event(Docs::Hyperlink::ClickEvent)
        .Event(Docs::Hyperlink::RequestNavigateEvent)
        .Property(Docs::Hyperlink::NavigateUriProperty, Base::String{})
        .Property(Docs::Hyperlink::CommandProperty, Base::Ref<ICommand>{})
        .Property(Docs::Hyperlink::CommandParameterProperty, Value::NullObject(TypeOf<Base::Object>()))
        .Property(Docs::Hyperlink::CommandTargetProperty, Base::Ref<UIElement>{})
        .Override(Docs::TextElement::TextDecorationsProperty, TextDecorations::Underline, AffectsRender)
        .Factory();

    Register<Docs::InlineUIContainer>(context)
        .Property(Docs::InlineUIContainer::ChildProperty, Base::Ref<UIElement>{})
        .Factory();

    Register<Docs::Adorner>(context)
        .Factory();

    Register<Docs::AdornerLayer>(context)
        .Factory();

    Register<Docs::AdornerDecorator>(context)
        .Factory();

    Register<Image>(context)
        .Property(Image::SourceProperty, Base::Ref<ImageSource>{}, AffectsMeasure | AffectsRender)
        .Property(Image::StretchProperty, Stretch::Uniform, AffectsMeasure | AffectsRender)
        .Property(Image::StretchDirectionProperty, StretchDirection::Both, AffectsMeasure | AffectsRender)
        .Factory();

    Register<Shape>(context, TypeFlags::Abstract)
        .Property(Shape::FillProperty, FrameworkPropertyMetadata(Base::Ref<Brush>{}, AffectsRender).Changed(&OnShapeFillChanged))
        .Property(Shape::StrokeProperty, FrameworkPropertyMetadata(Base::Ref<Brush>{}, AffectsRender).Changed(&OnShapeFillChanged))
        .Property(Shape::PenProperty, FrameworkPropertyMetadata(Base::Ref<Pen>{}, AffectsMeasure | AffectsRender).Changed(&OnShapePenChanged))
        .Property(Shape::StrokeThicknessProperty, 1.0, AffectsMeasure | AffectsRender, &Base::Validate::NonNegative<double>)
        .Property(Shape::StretchProperty, Stretch::Fill, AffectsMeasure | AffectsRender);

    Register<Rectangle>(context)
        .Property(Rectangle::RadiusXProperty, 0.0, AffectsRender, &Base::Validate::NonNegative<double>)
        .Property(Rectangle::RadiusYProperty, 0.0, AffectsRender, &Base::Validate::NonNegative<double>)
        .Factory();

    Register<Ellipse>(context)
        .Factory();

    Register<Path>(context)
        .Property(Path::DataProperty, FrameworkPropertyMetadata(Base::Ref<Geometry>{}, AffectsMeasure | AffectsRender).Changed(&OnPathDataChanged))
        .Property(Path::FillRuleProperty, FillRule::EvenOdd, AffectsRender, &OnPathFillRuleChanged)
        .Override(Shape::FillProperty, Base::Ref<Brush>{}, AffectsRender, &OnPathColorChanged)
        .Override(Shape::StrokeProperty, Base::Ref<Brush>{}, AffectsRender, &OnPathColorChanged)
        .Override(Shape::StrokeThicknessProperty, 1.0, AffectsMeasure | AffectsRender, &Base::Validate::NonNegative<double>, &OnPathDoubleChanged)
        .Property(Path::StrokeLineJoinProperty, PenLineJoin::Miter, AffectsRender, &OnPathLineJoinChanged)
        .Property(Path::StrokeStartLineCapProperty, PenLineCap::Flat, AffectsRender, &OnPathLineCapChanged)
        .Property(Path::StrokeEndLineCapProperty, PenLineCap::Flat, AffectsRender, &OnPathLineCapChanged)
        .Property(Path::TrimStartProperty, 0.0, AffectsRender, &ValidateNormalizedDouble, &OnPathDoubleChanged)
        .Property(Path::TrimEndProperty, 1.0, AffectsRender, &ValidateNormalizedDouble, &OnPathDoubleChanged)
        .Property(Path::StrokeDashArrayProperty, Base::String{}, AffectsRender, &OnPathStringChanged)
        .Property(Path::StrokeDashOffsetProperty, 0.0, AffectsRender, &OnPathDoubleChanged)
        .Property(Path::DashStyleProperty, Base::Ref<DashStyle>{}, AffectsRender, &OnPathDashStyleChanged)
        .Override(Shape::StretchProperty, Stretch::None, AffectsMeasure | AffectsRender)
        .Factory();

    Register<Line>(context)
        .Property(Line::X1Property, 0.0, AffectsMeasure | AffectsRender)
        .Property(Line::Y1Property, 0.0, AffectsMeasure | AffectsRender)
        .Property(Line::X2Property, 0.0, AffectsMeasure | AffectsRender)
        .Property(Line::Y2Property, 0.0, AffectsMeasure | AffectsRender)
        .Factory();

    Register<Polygon>(context)
        .Property(Polygon::FillRuleProperty, FillRule::EvenOdd, AffectsRender)
        .Property<Base::String, &Polygon::SetPointsText>("Points", PropertyFlags::None)
        .Factory();

    Register<Polyline>(context)
        .Property<Base::String, &Polyline::SetPointsText>("Points", PropertyFlags::None)
        .Factory();

    const Base::Ref<Brush> selection = makeBrush({46.0F / 255.0F, 174.0F / 255.0F, 235.0F / 255.0F, 1.0F});
    const Base::Ref<Brush> placeholder = makeBrush({123.0F / 255.0F, 128.0F / 255.0F, 133.0F / 255.0F, 1.0F});

    Register<TextBoxBase>(context, TypeFlags::Abstract)
        .Property(TextBoxBase::SelectionBrushProperty, selection, AffectsRender)
        .Property(TextBoxBase::SelectionOpacityProperty, 0.25, AffectsRender, &ValidateNormalizedDouble)
        .Property(TextBoxBase::CaretBrushProperty, black, AffectsRender);

    Register<TextBox>(context)
        .Event(TextBox::TextChangedEvent)
        .Property(TextBox::TextProperty, FrameworkPropertyMetadata(Base::String{}, AffectsMeasure | AffectsRender | BindsTwoWayByDefault).UpdateSource(UpdateSourceTrigger::LostFocus).Coerce(&CoerceTextBoxText))
        .Property(TextBox::IsReadOnlyProperty, false, AffectsRender)
        .Property(TextBox::MaxLengthProperty, std::uint32_t{0})
        .Property(TextBox::AcceptsReturnProperty, false, AffectsMeasure | AffectsRender)
        .Property(TextBox::TextWrappingProperty, TextWrapping::NoWrap, AffectsMeasure | AffectsRender)
        .Property(TextBox::PlaceholderProperty, Base::String{}, AffectsMeasure)
        .Property(TextBox::PlaceholderForegroundProperty, placeholder, AffectsRender)
        .Property(TextBox::FontSizeProperty, 15.0, AffectsMeasure, &ValidatePositiveFiniteDouble)
        .Property(TextBox::FontWeightProperty, FontWeight::Normal, AffectsMeasure)
        .Property(TextBox::FontStyleProperty, FontStyle::Normal, AffectsMeasure)
        .Property(TextBox::TextAlignmentProperty, TextAlignment::Left, AffectsMeasure)
        .Property(TextBox::MaxLinesProperty, std::uint32_t{0}, AffectsMeasure | AffectsRender)
        .Property(TextBox::MinLinesProperty, std::uint32_t{1}, AffectsMeasure | AffectsRender, &Base::Validate::Positive<std::uint32_t>)
        .Factory();

    Base::String defaultPasswordChar;
    status = defaultPasswordChar.Assign(Base::StringView(u8"\u2022"));
    if (!status) return status.GetStatus();

    Register<PasswordBox>(context)
        .Event(PasswordBox::PasswordChangedEvent)
        .Property<Base::String, &PasswordBox::GetPassword, &PasswordBox::SetPassword>("Password", PropertyFlags::None)
        .Property(PasswordBox::PasswordCharProperty, std::move(defaultPasswordChar), AffectsMeasure, &ValidatePasswordChar)
        .Property(PasswordBox::MaxLengthProperty, std::uint32_t{0}, AffectsMeasure)
        .Property(PasswordBox::PlaceholderProperty, Base::String{}, AffectsMeasure | AffectsRender)
        .TemplatePart("PART_ContentHost", TypeOf<ScrollViewer>())
        .Factory();

    Base::String defaultContentSource;
    status = defaultContentSource.Assign(Base::StringView("Content"));
    if (!status) return status.GetStatus();

    Register<ContentPresenter>(context)
        .Property(ContentPresenter::ContentProperty, FrameworkPropertyMetadata(Meta::Value::NullObject(Meta::TypeOf<Base::Object>()), AffectsMeasure).Structural().Changed(&ContentPresenter::OnContentPropertyChanged))
        .Property(ContentPresenter::ContentTemplateProperty, Base::Ref<Base::Object>{}, AffectsMeasure)
        .Property(ContentPresenter::ContentSourceProperty, std::move(defaultContentSource))
        .ContentAccessor(MakeMemberId(ContentPresenter::StaticTypeId(), MemberKind::Property, "Content"), ContentKind::Single, &SetContentPresenterContent, &ClearContentPresenterContent, ContentFlags::Visual)
        .Factory();

    return {};
}
