// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsPrimitives(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    auto panel = Meta::Register<Panel>(
        context, TypeFlags::Abstract);
    panel
        .Property(
            Panel::BackgroundProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Media::Brush>{})
                .AffectsRender())
        .Property(
            Panel::ZIndexProperty,
            FrameworkPropertyMetadata(std::int32_t{0})
                .AffectsParentArrange())
        .Property(
            Panel::IsItemsHostProperty,
            FrameworkPropertyMetadata(false))
        .Content<Aero::UIElement>(
            "Children", ContentKind::Collection,
            &SetPanelContent, &ClearPanelContent,
            ContentFlags::Visual);
    status = panel.Result();
    if (!status) return status.GetStatus();

    auto decorator = Meta::Register<Decorator>(context);
    decorator.Content<Aero::UIElement>(
        "Content", ContentKind::Single,
        &SetDecoratorContent, &ClearDecoratorContent,
        ContentFlags::Visual)
        .Factory();
    status = decorator.Result();
    if (!status) return status.GetStatus();

    auto bulletDecorator = Meta::Register<BulletDecorator>(context);
    // Bullet is the explicit WPF property-element name. Treating the same
    // visual collection as implicit content lets the following child element
    // populate the regular content slot while retaining both tree edges.
    bulletDecorator
        .Property(
            BulletDecorator::BackgroundProperty,
            FrameworkPropertyMetadata(Base::Ref<Aero::Media::Brush>{})
                .AffectsRender())
        .Content<Aero::UIElement>(
            "Bullet", ContentKind::Collection,
            &AddBulletDecoratorContent,
            &ClearBulletDecoratorContent,
            ContentFlags::Visual)
        .Factory();
    status = bulletDecorator.Result();
    if (!status) return status.GetStatus();

    auto viewbox = Meta::Register<Viewbox>(context);
    viewbox
        .Property(
            Viewbox::StretchProperty,
            FrameworkPropertyMetadata(Stretch::Uniform)
                .AffectsMeasure())
        .Property(
            Viewbox::StretchDirectionProperty,
            FrameworkPropertyMetadata(StretchDirection::Both)
                .AffectsMeasure())
        .Content<Aero::UIElement>(
            "Content", ContentKind::Single,
            &SetDecoratorContent, &ClearDecoratorContent,
            ContentFlags::Visual)
        .Factory();
    status = viewbox.Result();
    if (!status) return status.GetStatus();

    auto control = Meta::Register<Control>(context);
    control
        .Event(
            Control::PreviewMouseDoubleClickEvent,
            RoutingStrategy::Tunnel)
        .Event(Control::MouseDoubleClickEvent)
        .Override(
            UIElement::FocusableProperty,
            FrameworkPropertyMetadata(true))
        .Override(
            UIElement::IsTabStopProperty,
            FrameworkPropertyMetadata(true))
        .Property(
            Control::BackgroundProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Media::Brush>{})
                .AffectsRender())
        .Property(
            Control::BorderBrushProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Media::Brush>{})
                .AffectsRender())
        .Property(
            Control::BorderThicknessProperty,
            FrameworkPropertyMetadata(Aero::Thickness{})
                .AffectsMeasure()
                .AffectsRender()
                .Validate(&ValidateThicknessValue))
        .Property(
            Control::PaddingProperty,
            FrameworkPropertyMetadata(Aero::Thickness{})
                .AffectsMeasure()
                .Validate(&ValidateThicknessValue))
        .Property(
            Control::FontWeightProperty,
            FrameworkPropertyMetadata(FontWeight::Normal)
                .AffectsMeasure())
        .Property(
            Control::HorizontalContentAlignmentProperty,
            FrameworkPropertyMetadata(
                Aero::HorizontalAlignment::Left)
                .AffectsArrange())
        .Property(
            Control::VerticalContentAlignmentProperty,
            FrameworkPropertyMetadata(
                Aero::VerticalAlignment::Top)
                .AffectsArrange())
        .Property(
            Control::FontSizeProperty,
            FrameworkPropertyMetadata(16.0)
                .Inherits()
                .AffectsMeasure()
                .Validate(
                    &ValidatePositiveFiniteDouble))
        .Property(
            Control::FocusVisualStyleProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Aero::Style>{}))
        .Property(
            Control::OverridesDefaultStyleProperty,
            FrameworkPropertyMetadata(false))
        .Property(
            Control::TemplateProperty,
            FrameworkPropertyMetadata(Base::Ref<ControlTemplate>{})
                .AffectsMeasure())
        .Factory(&CreateBasicControl);
    status = control.Result();
    if (!status) return status.GetStatus();

    auto contentControl = Meta::Register<ContentControl>(context);
    contentControl
        .Property(
            ContentControl::ContentProperty,
            FrameworkPropertyMetadata(
                Meta::Value::NullObject(
                    Meta::TypeOf<Base::Object>()))
                .AffectsMeasure()
                .Structural()
                .Changed(
                    &AeroGuiInternal::
                        OnContentControlPropertyChanged))
        .Property(
            ContentControl::ContentTemplateProperty,
            FrameworkPropertyMetadata(Base::Ref<Base::Object>{})
                .AffectsMeasure())
        .Property(
            ContentControl::
                ContentTemplateSelectorProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Base::Object>{})
                .AffectsMeasure())
        .ContentAccessor(
            MakeMemberId(
                ContentControl::StaticTypeId(),
                MemberKind::Property,
                "Content"),
            ContentKind::Single,
            &SetContentControlContent,
            &ClearContentControlContent,
            ContentFlags::Visual)
        .Factory(&CreateBasicContentControl);
    status = contentControl.Result();
    if (!status) return status.GetStatus();

    // UserControl is a concrete ContentControl root for LoadComponent. Content
    // and resource semantics are inherited from ContentControl; the distinct
    // factory preserves the application's registered runtime type.
    status = Meta::Register<UserControl>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto buttonBase = Meta::Register<ButtonBase>(
        context, TypeFlags::Abstract);
    buttonBase
        .Event(ButtonBase::ClickEvent)
        .Property(
            ButtonBase::ClickModeProperty,
            FrameworkPropertyMetadata(ClickMode::Release))
        .Property(
            ButtonBase::CommandProperty,
            FrameworkPropertyMetadata(Base::Ref<ICommand>{}))
        .Property(
            ButtonBase::CommandParameterProperty,
            FrameworkPropertyMetadata(Value::NullObject(
                TypeOf<Base::Object>())))
        .Property(
            ButtonBase::CommandTargetProperty,
            FrameworkPropertyMetadata(Base::Ref<UIElement>{}))
        .Override(
            UIElement::IsEnabledProperty,
            FrameworkPropertyMetadata(true)
                .Inherits()
                .AffectsRender()
                .Coerce(&CoerceButtonEnabled))
        .Override(
            UIElement::IsTabStopProperty,
            FrameworkPropertyMetadata(true));
    status = buttonBase.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Button>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto repeatButton = Meta::Register<RepeatButton>(context);
    repeatButton
        .Property(
            RepeatButton::DelayProperty,
            FrameworkPropertyMetadata(std::uint32_t{400}))
        .Property(
            RepeatButton::IntervalProperty,
            FrameworkPropertyMetadata(std::uint32_t{100})
                .Validate(&::Aero::Base::Validate::Positive<std::uint32_t>))
        .Override(
            ButtonBase::ClickModeProperty,
            FrameworkPropertyMetadata(ClickMode::Press))
        .Factory();
    status = repeatButton.Result();
    if (!status) return status.GetStatus();

    auto toggleButton = Meta::Register<ToggleButton>(context);
    toggleButton
        .Event(ToggleButton::CheckedEvent)
        .Event(ToggleButton::UncheckedEvent)
        .Event(ToggleButton::IndeterminateEvent)
        .Property(
            ToggleButton::IsCheckedProperty,
            FrameworkPropertyMetadata(Nullable<bool>{false})
                .BindsTwoWayByDefault()
                .AffectsRender())
        .Property(
            ToggleButton::IsThreeStateProperty,
            FrameworkPropertyMetadata(false)
                .AffectsRender())
        .Factory();
    status = toggleButton.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<CheckBox>(context)
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto radioButton = Meta::Register<RadioButton>(context);
    radioButton
        .Property(
            RadioButton::GroupNameProperty,
            FrameworkPropertyMetadata(Base::String{}))
        .Factory();
    status = radioButton.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<ScrollContentPresenter>(context)
        .Property(
            ScrollContentPresenter::
                CanContentScrollProperty,
            FrameworkPropertyMetadata(false)
                .AffectsMeasure())
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto scrollViewer = Meta::Register<ScrollViewer>(context);
    scrollViewer
        .Event(ScrollViewer::ScrollChangedEvent)
        .Property(
            ScrollViewer::HorizontalOffsetProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::VerticalOffsetProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::ExtentWidthProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::ExtentHeightProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::ViewportWidthProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::ViewportHeightProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::ScrollableWidthProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::ScrollableHeightProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollViewer::
                ComputedHorizontalScrollBarVisibilityProperty,
            FrameworkPropertyMetadata(Visibility::Collapsed)
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            ScrollViewer::
                ComputedVerticalScrollBarVisibilityProperty,
            FrameworkPropertyMetadata(Visibility::Collapsed)
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            ScrollViewer::
                HorizontalScrollBarVisibilityProperty,
            FrameworkPropertyMetadata(
                ScrollBarVisibility::Disabled)
                .AffectsMeasure()
                .AffectsRender()
                .Changed(
                    &OnScrollViewerVisibilityChanged))
        .Property(
            ScrollViewer::
                VerticalScrollBarVisibilityProperty,
            FrameworkPropertyMetadata(
                ScrollBarVisibility::Visible)
                .AffectsMeasure()
                .AffectsRender()
                .Changed(
                    &OnScrollViewerVisibilityChanged))
        .Property(
            ScrollViewer::CanHorizontallyScrollProperty,
            FrameworkPropertyMetadata(true)
                .AffectsMeasure())
        .Property(
            ScrollViewer::CanVerticallyScrollProperty,
            FrameworkPropertyMetadata(true)
                .AffectsMeasure())
        .Property(
            ScrollViewer::CanContentScrollProperty,
            FrameworkPropertyMetadata(false)
                .AffectsMeasure())
        .Property(
            ScrollViewer::PanningModeProperty,
            FrameworkPropertyMetadata(PanningMode::None))
        .Factory();
    status = scrollViewer.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Thumb>(context)
        .Property(
            Thumb::IsDraggingProperty,
            FrameworkPropertyMetadata(false)
                .AffectsRender())
        .Factory()
        .Result();
    if (!status) return status.GetStatus();

    auto track = Meta::Register<Track>(context);
    track
        .Property(
            Track::OrientationProperty,
            FrameworkPropertyMetadata(Orientation::Vertical)
                .AffectsMeasure())
        .Property(
            Track::MinimumProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsArrange()
                .Validate(&::Aero::Base::Validate::Finite<double>))
        .Property(
            Track::MaximumProperty,
            FrameworkPropertyMetadata(1.0)
                .AffectsArrange()
                .Validate(&::Aero::Base::Validate::Finite<double>))
        .Property(
            Track::ValueProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsArrange()
                .BindsTwoWayByDefault()
                .Validate(&::Aero::Base::Validate::Finite<double>))
        .Property(
            Track::ViewportSizeProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsArrange()
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            Track::IsDirectionReversedProperty,
            FrameworkPropertyMetadata(false)
                .AffectsArrange())
        .Property<
            Base::Ref<RepeatButton>,
            &Track::SetDecreaseRepeatButton>(
                "DecreaseRepeatButton",
                PropertyFlags::Structural)
        .Property<
            Base::Ref<Thumb>,
            &Track::SetThumb>(
                "Thumb",
                PropertyFlags::Structural)
        .Property<
            Base::Ref<RepeatButton>,
            &Track::SetIncreaseRepeatButton>(
                "IncreaseRepeatButton",
                PropertyFlags::Structural)
        .Factory();
    status = track.Result();
    if (!status) return status.GetStatus();

    auto gridSplitter = Meta::Register<GridSplitter>(context);
    gridSplitter
        .Property(
            GridSplitter::DragIncrementProperty,
            FrameworkPropertyMetadata(1.0)
                .Validate(&::Aero::Base::Validate::Positive<double>))
        .Property(
            GridSplitter::KeyboardIncrementProperty,
            FrameworkPropertyMetadata(10.0)
                .Validate(&::Aero::Base::Validate::Positive<double>))
        .Property(
            GridSplitter::ResizeDirectionProperty,
            FrameworkPropertyMetadata(GridResizeDirection::Auto))
        .Property(
            GridSplitter::ResizeBehaviorProperty,
            FrameworkPropertyMetadata(GridResizeBehavior::BasedOnAlignment))
        .Property(
            GridSplitter::ShowsPreviewProperty,
            FrameworkPropertyMetadata(false))
        .Property(
            GridSplitter::PreviewStyleProperty,
            FrameworkPropertyMetadata(Base::Ref<Aero::Style>{}))
        .Factory();
    status = gridSplitter.Result();
    if (!status) return status.GetStatus();

    auto rangeBase = Meta::Register<RangeBase>(
        context, TypeFlags::Abstract);
    rangeBase
        .Event(RangeBase::ValueChangedEvent)
        .Property(
            RangeBase::MinimumProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsArrange()
                .Validate(&::Aero::Base::Validate::Finite<double>)
                .Coerce(&CoerceRangeMinimum))
        .Property(
            RangeBase::MaximumProperty,
            // WPF/AeroGUI RangeBase defaults to a 0..100 range. Controls
            // that operate in normalized coordinates set their own maximum.
            FrameworkPropertyMetadata(100.0)
                .AffectsArrange()
                .Validate(&::Aero::Base::Validate::Finite<double>)
                .Coerce(&CoerceRangeMaximum))
        .Property(
            RangeBase::ValueProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsArrange()
                .BindsTwoWayByDefault()
                .Validate(&::Aero::Base::Validate::Finite<double>)
                .Coerce(&CoerceRangeValue));
    status = rangeBase.Result();
    if (!status) return status.GetStatus();

    auto scrollBar = Meta::Register<ScrollBar>(context);
    scrollBar
        .Property(
            ScrollBar::OrientationProperty,
            FrameworkPropertyMetadata(Orientation::Vertical)
                .AffectsMeasure())
        .Property(
            ScrollBar::ViewportSizeProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsArrange()
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            ScrollBar::SmallChangeProperty,
            FrameworkPropertyMetadata(16.0)
                .Validate(&::Aero::Base::Validate::Positive<double>))
        .Property(
            ScrollBar::LargeChangeProperty,
            FrameworkPropertyMetadata(0.0)
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Factory();
    status = scrollBar.Result();
    if (!status) return status.GetStatus();

    for (Base::StringView commandName : {
             Base::StringView("LineUpCommand"),
             Base::StringView("LineUp"),
             Base::StringView("LineDownCommand"),
             Base::StringView("LineDown"),
             Base::StringView("LineLeftCommand"),
             Base::StringView("LineLeft"),
             Base::StringView("LineRightCommand"),
             Base::StringView("LineRight"),
             Base::StringView("PageUpCommand"),
             Base::StringView("PageUp"),
             Base::StringView("PageDownCommand"),
             Base::StringView("PageDown"),
             Base::StringView("PageLeftCommand"),
             Base::StringView("PageLeft"),
             Base::StringView("PageRightCommand"),
             Base::StringView("PageRight"),
             Base::StringView("ScrollToTopCommand"),
             Base::StringView("ScrollToTop"),
             Base::StringView("ScrollToBottomCommand"),
             Base::StringView("ScrollToBottom"),
             Base::StringView("ScrollToLeftEndCommand"),
             Base::StringView("ScrollToLeftEnd"),
             Base::StringView("ScrollToRightEndCommand"),
             Base::StringView("ScrollToRightEnd"),
             Base::StringView("ScrollToHorizontalOffsetCommand"),
             Base::StringView("ScrollToHorizontalOffset"),
             Base::StringView("ScrollToVerticalOffsetCommand"),
             Base::StringView("ScrollToVerticalOffset"),
             Base::StringView("DeferScrollToHorizontalOffsetCommand"),
             Base::StringView("DeferScrollToHorizontalOffset"),
             Base::StringView("DeferScrollToVerticalOffsetCommand"),
             Base::StringView("DeferScrollToVerticalOffset")}) {
        status = Input::RoutedCommand::RegisterStatic(
            ScrollBar::StaticTypeId(), commandName);
        if (!status) return status.GetStatus();
    }

    for (Base::StringView commandName : {
             Base::StringView("DecreaseSmall"),
             Base::StringView("IncreaseSmall"),
             Base::StringView("DecreaseLarge"),
             Base::StringView("IncreaseLarge")}) {
        status = Input::RoutedCommand::RegisterStatic(
            Slider::StaticTypeId(), commandName);
        if (!status) return status.GetStatus();
    }

    auto slider = Meta::Register<Slider>(context);
    slider
        .Property(
            Slider::OrientationProperty,
            FrameworkPropertyMetadata(Orientation::Horizontal)
                .AffectsMeasure())
        .Property(
            Slider::SmallChangeProperty,
            FrameworkPropertyMetadata(1.0)
                .Validate(&::Aero::Base::Validate::Positive<double>))
        .Property(
            Slider::LargeChangeProperty,
            FrameworkPropertyMetadata(10.0)
                .Validate(&::Aero::Base::Validate::Positive<double>))
        .Property(
            Slider::TickPlacementProperty,
            FrameworkPropertyMetadata(TickPlacement::None)
                .AffectsRender())
        .Property(
            Slider::TickFrequencyProperty,
            FrameworkPropertyMetadata(1.0)
                .AffectsRender()
                .Validate(&::Aero::Base::Validate::Positive<double>))
        .Property(
            Slider::TicksProperty,
            FrameworkPropertyMetadata(Base::String{})
                .AffectsRender()
                .Validate(&ValidateSliderTicks))
        .Property(
            Slider::IsSnapToTickEnabledProperty,
            FrameworkPropertyMetadata(false))
        .Property(
            Slider::IsDirectionReversedProperty,
            FrameworkPropertyMetadata(false)
                .AffectsArrange()
                .AffectsRender())
        .Property(
            Slider::IsMoveToPointEnabledProperty,
            FrameworkPropertyMetadata(false))
        .Override(
            UIElement::IsTabStopProperty,
            FrameworkPropertyMetadata(true))
        .Factory();
    status = slider.Result();
    if (!status) return status.GetStatus();

    auto tickBar = Meta::Register<TickBar>(context);
    tickBar
        .Property(
            TickBar::FillProperty,
            FrameworkPropertyMetadata(Base::Ref<Media::Brush>{})
                .AffectsRender())
        .Property(
            TickBar::PlacementProperty,
            FrameworkPropertyMetadata(TickBarPlacement::Top)
                .AffectsRender())
        .Factory();
    status = tickBar.Result();
    if (!status) return status.GetStatus();

    auto progressBar = Meta::Register<ProgressBar>(context);
    progressBar
        .Property(
            ProgressBar::IsIndeterminateProperty,
            FrameworkPropertyMetadata(false)
                .AffectsRender())
        .Property(
            ProgressBar::OrientationProperty,
            FrameworkPropertyMetadata(Orientation::Horizontal)
                .AffectsMeasure())
        .Factory();
    status = progressBar.Result();
    if (!status) return status.GetStatus();
    return {};
}
