// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsTemplates(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    auto frameworkTemplate = Meta::Register<FrameworkTemplate>(
        context, TypeFlags::Abstract);
    frameworkTemplate
        .Property<
            Base::Ref<Aero::ResourceDictionary>,
            &FrameworkTemplate::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Collection<Base::Object>(
            "Triggers",
            &AddTemplateTrigger,
            &ClearTemplateTriggers);
    status = frameworkTemplate.Result();
    if (!status) return status.GetStatus();

    auto controlTemplate = Meta::Register<ControlTemplate>(context);
    controlTemplate
        .Property<
            Meta::TypeReference,
            &GetControlTemplateTargetType,
            &SetControlTemplateTargetType>(
            "TargetType",
            PropertyFlags::None)
        .Collection<Base::Object>(
            "VisualStateGroups",
            &AddTemplateVisualStateGroup,
            &ClearTemplateVisualStateGroups)
        .Content<Base::Object>(
            "VisualTree",
            ContentKind::Single,
            &SetDeferredTemplateVisualTree<
                ControlTemplate>,
            &ClearDeferredTemplateVisualTree<
                ControlTemplate>,
            ContentFlags::Visual)
        .Factory();
    status = controlTemplate.Result();
    if (!status) return status.GetStatus();

    auto dataTemplate = Meta::Register<DataTemplate>(context);
    dataTemplate
        .Property<
            Meta::TypeReference,
            &GetDataTemplateType,
            &SetDataTemplateType>(
            "DataType",
            PropertyFlags::None)
        .Property<
            Base::Ref<Aero::ResourceDictionary>,
            &DataTemplate::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Collection<Aero::TriggerBase>(
            "Triggers",
            &AddDataTemplateTrigger,
            &ClearDataTemplateTriggers)
        .Content<Base::Object>(
            "VisualTree",
            ContentKind::Single,
            &SetDeferredTemplateVisualTree<DataTemplate>,
            &ClearDeferredTemplateVisualTree<DataTemplate>,
            ContentFlags::Visual)
        .Factory();
    status = dataTemplate.Result();
    if (!status) return status.GetStatus();

    auto dataTemplateSelector =
        Meta::Register<DataTemplateSelector>(context);
    dataTemplateSelector.Factory();
    status = dataTemplateSelector.Result();
    if (!status) return status.GetStatus();

    auto hierarchicalDataTemplate =
        Meta::Register<HierarchicalDataTemplate>(context);
    hierarchicalDataTemplate
        .Property<
            Base::Ref<Base::Object>,
            &HierarchicalDataTemplate::GetItemsSource,
            &HierarchicalDataTemplate::SetItemsSource>(
                "ItemsSource", PropertyFlags::None)
        .Property<
            Base::Ref<Base::Object>,
            &HierarchicalDataTemplate::GetItemTemplate,
            &HierarchicalDataTemplate::SetItemTemplate>(
                "ItemTemplate", PropertyFlags::None)
        .Factory();
    status = hierarchicalDataTemplate.Result();
    if (!status) return status.GetStatus();

    auto itemsPanelTemplate =
        Meta::Register<ItemsPanelTemplate>(context);
    itemsPanelTemplate
        .Property<
            Base::Ref<Aero::ResourceDictionary>,
            &ItemsPanelTemplate::SetResources>(
                "Resources",
                PropertyFlags::Structural)
        .Content<Base::Object>(
            "VisualTree",
            ContentKind::Single,
            &SetDeferredTemplateVisualTree<ItemsPanelTemplate>,
            &ClearDeferredTemplateVisualTree<ItemsPanelTemplate>,
            ContentFlags::Visual)
        .Factory();
    status = itemsPanelTemplate.Result();
    if (!status) return status.GetStatus();
    return {};
}
