// Generated by the guarded Phase 6 migration from the original ordered
// metadata bootstrap. Keep registration order stable within this unit.
Base::Result<void> PopulateControlsTextMedia(
    ::Aero::Meta::Registration& context) noexcept {
    Base::Result<void> status;
    const auto makeBrush = [](
        Base::Color color) noexcept {
        Base::Result<Base::Ref<Brush>> made =
            Media::MakeSolidColorBrush(color);
        return made
            ? std::move(made).Value()
            : Base::Ref<Brush>{};
    };
    const Base::Ref<Brush> black = makeBrush(
        {0.0F, 0.0F, 0.0F, 1.0F});
    auto textBlock = Meta::Register<TextBlock>(context);
    textBlock
        .Property(
            TextBlock::TextProperty,
            FrameworkPropertyMetadata(Base::String{})
                .AffectsMeasure())
        .Property(
            TextBlock::BackgroundProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Media::Brush>{})
                .AffectsRender())
        .Property(
            TextBlock::StrokeProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Media::Brush>{})
                .AffectsRender())
        .AddOwner(
            TextBlock::FontSizeProperty,
            FrameworkPropertyMetadata(16.0)
                .Inherits()
                .AffectsMeasure()
                .Validate(&ValidatePositiveFiniteDouble))
        .Property(
            TextBlock::FontWeightProperty,
            FrameworkPropertyMetadata(FontWeight::Normal)
                .AffectsMeasure())
        .Property(
            TextBlock::FontStyleProperty,
            FrameworkPropertyMetadata(FontStyle::Normal)
                .AffectsMeasure())
        .Property(
            TextBlock::TextDecorationsProperty,
            FrameworkPropertyMetadata(TextDecorations::None)
                .AffectsRender())
        .Property(
            TextBlock::StrokeThicknessProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsMeasure()
                .AffectsRender()
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            TextBlock::TextWrappingProperty,
            FrameworkPropertyMetadata(
                TextWrapping::NoWrap)
                .AffectsMeasure())
        .Property(
            TextBlock::TextTrimmingProperty,
            FrameworkPropertyMetadata(
                TextTrimming::None)
                .AffectsMeasure())
        .Property(
            TextBlock::TextAlignmentProperty,
            FrameworkPropertyMetadata(
                TextAlignment::Left)
                .AffectsMeasure())
        .Property(
            TextBlock::LineHeightProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsMeasure()
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            TextBlock::PaddingProperty,
            FrameworkPropertyMetadata(Aero::Thickness{})
                .AffectsMeasure()
                .AffectsArrange()
                .Validate(&ValidateThicknessValue))
        .Property<
            Value,
            &TextBlock::GetMetadataInlines,
            &TextBlock::SetInlineValue>(
            "Inlines",
            PropertyFlags::AnyValue |
                PropertyFlags::Collection |
                PropertyFlags::Structural)
        .ContentAccessor(
            MakeMemberId(
                TextBlock::StaticTypeId(),
                MemberKind::Property,
                "Inlines"),
            ContentKind::Collection,
            &AddTextBlockInline,
            &ClearTextBlockInlines,
            ContentFlags::None)
        .Factory();
    status = textBlock.Result();
    if (!status) return status.GetStatus();

    auto textElement = Meta::Register<Documents::TextElement>(
        context, TypeFlags::Abstract);
    textElement
        .Property(
            Documents::TextElement::FontFamilyProperty,
            FrameworkPropertyMetadata(Base::Ref<Media::FontFamily>{})
                .Inherits().AffectsMeasure())
        .Property(
            Documents::TextElement::FontWeightProperty,
            FrameworkPropertyMetadata(FontWeight::Normal).Inherits().AffectsMeasure())
        .Property(
            Documents::TextElement::ForegroundProperty,
            FrameworkPropertyMetadata(Base::Ref<Brush>{}).Inherits())
        .Property(
            Documents::TextElement::FontSizeProperty,
            FrameworkPropertyMetadata(16.0).Inherits().Validate(
                &ValidatePositiveFiniteDouble))
        .Property(
            Documents::TextElement::FontStyleProperty,
            FrameworkPropertyMetadata(FontStyle::Normal).Inherits())
        .Property(
            Documents::TextElement::TextDecorationsProperty,
            FrameworkPropertyMetadata(TextDecorations::None).Inherits());
    status = textElement.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Documents::Inline>(
        context, TypeFlags::Abstract).Result();
    if (!status) return status.GetStatus();

    auto run = Meta::Register<Documents::Run>(context);
    run
        .Property(
            Documents::Run::TextProperty,
            FrameworkPropertyMetadata(Base::String{}).Structural())
        .Content(Documents::Run::TextProperty.Id())
        .Factory();
    status = run.Result();
    if (!status) return status.GetStatus();

    auto span = Meta::Register<Documents::Span>(context);
    span
        .Property<
            Value,
            &Documents::Span::GetMetadataInlines,
            &Documents::Span::SetInlineValue>(
                "Inlines",
                PropertyFlags::AnyValue |
                    PropertyFlags::Collection |
                    PropertyFlags::Structural)
        .ContentAccessor(
            MakeMemberId(
                Documents::Span::StaticTypeId(),
                MemberKind::Property,
                "Inlines"),
            ContentKind::Collection,
            &AddSpanInline,
            &ClearSpanInlines,
            ContentFlags::None)
        .Factory();
    status = span.Result();
    if (!status) return status.GetStatus();

    auto bold = Meta::Register<Documents::Bold>(context);
    bold
        .Override(
            Documents::TextElement::FontWeightProperty,
            FrameworkPropertyMetadata(FontWeight::Bold)
                .AffectsMeasure())
        .Factory();
    status = bold.Result();
    if (!status) return status.GetStatus();

    auto italic = Meta::Register<Documents::Italic>(context);
    italic
        .Override(
            Documents::TextElement::FontStyleProperty,
            FrameworkPropertyMetadata(FontStyle::Italic)
                .AffectsMeasure())
        .Factory();
    status = italic.Result();
    if (!status) return status.GetStatus();

    auto underline = Meta::Register<Documents::Underline>(context);
    underline
        .Override(
            Documents::TextElement::TextDecorationsProperty,
            FrameworkPropertyMetadata(TextDecorations::Underline)
                .AffectsRender())
        .Factory();
    status = underline.Result();
    if (!status) return status.GetStatus();

    auto lineBreak = Meta::Register<Documents::LineBreak>(context);
    lineBreak.Factory();
    status = lineBreak.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Documents::RequestNavigateEventArgs>(context)
        .Result();
    if (!status) return status.GetStatus();

    auto hyperlink = Meta::Register<Documents::Hyperlink>(context);
    hyperlink
        .Event(Documents::Hyperlink::ClickEvent)
        .Event(Documents::Hyperlink::RequestNavigateEvent)
        .Property(
            Documents::Hyperlink::NavigateUriProperty,
            FrameworkPropertyMetadata(Base::String{}))
        .Property(
            Documents::Hyperlink::CommandProperty,
            FrameworkPropertyMetadata(Base::Ref<ICommand>{}))
        .Property(
            Documents::Hyperlink::CommandParameterProperty,
            FrameworkPropertyMetadata(Value::NullObject(
                TypeOf<Base::Object>())))
        .Property(
            Documents::Hyperlink::CommandTargetProperty,
            FrameworkPropertyMetadata(Base::Ref<UIElement>{}))
        .Override(
            Documents::TextElement::TextDecorationsProperty,
            FrameworkPropertyMetadata(TextDecorations::Underline)
                .AffectsRender())
        .Factory();
    status = hyperlink.Result();
    if (!status) return status.GetStatus();

    auto image = Meta::Register<Image>(context);
    image
        .Property(
            Image::SourceProperty,
            FrameworkPropertyMetadata(
                Base::Ref<ImageSource>{})
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            Image::StretchProperty,
            FrameworkPropertyMetadata(Stretch::Uniform)
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            Image::StretchDirectionProperty,
            FrameworkPropertyMetadata(
                StretchDirection::Both)
                .AffectsMeasure()
                .AffectsRender())
        .Factory();
    status = image.Result();
    if (!status) return status.GetStatus();

    status = Meta::Register<Shape>(
        context, TypeFlags::Abstract)
        .Property(
            Shape::FillProperty,
            FrameworkPropertyMetadata(Base::Ref<Brush>{})
                .AffectsRender()
                .Changed(&OnShapeFillChanged))
        .Property(
            Shape::StrokeProperty,
            FrameworkPropertyMetadata(Base::Ref<Brush>{})
                .AffectsRender()
                .Changed(&OnShapeFillChanged))
        .Property(
            Shape::StrokeThicknessProperty,
            FrameworkPropertyMetadata(1.0)
                .AffectsMeasure()
                .AffectsRender()
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            Shape::StretchProperty,
            FrameworkPropertyMetadata(Stretch::Fill)
                .AffectsMeasure()
                .AffectsRender())
        .Result();
    if (!status) return status.GetStatus();

    auto rectangle = Meta::Register<Rectangle>(context);
    rectangle
        .Property(
            Rectangle::RadiusXProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsRender()
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Property(
            Rectangle::RadiusYProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsRender()
                .Validate(&::Aero::Base::Validate::NonNegative<double>))
        .Factory();
    status = rectangle.Result();
    if (!status) return status.GetStatus();

    auto ellipse = Meta::Register<Ellipse>(context);
    ellipse.Factory();
    status = ellipse.Result();
    if (!status) return status.GetStatus();

    auto path = Meta::Register<Path>(context);
    path
        .Property(
            Path::DataProperty,
            FrameworkPropertyMetadata(
                Base::Ref<
                    Media::Geometry>{})
                .AffectsMeasure()
                .AffectsRender()
                .Changed(&OnPathDataChanged))
        .Property(
            Path::FillProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Media::Brush>{})
                .AffectsRender()
                .Changed(&OnPathColorChanged))
        .Property(
            Path::StrokeProperty,
            FrameworkPropertyMetadata(
                Base::Ref<Media::Brush>{})
                .AffectsRender()
                .Changed(&OnPathColorChanged))
        .Property(
            Path::StrokeThicknessProperty,
            FrameworkPropertyMetadata(1.0)
                .AffectsMeasure()
                .AffectsRender()
                .Validate(&::Aero::Base::Validate::NonNegative<double>)
                .Changed(&OnPathDoubleChanged))
        .Property(
            Path::StrokeLineJoinProperty,
            FrameworkPropertyMetadata(PenLineJoin::Miter)
                .AffectsRender()
                .Changed(&OnPathLineJoinChanged))
        .Property(
            Path::StrokeStartLineCapProperty,
            FrameworkPropertyMetadata(PenLineCap::Flat)
                .AffectsRender()
                .Changed(&OnPathLineCapChanged))
        .Property(
            Path::StrokeEndLineCapProperty,
            FrameworkPropertyMetadata(PenLineCap::Flat)
                .AffectsRender()
                .Changed(&OnPathLineCapChanged))
        .Property(
            Path::TrimStartProperty,
            FrameworkPropertyMetadata(0.0)
                .AffectsRender()
                .Validate(&ValidateNormalizedDouble)
                .Changed(&OnPathDoubleChanged))
        .Property(
            Path::TrimEndProperty,
            FrameworkPropertyMetadata(1.0)
                .AffectsRender()
                .Validate(&ValidateNormalizedDouble)
                .Changed(&OnPathDoubleChanged))
        .Property(
            Path::StretchProperty,
            FrameworkPropertyMetadata(Stretch::Uniform)
                .AffectsMeasure()
                .AffectsRender())
        .Factory();
    status = path.Result();
    if (!status) return status.GetStatus();

    const Base::Ref<Brush> selection = makeBrush({
        46.0F / 255.0F,
        174.0F / 255.0F,
        235.0F / 255.0F,
        1.0F});
    const Base::Ref<Brush> placeholder = makeBrush({
        123.0F / 255.0F,
        128.0F / 255.0F,
        133.0F / 255.0F,
        1.0F});
    auto textBoxBase = Meta::Register<TextBoxBase>(
        context, TypeFlags::Abstract);
    textBoxBase
        .Property(
            TextBoxBase::SelectionBrushProperty,
            FrameworkPropertyMetadata(selection)
                .AffectsRender())
        .Property(
            TextBoxBase::SelectionOpacityProperty,
            FrameworkPropertyMetadata(0.25)
                .AffectsRender()
                .Validate(&ValidateNormalizedDouble))
        .Property(
            TextBoxBase::CaretBrushProperty,
            FrameworkPropertyMetadata(black)
                .AffectsRender());
    status = textBoxBase.Result();
    if (!status) return status.GetStatus();

    auto textBox = Meta::Register<TextBox>(context);
    textBox
        .Event(TextBox::TextChangedEvent)
        .Property(
            TextBox::TextProperty,
            FrameworkPropertyMetadata(Base::String{})
                .AffectsMeasure()
                .AffectsRender()
                .BindsTwoWayByDefault()
                .UpdateSource(
                    UpdateSourceTrigger::LostFocus)
                .Coerce(&CoerceTextBoxText))
        .Property(
            TextBox::IsReadOnlyProperty,
            FrameworkPropertyMetadata(false)
                .AffectsRender())
        .Property(
            TextBox::MaxLengthProperty,
            FrameworkPropertyMetadata(std::uint32_t{0}))
        .Property(
            TextBox::AcceptsReturnProperty,
            FrameworkPropertyMetadata(false)
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            TextBox::TextWrappingProperty,
            FrameworkPropertyMetadata(
                TextWrapping::NoWrap)
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            TextBox::PlaceholderProperty,
            FrameworkPropertyMetadata(Base::String{})
                .AffectsMeasure())
        .Property(
            TextBox::PlaceholderForegroundProperty,
            FrameworkPropertyMetadata(placeholder)
                .AffectsRender())
        .Property(
            TextBox::FontSizeProperty,
            FrameworkPropertyMetadata(15.0)
                .AffectsMeasure()
                .Validate(
                    &ValidatePositiveFiniteDouble))
        .Property(
            TextBox::FontWeightProperty,
            FrameworkPropertyMetadata(FontWeight::Normal)
                .AffectsMeasure())
        .Property(
            TextBox::FontStyleProperty,
            FrameworkPropertyMetadata(
                FontStyle::Normal)
                .AffectsMeasure())
        .Property(
            TextBox::TextAlignmentProperty,
            FrameworkPropertyMetadata(
                TextAlignment::Left)
                .AffectsMeasure())
        .Property(
            TextBox::MaxLinesProperty,
            FrameworkPropertyMetadata(std::uint32_t{0})
                .AffectsMeasure()
                .AffectsRender())
        .Property(
            TextBox::MinLinesProperty,
            FrameworkPropertyMetadata(std::uint32_t{1})
                .AffectsMeasure()
                .AffectsRender()
                .Validate(
                    &::Aero::Base::Validate::Positive<
                        std::uint32_t>))
        .Factory();
    status = textBox.Result();
    if (!status) return status.GetStatus();

    auto passwordBox = Meta::Register<PasswordBox>(context);
    Base::String defaultPasswordChar;
    status = defaultPasswordChar.Assign(
        Base::StringView(u8"\u2022"));
    if (!status) return status.GetStatus();
    passwordBox
        .Event(PasswordBox::PasswordChangedEvent)
        .Property<
            Base::String,
            &PasswordBox::GetPassword,
            &PasswordBox::SetPassword>(
                "Password", PropertyFlags::None)
        .Property(
            PasswordBox::PasswordCharProperty,
            FrameworkPropertyMetadata(
                std::move(defaultPasswordChar))
                .AffectsMeasure()
                .Validate(&ValidatePasswordChar))
        .Property(
            PasswordBox::MaxLengthProperty,
            FrameworkPropertyMetadata(std::uint32_t{0})
                .AffectsMeasure())
        .Property(
            PasswordBox::PlaceholderProperty,
            FrameworkPropertyMetadata(Base::String{})
                .AffectsMeasure()
                .AffectsRender())
        .Factory();
    status = passwordBox.Result();
    if (!status) return status.GetStatus();

    auto contentPresenter = Meta::Register<ContentPresenter>(context);
    contentPresenter
        .Property(
            ContentPresenter::ContentProperty,
            FrameworkPropertyMetadata(
                Meta::Value::NullObject(
                    Meta::TypeOf<Base::Object>()))
                .AffectsMeasure()
                .Structural()
                .Changed(
                    &ContentPresenter::
                        OnContentPropertyChanged))
        .Property(
            ContentPresenter::ContentTemplateProperty,
            FrameworkPropertyMetadata(Base::Ref<Base::Object>{})
                .AffectsMeasure())
        .Property(
            ContentPresenter::ContentSourceProperty,
            FrameworkPropertyMetadata(Base::String{}))
        .ContentAccessor(
            MakeMemberId(
                ContentPresenter::StaticTypeId(),
                MemberKind::Property,
                "Content"),
            ContentKind::Single,
            &SetContentPresenterContent,
            &ClearContentPresenterContent,
            ContentFlags::Visual)
        .Factory();
    status = contentPresenter.Result();
    if (!status) return status.GetStatus();
    return {};
}
